### ISSUE TITLE
implement page for displaying entity details and table for the enzyme database

### ISSUE THREAD

**Issue by e0** [MetabolicAtlas/MetabolicAtlas#1014]
**Please describe the feature**

As a user, I want to see relevant details for an entity (for example a reaction), so that I can have a quick overview of the entity and its related cross references.

As a user, I want to have access to a table of relevant fields associated with an entity (for example a reaction), so that I can browse through and understand which other entities and field values it is associated with.

**Acceptance Criteria**

- [x] If available, display the basic fields for an entity. This is the first table from the top in the attached UX mockup.
- [x] If available, display the cross references for an entity. This is the second table from the top in the attached UX mockup.
- [x] An interactive table should be displayed that lists all of of related entities and field values the entity is associated with.
  - [x] The table should be server-side paginated. Page size should be 50.
  - [x] Every column should be sortable.
  - [x] Every column, with the exception of `kcat`, should be filterable. Only filter on exact matches for now. Filtered results should still be server-side paginated.
- [x] Display an error message if no entity is found.
- [x] The URLs should follow the format: `/enzymedb/ENTITY_TYPE/ENTITY_ID`.
  - `enzymedb` is a working name, if should be updated if it gets changed by the researchers.
  - The exact entity types should be clear once the actual data files are ready.
- [ ] The changes are in alignment with the privacy policy
- [ ] The changes are tested on multiple models and browsers
- [ ] Tests verifying the changes are added
- [ ] The API response is the same as before
- [ ] The changes do not affect the deployment
- [ ] The changes do not reduce the performance

**Additional context**

- This issue should follow the work from #1008.
- Mock data should be replaced with actual data once it's available.

UX mockup
<img width="1295" alt="image" src="https://user-images.githubusercontent.com/423498/171815326-42ab4c26-c7d7-4b9a-a154-70162f265e94.png">

**Comment by e0** [comment]
It would be nice if the search input is also available from this page so the user can quickly jump to another entity.

**Comment by mihai-sysbio** [comment]
> It would be nice if the search input is also available from this page so the user can quickly jump to another entity.

Interesting idea! For inspiration, it is something we had in a previous version of the GEM Browser, a recording of which should be stored.
