### ISSUE TITLE
implement landing page for the enzyme database

### ISSUE THREAD

**Issue by e0** [MetabolicAtlas/MetabolicAtlas#1015]
**Please describe the feature**

As a user, I want to have a landing page for the enzyme database so that I can understand its purpose and search for enzyme details based on KEGG identifiers.

**Acceptance Criteria**

- [ ] Add landing visual elements as indicated in the UX mockup.
  - [ ] banner
  - [ ] search field
  - [ ] KEGG id examples The exact KEGG id suggestions may differ from the mockup. It should be clearer which entity types should be used once the actual data files are ready.
  - [ ] About the project
- [ ] Entering a term into the search field and clicking the "Enter/Return" key from the keyboard should take the user to the entity specific page. That page is responsible for displaying the error message as described in #1014.
- [ ] A new navbar item should be added as indicated in the UX mockup.
  - [ ] `EnzymeDB` is a working name, if should be updated if it gets changed by the researchers.
  - [ ] The URL should be `/enzymedb`. It should be updated if necessary as in above todo.
- [ ] The changes are in alignment with the privacy policy
- [ ] The changes are tested on multiple models and browsers
- [ ] The API response is the same as before
- [ ] The changes do not affect the deployment
- [ ] The changes do not reduce the performance

**Additional context**

- This issue should follow the work of #1014.

UX mockup
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/423498/171818225-dfc33c7c-35b6-439c-bcd2-a5177e5166a5.png">

**Comment by mihai-sysbio** [comment]
@mihai-sysbio to get all the required text from the researchers.

**Comment by feiranl** [comment]
Will do this today.
