### ISSUE TITLE
Enable approximate searching on the EnzymeDB landing page

### ISSUE THREAD

**Issue by nanjiangshu** [MetabolicAtlas/MetabolicAtlas#1025]
**Please describe the feature**

As a user, I want to be able to search by partial strings.

**Acceptance Criteria**

- [ ] Placeholder for issue specific criterion
- [ ] The web page documentation is updated accordingly
- [ ] The changes are in alignment with the privacy policy
- [ ] The changes are tested on multiple models and browsers
- [ ] Tests verifying the changes are added
- [ ] The API response is the same as before
- [ ] The changes do not affect the deployment
- [ ] The changes do not reduce the performance

**Additional context**

Potentially closed by #1027.

**Comment by e0** [comment]
Closing since it's being covered in #1027.
