### ISSUE TITLE
Implement Quick Search for the EnzymeDB landing page

### ISSUE THREAD

**Issue by nanjiangshu** [MetabolicAtlas/MetabolicAtlas#1027]
**Please describe the feature**

As a user, I want the same search functionality as in the GEM browser so that I can see suggestions even for partial strings.

**Acceptance Criteria**

- [x] 5-10 suggestions maximum
- [x] Should be reasonably fast
- [x] The changes are in alignment with the privacy policy
- [x] The changes are tested on multiple models and browsers
- [x] The API response is the same as before
- [x] The changes do not reduce the performance
- [x] The web page documentation is updated accordingly
- [x] The changes do not affect the deployment
- [ ] Tests verifying the changes are added

**Additional context**

Re-use as much as possible from the existing quick search.
Does not have to be grouped by type.
Only one character is needed to search for domains, maybe remove the restriction of 2 characters totally.

If possible, this could solve issue #1028.

**Comment by e0** [comment]
It would be nice if the search input is available from the details pages too, as mentioned by @inghylt : https://github.com/MetabolicAtlas/MetabolicAtlas/pull/1031#issuecomment-1157540146

**Comment by e0** [comment]
For quick/fuzzy search to be possible, the database needs to be indexed accordingly. Currently, the number of proteins/genes is the bottleneck in both indexing speed and performance. For my local machine, I think the indexing for proteins alone takes +20min. Performing a search takes about 5s. This makes sense as there are nearly 6 million proteins compared to the other entities which are in the thousands.

To circumvent this problem, the researchers and devs have jointly decided to drop the fuzzy search for proteins, at least for this iteration. So the search would combine the fuzzy search results from the other entities together with the exact match results for proteins (ranked at the top). This should greatly introduce the speed of both indexing and searching. I will start with the changes for this now .

**Comment by mihai-sysbio** [comment]
Sounds great @shan-chalmers, thanks for the write-up!

**Comment by e0** [comment]
Here is a quick preview of how this looks like when making an `api` request.

<img width="697" alt="image" src="https://user-images.githubusercontent.com/423498/175941638-b0adbb78-6e0e-4981-be29-ef85453e69c2.png">
