### ISSUE TITLE
Update sprint responsibility sheet

### ISSUE THREAD

**Issue by MalinAhlberg** [MetabolicAtlas/MetabolicAtlas#1029]
**Please describe the feature**

As a developer, I want one updated source of information about this sprint so that I can easily access it and read it.

**Acceptance Criteria**

- [X] Google doc sheet "sprint note taking and review presenter" and https://github.com/MetabolicAtlas/docs/wiki/Story-points-log should be merged
- [X] Each sprint should be referenced by its dates, not a month
- [X] As we don't deploy every sprint, that column should be separated from the sprints
- [X] The documentation (readme's, wiki pages) is updated accordingly

**Comment by MalinAhlberg** [comment]
I have updated the wiki page to contain all information: https://github.com/MetabolicAtlas/docs/wiki/Sprint-responsibilities-and-Story-points-log

Please have a look! If you think it's fine, I'll update the documentation accordingly.

**Comment by e0** [comment]
Looks great @MalinAhlberg!

**Comment by mihai-sysbio** [comment]
There was a broken link in the sidebar menu, but with that fixed I also consider this issue resolved.

**Comment by MalinAhlberg** [comment]
@nanjiangshu you mean that we only use 1,3,5?

**Comment by MalinAhlberg** [comment]
I added a note about that at the bottom of the page.
I also fixed the link mentioned by @mihai-sysbio and updated related wiki pages so that the links are correct.
