### ISSUE TITLE
add details pages for other categories

### ISSUE THREAD

**Issue by mihai-sysbio** [MetabolicAtlas/MetabolicAtlas#1032]
**Please describe the feature**

As a user, I want to see details for all the items listed on the main page of EnzymeDB.

**Acceptance Criteria**

- [x] Add details pages for `protein`, `organism`, and `domain`. Please note that these pages do not have any supplementary data and the shared details page component may need to be updated accordingly.
- [x] Make sure that the enzymes table column matching the current page should not be displayed. For example, do not display the `Reaction` column on a reaction details page.
- [x] Update the GotEnzymes landing page to handle the new types of details pages.
  - [x] Add working examples like in the attached screenshot. Please note that `gene` should be `protein`.
  - [x] Add new redirection rules for the new types, `domain` should always be a single letter for example. Existing rules may need to be updated if there is overlap with the new ones.
- [x] Add links in the enzymes table for all of the types that have details pages (fields listed on the landing page).
- [ ] The web page documentation is updated accordingly
- [ ] The changes are in alignment with the privacy policy
- [ ] The changes are tested on multiple models and browsers
- [ ] Tests verifying the changes are added
- [ ] The API response is the same as before
- [ ] The changes do not affect the deployment
- [ ] The changes do not reduce the performance

**Additional context**

![image.png](https://images.zenhubusercontent.com/5e29ab0b256e0f269fabd654/ab287d11-edcd-429c-a907-fb1c8c977ea5)

**Comment by e0** [comment]
Notes from meeting regarding this issue are below. The issue description should be edited properly using the regular template with the notes when there is time. 

- display protein instead of gene on landing page
- for the details page, omit the column from the enzymes table that is of the same type, for example do not display the Reaction column on a reaction details page
- domain should always be a single letter
- add simple redirection rules

**Comment by MalinAhlberg** [comment]
I'm not sure how to handle the redirects of search queries from the landing page. The below can be both organisms and proteins:
```  adk amn apt asd cca cls cmk dra drm eno fba gap maf ndk pdp pfk pfs pgi pgm pnp psd pta rpe sul tal tpi```

**Comment by mihai-sysbio** [comment]
@MalinAhlberg how about redirect to proteins first, and mentioned this duplication in #1027 ?

**Comment by MalinAhlberg** [comment]
> @MalinAhlberg how about redirect to proteins first, and mentioned this duplication in #1027 ?

I believe that the cases I mentioned are handled by [the current code.](https://github.com/MetabolicAtlas/MetabolicAtlas/pull/1043/files#diff-45912df86d4ffaa92ba6e953125c965dadf12b4dc9499fa51bc3834c67b3cad9R205)
