### ISSUE TITLE
add API tests for GotEnzymes

### ISSUE THREAD

**Issue by MalinAhlberg** [MetabolicAtlas/MetabolicAtlas#1048]
**Please describe the feature**

As a developer, I want tests so that I can be sure that everything is working as expected.

**Acceptance Criteria**

- [ ] Tests added for the detail pages (one for each type of data)
- [ ] One or more tests for the search functionality
- [ ] Test the enzymes table

**Additional context**

This issue is partly a leftover from #1032.
The performance aspect is not meant to be tested as part of this issue.

**Comment by inghylt** [comment]
Very nice to have tests in place soon so we don't end up in these situations where api breakage might go unnoticed https://github.com/MetabolicAtlas/MetabolicAtlas/pull/1095#pullrequestreview-1078398586
