### ISSUE TITLE
expose API endpoints for GotEnzymes

### ISSUE THREAD

**Issue by mihai-sysbio** [MetabolicAtlas/MetabolicAtlas#1065]
**Please describe the feature**

As a user, I want to be able to use GotEnzymes via the API, so that I can built it into my workflows,

**Acceptance Criteria**

- [ ] expose API for individual components (gene, compound, reaction and organism - not domain)
- [ ] The web page documentation is updated accordingly
- [ ] The changes are in alignment with the privacy policy
- [ ] The changes are tested on multiple models and browsers
- [ ] Tests verifying the changes are added
- [ ] The API response is the same as before
- [ ] The changes do not affect the deployment
- [ ] The changes do not reduce the performance

**Additional context**
There is a built-in limit to the amount of entries that can be fetched from the database. For now, the purpose is to be able to at least use the API. Ideally, one should be able to fetch all entries for a given organism, but that is optional for the current issue - if it's too much work now then a seperate issue may be opened instead.

**Comment by inghylt** [comment]
@mihai-sysbio just to make things clear:

- _Expose API for individual components_, does that mean adding examples to swagger? Since you can already reach the gotenzymes data through for example https://dev-metatlas.csbi.chalmers.se/api/v2/gotenzymes/enzymes?filters[compound]=C00003&pagination[page]=1&pagination[pageSize]=50&pagination[column]=gene&pagination[isAscending]=true
- _The web page documentation is updated accordingly_, does that mean adding a section in the /documentation page with for example title `GotEnzymes`?
-  _Tests verifying the changes are added_, what kind of test do you have in mind here?

**Comment by mihai-sysbio** [comment]
> @mihai-sysbio just to make things clear:
> 
>     * _Expose API for individual components_, does that mean adding examples to swagger? Since you can already reach the gotenzymes data through for example [https://dev-metatlas.csbi.chalmers.se/api/v2/gotenzymes/enzymes?filters[compound]=C00003&pagination[page]=1&pagination[pageSize]=50&pagination[column]=gene&pagination[isAscending]=true](https://dev-metatlas.csbi.chalmers.se/api/v2/gotenzymes/enzymes?filters%5Bcompound%5D=C00003&pagination%5Bpage%5D=1&pagination%5BpageSize%5D=50&pagination%5Bcolumn%5D=gene&pagination%5BisAscending%5D=true)

Yes, an API implies a public description of the endpoints in my view, so examples to Swagger is exactly what is needed.

>     * _The web page documentation is updated accordingly_, does that mean adding a section in the /documentation page with for example title `GotEnzymes`?

The _Documentation_ briefly covers the API, so that should be expanded a bit.

>     * _Tests verifying the changes are added_, what kind of test do you have in mind here?

I personally don't think tests would be needed, but I kept the checklist item in case somebody else things differently.

**Comment by inghylt** [comment]
@mihai-sysbio I assume you want a swagger example for each url below?
/gotenzymes/gene/{somegene}
/gotenzymes/compound/{somecompound}
/gotenzymes/reaction/{somecreaction}
/gotenzymes/ec/{someenzyme}
/gotenzymes/organism/{someorganism}
/gotenzymes/domain/{somedomain}

**Comment by mihai-sysbio** [comment]
> @mihai-sysbio I assume you want a swagger example for each url below?
> /gotenzymes/gene/{somegene}
> /gotenzymes/compound/{somecompound}
> /gotenzymes/reaction/{somecreaction}
> /gotenzymes/ec/{someenzyme}
> /gotenzymes/organism/{someorganism}
> /gotenzymes/domain/{somedomain}

That would be ideal. Let me know if any poses difficulties, so we may adapt.
A side note, the API response is meant to stay as is - no changes are planned as part of this issue.

A new request is that the API should be bumped to `v3`.

**Comment by inghylt** [comment]
@mihai-sysbio should it be bumped to v3 in this or a separate issue?

**Comment by mihai-sysbio** [comment]
> @mihai-sysbio should it be bumped to v3 in this or a separate issue?

However you see fit! It might be easy enough here, but it's just a hunch.
