### ISSUE TITLE
Inconsistent behavior when clicking links to the about pages on mobile devices

### ISSUE THREAD

**Issue by MalinAhlberg** [MetabolicAtlas/MetabolicAtlas#1068]
**Describe the bug**

Clicking links to some sections of the About pages from the Table of Content does does not scroll to the right place.

**Steps to reproduce**

- Click eg "Contact us" from the "Table of Content" on a mobile device (scrolls to the "Contact us" section)
- Compare to clicking "News" (stays on the menu)

**Expected behavior**

- [ ] Clicking a link from the TOC will consistently either scroll to the correct place or stay on the menu
- [ ] Clicking a link from the Nav Bar will  consistently either scroll to the correct place or stay on the menu
- [ ] Links at the "Documentation" pages still work as expected
- [ ] Tested on different browsers and devices

**Additional context**

See `frontend/src/content/about.js` The TOC uses links rather than router names, to allow scrolling to anchors on the page. The Nav Bar uses the router names.

See also discussions at https://github.com/MetabolicAtlas/MetabolicAtlas/pull/1064.

**Comment by inghylt** [comment]
The News section is also a bit broken on non mobile, if you have pressed a subsection before and press News, it will not start from the top
