### ISSUE TITLE
add identifier registry link to MA id pages

### ISSUE THREAD

**Issue by mihai-sysbio** [MetabolicAtlas/MetabolicAtlas#1071]
**Please describe the feature**

As a user, I want to know how I can use MA ids with an identifier registry, so that I can use it.

**Acceptance Criteria**

- [ ] an url on the pages `/identifier/MetabolicAtlas/..` 
- [ ] the web page documentation is updated to also mention this, add section
- [ ] The API response is the same as before
- [ ] The changes do not affect the deployment
- [ ] The changes do not reduce the performance

**Additional context**

**Comment by MalinAhlberg** [comment]
https://metabolicatlas.org/identifier/MetabolicAtlas/MAM02877s
