### ISSUE TITLE
Faulty swagger for section Miscellaneous

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#1073]
**Describe the bug**

1. The swagger page hangs for /maps/listing?model={model}
2. The provided information is not entirely correct for /random-components?model={model}&componentTypes={componentTypes}

**Steps to reproduce**

1. 
- Visit `/api/v2/#/Miscellaneous/mapListing`
- Follow the instructions
- Note that the page hangs

2.
- Visit `/api/v2/#/Miscellaneous/randomComponentInfo`
- Follow the instructions
- Note that you get 404 if you leave out componentTypes even though it is not marked as required

**Expected behavior**

- [ ] That the above situations does not ocurr

**Screenshots**

**Additional context**

**Comment by mihai-sysbio** [comment]
A suggestion for @e0 is to have a better default value for (2).
