### ISSUE TITLE
Update dependencies for 3D-network-viewer

### ISSUE THREAD

**Issue by nanjiangshu** [MetabolicAtlas/MetabolicAtlas#1080]
**Please describe the feature**

As a developer, I want all dependencies to be updated so that potential vulnerabilities are resolved.

**Acceptance Criteria**

- [ ] Fix all dependatbot's PRs
- [ ] Check all other dependencies
- [ ] The changes are tested on multiple browsers
- [ ] The changes do not affect the deployment
- [ ] The changes do not reduce the performance

**Additional context**

**Comment by inghylt** [comment]
https://github.com/MetabolicAtlas/docs/wiki/Dependency-management Might have some useful information even though 3d-network-viewer is a different repo

**Comment by mihai-sysbio** [comment]
I believe this issue was resolved through this PR https://github.com/MetabolicAtlas/3d-network-viewer/pull/49 so I will close it.

@e0 please re-open if needed, and feel free to adjust the estimate.

**Comment by e0** [comment]
Since we haven't published a new version from that repo yet and merged into this one I think this issue should be open for now.
