### ISSUE TITLE
Explore if there are parts of the code that needs to be tested

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#1082]
**Please describe the feature**

["It is SUGGESTED that the test suite cover most (or ideally all) the code branches, input fields, and functionality."](https://bestpractices.coreinfrastructure.org/en/projects/4276/#quality)

As a developer, I would like to know that all relevant parts of the code base are tested, so that I know that changes I make don't create bugs that are missed during PR reviews

**Acceptance Criteria**

- [ ] Research if all relevant parts of the code base are tested
- [ ] Add test if needed or create new issues
- [ ] Make sure the test are robust so they can handle model updating

**Additional context**

**Comment by KattisLej** [comment]
Moved this issue into the test policy issue #1083
