### ISSUE TITLE
metabolite images in GEM Browser and GotEnzymes

### ISSUE THREAD

**Issue by mihai-sysbio** [MetabolicAtlas/MetabolicAtlas#1096]
**Please describe the feature**

As a user, I want to see metabolite images on metabolite/compound pages, so that I can more quickly recognize the molecule I'm after.

**Acceptance Criteria**

- [ ] our own metabolite images in the GEM Browser
- [ ] our own metabolite images in GotEnzymes
- [ ] The changes do not affect the deployment
- [ ] The changes do not reduce the performance

**Additional context**

For the GEM Browser, metabolite images are fetched dynamically based on the ChEBI id. However, there can be issues with the requests, and the annotation itself (not all metabolites have associated ChEBI ids). For GotEnzymes, the compounds don't have the ChEBI cross-reference at all.
As part of this feature, it is envisioned to change the source of metabolites from ChEBI to our own, based on the  KEGG id. While this is an about 10% decrease in coverage based on the current cross-references, relying on our own images is a better option.
Alternatively, if there is a KEGG mapping, our own image is loaded; otherwise if there is a ChEBI cross-reference, the request for that external image can be sent.

edit: An attempt should be made to generate the images dynamically first. While JS is preferred, here is a tool that may be used 
https://www.rdkit.org/docs/GettingStartedInPython.html#drawing-molecules

**Comment by inghylt** [comment]
RdKit seems to exist for js: https://github.com/rdkit/rdkit-js

**Comment by mihai-sysbio** [comment]
I'd also like to know more about the possibility to go serverless for this, for example with Cloudfare workers https://www.cloudflare.com/plans/developer-platform/#add-ons

**Comment by e0** [comment]
> I'd also like to know more about the possibility to go serverless for this, for example with Cloudfare workers https://www.cloudflare.com/plans/developer-platform/#add-ons

I would love to explore this kind of options! I think it would make the most sense to have a separate repo for this since it could be used as a standalone service. It would also simplify the devops process.

**Comment by e0** [comment]
Update regarding server less possibility. It seems that rdkit.js relies on some browser features (such as attaching the main init function to `window`) so it's not directly compatible with cloudflare workers. It was trivial to create a Vue component though and we can load from CDN to avoid increasing bundle size (we can of course bundle it as well if that's preferable). So far it seems to work well, will try to create a PR soon.

**Comment by mihai-sysbio** [comment]
The main reason I see for going serverless is the computation that needs to be performed by our machine that can add up. Many users looking at metabolites at the same time increases the resources we need to have available. And thinking that this visualisation would be added to reactions as well (at least, as far as it we know atm), it's important to have a long-term thinking about this feature. Have you made any investigations about this @e0?

**Comment by e0** [comment]
@mihai-sysbio As I mentioned in the last comment, this visualization is now being done on the client side, which means inside the browser. So the visualization logic is not touching the server.
