### ISSUE TITLE
Searching for "nucleophagy" in 2D Map Viewer pops up an error window

### ISSUE THREAD

**Issue by nanjiangshu** [MetabolicAtlas/MetabolicAtlas#1106]
**Describe the bug**

Searching for `nucleophagy` in 2D Map Viewer pops up an error window. It normally just shows `No matches` message on the right side. 

**Steps to reproduce**

URL to reproduce the error:
https://metabolicatlas.org/explore/Human-GEM/map-viewer/golgi_apparatus?dim=2d&panel=0&sel=&search=nucleophagy&coords=-4258.84,-29435.89,0.12,21.94,-41.3,-47.11&datatype=None&datasource=None&dataSet=None

**Expected behavior**

- [ ] The error window does not pop up at `No matches`
- [ ] Tests verifying the fix are added

**Screenshots**

![Screenshot 2022-08-23 at 14.43.48.png](https://images.zenhubusercontent.com/58ca67a651aa2c305778a403/b1d1b8b4-625a-4736-93fa-c8c45a41f291)
**Additional context**

Searching of other key words may also trigger the pop up window.

**Comment by nanjiangshu** [comment]
Other key words which active searching errors
```
pi213ffd
```

**Comment by mihai-sysbio** [comment]
This issue is no longer reproducible after the upgrade to Vue 3.
