### ISSUE TITLE
Click selecting an object is very difficult on the 3D Map Viewer for some OS

### ISSUE THREAD

**Issue by nanjiangshu** [MetabolicAtlas/MetabolicAtlas#1108]
**Describe the bug**

For the 3D Map Viewer, click selecting an object is very difficult so as hover showing the gene label. 
This problem is observed on Macbook Pro M1 on all major Web browsers. 

We need to first verify and investigate the range of the problem. If the problem exists only on a specific type of computer with a specific OS version, maybe we just document the problem somewhere e.g. FAQ. 
  
**Steps to reproduce**

**Expected behavior**

- [ ] It should be easy to select an object on the 3D Map Viewer and hover to show the gene label

**Screenshots**

**Additional context**

**Comment by MalinAhlberg** [comment]
Covered by https://github.com/MetabolicAtlas/3d-network-viewer/issues/59
