### ISSUE TITLE
GotEnzymes result table page jumps when doing filtering

### ISSUE THREAD

**Issue by nanjiangshu** [MetabolicAtlas/MetabolicAtlas#1111]
**Describe the bug**

The web page for the GotEnzymes result table jumps when doing filtering, see the attached video recording.
**Steps to reproduce**

**Expected behavior**

- [ ] The web page does not jump when doing filtering 

**Screenshots**

https://images.zenhubusercontent.com/366030821/58c17716-12b8-4bfa-a238-770abaf008e5/gotenzyme.mov

**Additional context**

**Comment by mihai-sysbio** [comment]
In the case when the response would include 0 results, any fix would become irrelevant. Therefore the decision is to not resolve this issue.
