### ISSUE TITLE
Enable progressive keyword filtering (or partial matching) in the GotEnzymes result table

### ISSUE THREAD

**Issue by nanjiangshu** [MetabolicAtlas/MetabolicAtlas#1112]
**Please describe the feature**

As a user, I want filtering by keywords using partial matching instead of whole word matching so that the filtering of the result table is shortened progressively.

**Acceptance Criteria**

- [ ] Keyword filtering of the result table uses partial matching
- [ ] The changes are tested on multiple models and browsers
- [ ] Tests verifying the changes are added
- [ ] The API response is the same as before
- [ ] The changes do not affect the deployment
- [ ] The changes do not reduce the performance

**Additional context**

For example, for the page https://metabolicatlas.org/gotenzymes/ec/2.5.1.19, typing in `100` in the field `Gene` results in an empty table, despite that `100` partially matches many of the gene IDs. In many other data table libraries, such as https://datatables.net/, keyword filtering is progressive and shortens the table until no matches are found.

It might be problematic to implement this for all columns. The `Gene` column might contain too many entries for the partial matching to work with resonable performance.

**Comment by mihai-sysbio** [comment]
The partial matching does not have to be applied to all columns - skipping one (or several?) is fine.

**Comment by inghylt** [comment]
As summarized [here](https://github.com/MetabolicAtlas/MetabolicAtlas/pull/1136#issuecomment-1251060329), this issue will be closed and partial matching will hopefully be implemented as a result of #1056
