### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'short_name')

### ISSUE THREAD

**Issue by perjo** [MetabolicAtlas/MetabolicAtlas#1120]
**Describe the bug**
An error message is shown in the console log. 

**Steps to reproduce**

1. Open developer tools -> console
2. Visit `explore/Human-GEM/gem-browser/metabolite/MAM01637c`

**Expected behavior**

No error message is shown

**Screenshots**

![image](https://user-images.githubusercontent.com/3620387/187371292-b9ace41d-b604-478a-9e08-191c8dc7f1f2.png)

**Additional context**

**Comment by mihai-sysbio** [comment]
Could not be reproduced after the Vue 3 upgrade
