### ISSUE TITLE
duplicated results in Gemsearch 

### ISSUE THREAD

**Issue by nanjiangshu** [MetabolicAtlas/MetabolicAtlas#1124]
**Describe the bug**

Gemsearch shows duplicated results when searching for e.g. `Retinol metabolism`

**Steps to reproduce**

In Gemsearch, select `Human-GEM` and search for the keyword `Retinol metabolism`.  The hit `MAM02834c` is duplicated as shown in the screenshot.

**Expected behavior / Acceptance criteria**

- [ ] search results that match 100% with the model content in the yml in the `data-files` repository
- [ ] The results shown in Gemsearch are unique 
- [ ] Tests verifying the fix are added

**Screenshots**

![Screenshot 2022-09-02 at 22.40.14.png](https://images.zenhubusercontent.com/58ca67a651aa2c305778a403/acc537e8-bbb9-48d7-9030-94b92207e0ad)
**Additional context**

The reason why two hits for `MAM02834c` are shown is because the `mid` of the two hits are different. However, since these two hits show the same information in the frontend and more importantly, they direct to the same metabolite page, only one of them should be shown. 
```
{
  name: 'retinol',
  compartment: 'Cytosol',
  mid: 'retinol',
  id: 'MAM02834c',
  score: 9.824196815490723,
  component: 'metabolites'
},
{
  name: 'retinol',
  compartment: 'Cytosol',
  mid: '11_cis_retinol',
  id: 'MAM02834c',
  score: 6.724960803985596,
  component: 'metabolites'
}, 
```

If the problem is in the source yml, it should then be reported in the corresponding repository.

**Comment by mihai-sysbio** [comment]
Looking for `11-cis-retinol` in [Human-GEM.yml](https://github.com/MetabolicAtlas/data-files/blob/main/integrated-models/Human-GEM/Human-GEM.yml) points to the id `MAM00291c`, so it appears that the error is either in the query or in the parsing of the `data-files`.
