### ISSUE TITLE
Support all overlay data types for custom data, not only those that have data in the db

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#1125]
**Please describe the feature**

As a user, I want to be able to upload custom data for all supported data types, so that I'm not limited by only using data types belonging to the data in the db.

**Acceptance Criteria**

- [ ] Users should be able to pick any supported data type (transcriptomics, metabolomics, fluxomics) when uploading custom overlay data
- [ ] The changes are tested on multiple models and browsers

**Additional context**

Probably makes sense to use `const DATA_TYPES_COMPONENTS` in `MetabolicAtlas/frontend/src/helpers/dataOverlay.js`

**Comment by e0** [comment]
Re-adjusted to a `5` based on work done.
