### ISSUE TITLE
Interaction partners map broken on Linux

### ISSUE THREAD

**Issue by MalinAhlberg** [MetabolicAtlas/MetabolicAtlas#1135]
**Describe the bug**

After updating to vue-3, clicking and dragging nodes on the Interaction Partners map sometimes causes the nodes and parts of the labels to disappear. This seems to happen only on Linux systems.

**Steps to reproduce**

- Visit `explore/Human-GEM/interaction-partners/MAM00507c`
- Try to move the nodes around

**Expected behavior**

- [ ] Clicking and moving nodes on the interaction partners map works on all platforms.

**Screenshots**

This is how http://localhost/explore/Human-GEM/interaction-partners/MAM00507c
looks after having moved some of the nodes
![2022-09-14-141923_742x451_scrot.png](https://images.zenhubusercontent.com/5bd711b6c68d75301f4bd969/3057593b-9734-4bf2-b46d-2d007948ab2e)

**Additional context**

Related to private issue #84 (improving the interaction partners). Might not be a problem after the refactoring.

**Comment by mihai-sysbio** [comment]
In light of the work done in #1144, this problem has been circumvented so this issue is no longer valid.
