### ISSUE TITLE
Redo Interaction Partners

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#1144]
**Please describe the feature**

As a developer, I want to redo the Interaction Partners viewer so that the visualisation is snappy (has good performance) and some of the heavy JS library can be removed.

**Acceptance Criteria**

Based on the comments above, the foreseen upcoming work is then to:
- [x]  Create {nodes: [], links: []} object for IP genes and metabolites data
- [x] Generate 2D graph based on this object by using 3d-network-viewer
- [x] Separate IP landing and details page
- [x] When (left) clicking, show GB and IP. Possibly also an "Expand network" button instead of having that as right click option
- [x] Add expand network functionality (right click or through button next to GB and IP)
- [x] Add overlay functionality (and fix the wonky close button)
- [x] Add functionality to export to PNGhML or GraphML
- [x] Update mouse controls to fit IP
- [x] Add button to toggle labels (probably makes sense to more or less copy MapControls.vue)
- [x] Fix constant size of viewer container
- [x] Remove instances of `cytoscape` from `frontend` (if possible)
- [ ] Add logic similar to `if (!document.getElementById('viewer3d'))`
- [x] Remove the legacy css styling in DetailsPage.vue
- [x] Make sure URL params are updated according to graph and overlay
  - [x] create new issue for going "back" (#1168)
  - [x] update the title of the Interaction Partners when expanding the network
- [x] The map is tilted after clicking zoom-in and zoom-out buttons (Fixed using mouse wheel event)
- [x] Some maps occur at random positions after reloading (or all the time as for `ENSG00000109685`): 
- [x] The shape of the nodes changes after applying the data overlay: open the interaction partners for `ENSG00000255730` switch between overlay for `duodenum` and `endometrim` and watch the shape of the nodes (triangle <-> circle). The behaviour is random.
- [x] turned into new issue: MetabolicAtlas/3d-network-viewer#59
- [x] Show but disable the Highlight Compartment/Subsystem and on hover inform that it will be implemented
- [x] The web page documentation is updated accordingly (replace video with picture)
- [ ] The changes are tested on multiple models and browsers
- [ ] Tests verifying the changes are added
- [ ] The API response is the same as before
- [ ] The changes do not affect the deployment
- [ ] The changes do not reduce the performance

**Additional context**

This issue is created from the summary of MetabolicAtlas/MetabolicAtlas#1130

**Comment by inghylt** [comment]
Added item
- [ ] Separate IP landing and details page

Since that will make the IP code clenaer

**Comment by mihai-sysbio** [comment]
I've edited the original post to separate the nice-to-have's to more clearly separate them as optional.

**Comment by e0** [comment]
> Some maps occur at random positions after reloading (or all the time as for ENSG00000109685)

Regarding this point. I followed the idea @inghylt mentioned on Friday and added a commit now: https://github.com/MetabolicAtlas/MetabolicAtlas/commit/99bce695c67074ff3ecf80be6f0fa666ada9d961. It uses the max and min `x` and `y` positions to calculate a new center for the layout to shift to. I still notice the graph being slightly off-center after reloading sometimes but the problem seems a lot less severe than how it was before. Please let me know if there is any other issues and we can uncheck this todo item again.

**Comment by e0** [comment]
> Mac users cannot click on nodes

Finally some progress on this issue. It seems like the [width of the `subcamera`](https://threejs.org/docs/#api/en/cameras/PerspectiveCamera.setViewOffset) needs to be increased for the object to be picked up. With this change, the "wrong" object can get picked sometimes if there are two in close proximity. I will try to play around a bit more with the numbers but really wanted to share this already.

 Change and effect below. (Tested on an M1 MacBook, where object picking does not work without this change).

<img width="555" alt="image" src="https://user-images.githubusercontent.com/423498/197719730-58ca40ae-ae60-4630-8e39-0081efb7f60b.png">


https://user-images.githubusercontent.com/423498/197720331-feff1874-3543-4d29-99dc-5bbdea420a2e.mp4

**Comment by nanjiangshu** [comment]
> > > Some maps occur at random positions after reloading (or all the time as for ENSG00000109685)
> > 
> > 
> > Regarding this point. I followed the idea @inghylt mentioned on Friday and added a commit now: [99bce69](https://github.com/MetabolicAtlas/MetabolicAtlas/commit/99bce695c67074ff3ecf80be6f0fa666ada9d961). It uses the max and min `x` and `y` positions to calculate a new center for the layout to shift to. I still notice the graph being slightly off-center after reloading sometimes but the problem seems a lot less severe than how it was before. Please let me know if there is any other issues and we can uncheck this todo item again.
> 
> Well done! I think the off-center problem is good enough now.

Hi @e0 @MalinAhlberg @inghylt @mihai-sysbio , when reading the Documentation for the interaction partners, it says `The metabolite or gene of interest is centered on the graph.`. I realized it makes more sense to always place the main node at the center of the container area instead of making the re-centering based on the center of the network. I have created a branch `feat/redo-IP-center-selected-object` to implement this. Now for IDs such as `ENSG00000118058` and `ENSG00000109685`, the component of interest is always placed at the center of the container area, no random position anymore. I think it also makes sense to place the component that is used for expanding network at the center of the area, however, I cannot test this feature since left clicking is so far not working on my computer. Could someone please verify that the implementation works also for IP expand?

**Comment by MalinAhlberg** [comment]
> Hi @e0 @MalinAhlberg @inghylt @mihai-sysbio , when reading the Documentation for the interaction partners, it says `The metabolite or gene of interest is centered on the graph.`. I realized it makes more sense to always place the main node at the center of the container area instead of making the re-centering based on the center of the network. I have created a branch `feat/redo-IP-center-selected-object` to implement this. Now for IDs such as `ENSG00000118058` and `ENSG00000109685`, the component of interest is always placed at the center of the container area, no random position anymore. I think it also makes sense to place the component that is used for expanding network at the center of the area, however, I cannot test this feature since left clicking is so far not working on my computer. Could someone please verify that the implementation works also for IP expand?

Well done! From my testing so far, this behaves really nice! It does not work for expanded networks, though, I can have a look at that.

**Comment by e0** [comment]
@nanjiangshu That's a really good catch fromt the documentation! I tested your branch now and it works well!
