### ISSUE TITLE
refactor the use of citations

### ISSUE THREAD

**Issue by mihai-sysbio** [MetabolicAtlas/MetabolicAtlas#1153]
**Please describe the feature**

As a developer, I want to have a single point of update of the citation information that will be used across the website, so that I don't have to manually maintain multiple ones.

**Acceptance Criteria**

- [ ] continue the work in this branch https://github.com/MetabolicAtlas/MetabolicAtlas/tree/feat/refactor-citations
- [ ] resolve feedback shared here https://github.com/MetabolicAtlas/MetabolicAtlas/commit/11c451f3c32a8b2ca403ed0f27ae95ac6b77423b#comments
- [ ] The changes do not affect the deployment

**Additional context**

This issue started from a review comment https://github.com/MetabolicAtlas/MetabolicAtlas/pull/1151#discussion_r985732924

**Comment by MalinAhlberg** [comment]
It's part of the work to discuss the layout of the publications on the different pages.

**Comment by nanjiangshu** [comment]
I think we can use a unique source, json or something else, for the publication, but the representation in the frontpage or the citation page can be different.
