### ISSUE TITLE
gather user feedback on gotenzymes

### ISSUE THREAD

**Issue by mihai-sysbio** [MetabolicAtlas/MetabolicAtlas#1154]
Go through the HotJar data.

_note: If more time seems to be needed, this can be bumped to a 5. Might make sense to involve the researchers._

**Comment by inghylt** [comment]
@e0 @MalinAhlberg @nanjiangshu I'm thinking that it makes sense to have one of you guys watching some videos as well for one hour or two so it's not only my subjective eyes watching, what do you guys think?

**Comment by MalinAhlberg** [comment]
My findings:

- > Add GotEnzymes to Documentation

    After having watched a bunch of videos, I agree that this should be done. The documentation at `/gotenzymes` is not visible to all users without scrolling.  People repeatedly go the 'Documentation' and scrolls up and down before returning to GotEnzymes.

- > Makes sense to improve filtering (Clicking around at different compounds at random + full text fail when filtering + a lot of jumping around)

    yes!

- Could it be made possible to click the kegg ids in details table? Similarily as for cross references. See for example: https://metabolicatlas.org/gotenzymes/gene/I6J01_13315

- Searching for long strings in the search field: if you click on one of the hits, then want to go back and inspect the other hits, you will have to retype the whole word. Maybe save the last search string in the field, as for quick search? Or even better, to have the search integrated with the quick search. See first marked issue https://insights.hotjar.com/r?site=1356321&recording=15976529374&workspace_id=1124481

- Search by name: It would be nice to be able to find ec 3.2.1.17 by searching for lysozyme (its name) or to find https://metabolicatlas.org/gotenzymes/organism/wbr by the search string Wigglesworthia. https://metabolicatlas.org/gotenzymes/ec/3.2.1.17

- Sorting a column multiple times may lead to gateway timeout.
  For example this https://metabolicatlas.org/api/v2/gotenzymes/enzymes?filters[ec_number]=6.2.1.1&pagination[page]=1&pagination[pageSize]=50&pagination[column]=reaction_id&pagination[isAscending]=false  , eg sorting by reaction many times at https://metabolicatlas.org/gotenzymes/ec/6.2.1.1
  See https://insights.hotjar.com/r?site=1356321&recording=16556846475&workspace_id=1124481

- Some users seem to have a hard time finding their way back to GotEnzymes after having left for another page. Maybe add a picture/link from the home page, as for *GEM Browser*, *Map Viewer* and *Interaction Partners!*?

Unrelated:
- IP: the reaction table get impossible to overview on mobile phone, see screen shot or https://metabolicatlas.org/explore/Human-GEM/interaction-partners/ENSG00000145949
  or the marked issue (at the end of) https://insights.hotjar.com/r?site=1356321&recording=15949104195&workspace_id=1124481.
![2022-11-01-154344_386x765_scrot.png](https://images.zenhubusercontent.com/5bd711b6c68d75301f4bd969/026f8428-3cd5-42c7-af83-5de4e23acdce)

**Comment by feiranl** [comment]
As for the first one, it is empty due to there is not a defined SMILES: `C8H12NO10PR2`, `R` refers to undefined formula. Then we cannot perform the prediction.
For the second one, it would be great to allow users search by name for all types.

**Comment by mihai-sysbio** [comment]
> As for the first one, it is empty due to there is not a defined SMILES: `C8H12NO10PR2`, `R` refers to undefined formula. Then we cannot perform the prediction.

`C02737` is present in line 2185 in `supplementary/compound.txt` - perhaps it got there by accident?

**Comment by feiranl** [comment]
We didn't do filtering for the compounds. All compounds exist in KEGG were kept no matter wether it is  included in the current prediction main file. We were thinking that by doing so, we don't have to update the compound supplementary file for each update.

**Comment by mihai-sysbio** [comment]
> All compounds exist in KEGG were kept no matter wether it is included in the current prediction main file. We were thinking that by doing so, we don't have to update the compound supplementary file for each update.

I see how this is less work, but it's also creating a confusion for some users. It's always a trade-off with these things.

**Comment by MalinAhlberg** [comment]
This issues will be closed, as new issues for all points, except 
> Should a page have empty tables?

have been created. Please open new issues if you see fit.
