### ISSUE TITLE
remove jQuery

### ISSUE THREAD

**Issue by e0** [MetabolicAtlas/MetabolicAtlas#1156]
**Please describe the feature**

As a developer, I want to remove jQuery from the project so that there is a consistent way of manipulating the UI and the web app loads faster.

**Acceptance Criteria**

- [x] Get rid of all instances of `jquery` in `frontend`. Replicate the functionality using Vue or vanilla JavaScript.
- [ ] The changes are tested on multiple models and browsers
- [ ] The API response is the same as before
- [ ] The changes do not affect the deployment
- [ ] The changes do not reduce the performance

**Additional context**

This should probably be started after #1144 since there is a few instances of `jquery` that looks like they could be removed (along with `cytoscape`.

**Comment by PRO-BROS** [comment]
Yep. I am also doing same with my [site](https://prhocoding.com/)

**Comment by mihai-sysbio** [comment]
Re-opening this issue to report on the size reduction of the frontend JS as a result of this improvement.

**Comment by mihai-sysbio** [comment]
Awesome 💫 this reduced the size by about 10%, raw _and_ compressed

**3.2**
```
index.js    1129.36 KiB / gzip: 325.84 KiB
```

**3.3**
```
index.js    1040.14 KiB / gzip: 294.41 KiB
```
