### ISSUE TITLE
Create a presentation regarding on how we deploy

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#1166]
This is to be presented to NBIS but also a way for the team to understand what is going on "under the hood":

_Suggested title:_ From coding locally to fulfilling a client browser request
- running `deploy-stack`
- using Docker context
- how the Docker compose files are set up (2, combined)
- the different containers
- caching in Neo4j, Express.js, and Nginx
- testing the speed of the requests around the globe with some online tool show that for some countries the website is still slow
- Cloudfare: DNS settings, forwarding rules, caching

**Comment by inghylt** [comment]
@mihai-sysbio regarding this comment:

>  testing the speed of the requests around the globe with some online tool show that for some countries the website is still slow

What tools are we referring to there?

**Comment by mihai-sysbio** [comment]
> What tools are we referring to there?

@inghylt I can't remember the specific website, but I used one to see the loading speed of the website from different locations around the world.

**Comment by inghylt** [comment]
https://docs.google.com/presentation/d/1qX0L4Upd12MNQmjglPobxTPzgN32wFJKpe7w3yT3CUA/edit?usp=sharing

@mihai-sysbio @MalinAhlberg @nanjiangshu @e0 Please have a look at the presentation and see if everything looks good. Please make comments in the presentation if you have feedback. @e0 I sent an invitation to you email since you are not part of SciLifeLab

**Comment by e0** [comment]
@inghylt The presentation looks excellent! I think it's a really nice overview of our setup.

**Comment by inghylt** [comment]
Thanks for all the feedback!
