### ISSUE TITLE
Enable going back in IP (url)

### ISSUE THREAD

**Issue by MalinAhlberg** [MetabolicAtlas/MetabolicAtlas#1168]
**Please describe the feature**

As a user, I want the backward-button to work for the IP maps so that I can extend a map and then easily go back to the original one.

**Acceptance Criteria**

- [ ] Going back in browser history after having added extension works
- [ ] Going back in browser history after having added overlay works (?)
- [ ] The changes are tested on multiple models and browsers
- [ ] The changes do not reduce the performance

**Additional context**

Moved out of issue #1144

**Comment by perjo** [comment]
I believe the title should also set to reflect the expansion and data set state, otherwise the history does not give much? 

![Skärmavbild 2023-03-14 kl. 11.04.35.png](https://images.zenhubusercontent.com/626697ae6d06b7eb7ed6729d/07c2f1bf-9991-45cc-86a5-9d04363246f3)

**Comment by mihai-sysbio** [comment]
> I believe the title should also set to reflect the expansion and data set state, otherwise the history does not give much?

That makes a lot of sense - I didn't think about it. Would it be within scope to add it, or should it be a new issue? Perhaps it's not the only place where the browser tab title should be updated.

**Comment by perjo** [comment]
> > I believe the title should also set to reflect the expansion and data set state, otherwise the history does not give much?
> 
> That makes a lot of sense - I didn't think about it. Would it be within scope to add it, or should it be a new issue? Perhaps it's not the only place where the browser tab title should be updated.

Yes, there are probably more places that a more informative page title could be useful. Created #1318 for this.
