### ISSUE TITLE
adding overlay will make hidden labels show

### ISSUE THREAD

**Issue by MalinAhlberg** [MetabolicAtlas/MetabolicAtlas#1169]
**Describe the bug**

Adding overlay to a 3d map (in map viewer or IP), will make gene and gene labels show, even if they are previously hidden.

**Steps to reproduce**

- Visit `/explore/Human-GEM/interaction-partners/ENSG00000135929`
- Hide the gene labels
- Add overlay
- Labels will reappear

**Expected behavior**

- [ ] If hidden, the gene labels should not be shown when adding overlay

**Additional context**

**Comment by inghylt** [comment]
With what we currently have on [main](https://github.com/MetabolicAtlas/MetabolicAtlas/tree/a63814da092ce1a4059f306db07d5b6d84570778), this is no longer a problem!
