### ISSUE TITLE
Label of IP network nodes shown outside of the container

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#1172]
**Describe the bug**

Label of IP network nodes shown outside of the container

**Steps to reproduce**

1. Visit `/explore/Human-GEM/interaction-partners/MAM02040r?expandedIds=&dataTypes=transcriptomics&dataSources=hpaRna.tsv&dataSets=None`
2. Move mouse around outside of the container, e.g. around the reactions table
3. Note that network labels are displayed (if that's not the case, reload the page or zoom until you have nodes "outside" of the container and repeat step 2)

**Expected behavior**

- [ ] No labels are shown outside of the container

**Screenshots**

**Additional context**

**Comment by MalinAhlberg** [comment]
The same thing happen in the map viewer (3d) when having zoomed in on large graphs (eg cytosol) and moving the mouse around on the left sidebar.
