### ISSUE TITLE
Cypher error message shown

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#1173]
**Describe the bug**

Cypher error message shown when faulty input is given to API

**Steps to reproduce**

1.  Visit `/api/v2/#/Miscellaneous/randomComponentInfo`
2. Provide `HumanGem` and `{"silly":true}`
3. Note that `Cypher query is expected to be a non-empty string` is returned

**Expected behavior**

- [ ] for the entire backend, make sure that it's not any text error message returned to the user (Neo4j or otherwise)
- [ ] Tests verifying the fix are added

**Screenshots**

**Additional context**

Created as result of https://github.com/MetabolicAtlas/MetabolicAtlas/pull/1160#pullrequestreview-1145928562

**Comment by e0** [comment]
I started looking into this issue and it seems like what we originally decided may not be ideal. Following are some points that makes me think it's better to either rewrite or skip this issue.

1. There are many endpoints where we are explicitly returning a custom error message (see below). I don't think it is ideal if all of these messages are kept away from the user. I was thinking that we should then only avoid returning text error messages for when we don't throw a custom error, which leads to the next point.
2. Many of the `neo4j` endpoints currently share a `fetchWith` function, which makes it cumbersome to decide when a text error message should be returned.
3. Given that the project is open-source and the user does not have write-access to the DBs, I feel like returning cypher or other types of DB error messages is not a significant problem, if at all.

Overall, I feel like the time required to complete this issue properly is not worthwhile considering the debatable usefulness of it. So my personal recommendation is to close the issue. Please let me know what you think though, especially if you disagree with the usefulness of this issue.

Some instances of custom error messages:
```
./api/src//neo4j/queries/relatedReactions.js:      throw new Error(`Unrecognized node type: ${nodeType}`);
./api/src//neo4j/queries/search/modelSearch.js:    throw new Error(`Invalid model: ${model}`);
./api/src//neo4j/queries/search/modelSearch.js:    throw new Error(`Empty searchTerm!`);
./api/src//neo4j/queries/compare.js:    throw new Error(
./api/src//neo4j/queries/randomComponents.js:    throw new Error('At least 1 component type is needed');
./api/src//endpoints/svgThumbnail.js:      throw new Error(
./api/src//endpoints/svgThumbnail.js:      throw new Error(`Invalid model provided: ${model}.`);
./api/src//endpoints/svgThumbnail.js:      throw new Error(`2D map does not exist for ${svgName} in ${model}.`);
./api/src//endpoints/neo4j.js:      throw new Error('At least 2 and at most 4 models need to be provided.');
./api/src//endpoints/neo4j.js:      throw new Error('At least 1 and at most 2 models need to be provided.');
./api/src//endpoints/dataOverlay.js:      throw new Error(`Invalid model provided: ${model}.`);
./api/src//utils/data-overlay.js:    throw new Error(`Invalid model provided: ${model}.`);
./api/src//utils/data-overlay.js:    throw new Error(`Invalid data type provided: ${dataType}.`);
./api/src//utils/data-overlay.js:    throw new Error(`Invalid filename provided: ${filename}.`);
./api/src//gotEnzymes/organism.js:    throw new Error(`Organism ${value} returned ${organism.length} results.`);
./api/src//gotEnzymes/enzyme.js:    throw new Error(`Can not sort on unknown column ${column}`);
./api/src//gotEnzymes/domain.js:    throw new Error(`Domain ${value} returned ${domain.length} results.`);
./api/src//gotEnzymes/ec.js:    throw new Error(`EC ${value} returned ${ecs.length} results.`);
./api/src//gotEnzymes/gene.js:    throw new Error(`Gene ${value} returned ${genes.length} results.`);
```

**Comment by inghylt** [comment]
Nice summary! I think it makes sense. One idea though could be to improve the filtering here https://github.com/MetabolicAtlas/MetabolicAtlas/blob/8f7cfef072f335ad81852302aaa69021346c6b33/api/src/neo4j/queries/randomComponents.js#L16 to make sure that the case that this issue is actually reported for is fixed, I think that should be easy. But I'm fine with closing the issue if that's not something we would like to prioritize.

**Comment by MalinAhlberg** [comment]
> How about we rewrite this issue to be specifically about adding an input validator for the entire backend?

Makes sense to me!

**Comment by nanjiangshu** [comment]
I would be nice to create an input validator for the entire backend, but I'm not quite sure if we should collect all input validator at one place or spread in dedicated backend scripts. Both has advantages and disadvantages. 
Just for this issue, I agree we can close it.

**Comment by nanjiangshu** [comment]
This issue will be supplemented by #1208
