### ISSUE TITLE
Labels are offset after selecting a node for Interaction Partners

### ISSUE THREAD

**Issue by nanjiangshu** [MetabolicAtlas/MetabolicAtlas#1176]
**Describe the bug**

The labels are offset when click selecting a node for Interaction Partners

**Steps to reproduce**

1. Open the IP for e.g. `ENSG00000144290`
2. Select any node
3. The labels will be offset 

**Expected behavior**

- [ ] Labels will not be offset when selecting a node 

**Screenshots**

#### Before selecting 

![Screenshot 2022-10-27 at 10.38.25.png](https://images.zenhubusercontent.com/58ca67a651aa2c305778a403/8bcc5122-b1a6-4799-b53d-d4fa567f1005)
####![Screenshot 2022-10-27 at 10.38.43.png](https://images.zenhubusercontent.com/58ca67a651aa2c305778a403/1dca3be1-da4a-45fb-92bf-b648a30e6fc0) After selecting

**Additional context**

After expanding the network, labels will not be offset when selecting a node

**Comment by MalinAhlberg** [comment]
Not closed by #12204. I will reopen it.
