### ISSUE TITLE
Different IP networks shown in old and new versions

### ISSUE THREAD

**Issue by MalinAhlberg** [MetabolicAtlas/MetabolicAtlas#1189]
**Describe the bug**

The current/old implementation of IP shows different results than the new one.

**Steps to reproduce**

Compare `explore/Human-GEM/interaction-partners/ENSG00000145949` on the prod server to the new IP version.
https://metabolicatlas.org/explore/Human-GEM/interaction-partners/ENSG00000145949 vs http://localhost/explore/Human-GEM/interaction-partners/ENSG00000145949

**Expected behavior**

- [ ] Networks should always be the same (have the same number of nodes and edges) in the two versions

**Screenshots**

![2022-11-01-155542_805x792_scrot.png](https://images.zenhubusercontent.com/5bd711b6c68d75301f4bd969/3a57aa60-07d4-4f5c-91b2-a7b817d0f34e)![2022-11-01-155611_855x647_scrot.png](https://images.zenhubusercontent.com/5bd711b6c68d75301f4bd969/6c7d7fde-b906-4e6e-ae94-c48b515c48e4)

**Additional context**

**Comment by mihai-sysbio** [comment]
This is caused by the update of `Human-GEM` - [2 reactions have been removed](MAR09579) which make the IP network much simpler in the new setup. This is not an issue caused by the IP redo.
