### ISSUE TITLE
Sorting a gotenzymes column multiple times may lead to gateway timeout

### ISSUE THREAD

**Issue by MalinAhlberg** [MetabolicAtlas/MetabolicAtlas#1197]
**Describe the bug**

Clicking several times on the sorting buttons of a column may lead to a gateway timeout (noticed on the production server). The user will see an error message popping up.

**Steps to reproduce**

- This api call `api/v2/gotenzymes/enzymes?filters[ec_number]=6.2.1.1&pagination[page]=1&pagination[pageSize]=50&pagination[column]=reaction_id&pagination[isAscending]=false` may trigger the problem, eg sorting by reaction many times at `/gotenzymes/ec/6.2.1.1`

**Expected behavior**

- [ ] Clicking the sorting arrows several times will not lead to error messages

**Additional context**

Created from #1154.

**Comment by mihai-sysbio** [comment]
This should be re-tested, since it was reported on the `3.0` that had the old server. Since `3.1` we are on a new server with more CPU and RAM.

**Comment by e0** [comment]
Can confirm that this also breaks on the new production server. I think it might be related to [this PR](https://github.com/MetabolicAtlas/MetabolicAtlas/pull/1138) but I have not verified.

**Comment by nanjiangshu** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MetAtlas-Roadmap-60d96b68da0fb10019d26deb/issues/MetabolicAtlas/MetabolicAtlas/1197?planning-poker) with Zenhub @e0 @inghylt @MalinAhlberg

**Comment by MalinAhlberg** [comment]
> @nanjiangshu @e0 @MalinAhlberg can any of you guys recreate this on prod now? I can't, which I expected given removal of the CPU settings

I could! After a lot of trying, though...
This `api/v2/gotenzymes/enzymes?filters[ec_number]=7.1.1.6&pagination[page]=1&pagination[pageSize]=50&pagination[column]=compound&pagination[isAscending]=true` was the call that crashed.
I also had to wait for almost a minute sometimes. Not sure if / how it could be fixed though. And since we're also working on #1241,  maybe this isn't so severe.

**Comment by nanjiangshu** [comment]
I could not reproduce time out by just sorting the reaction column, but by typing in text (filtering) for the reaction column multiple times, the page hangs, the spinning circle has been running for more than 10 minutes.

**Comment by e0** [comment]
I tried some different pages and combinations of filtering and couldn't trigger it a single time. It seems like the problem is at least a lot less severe compared to before so I'm ok with lowering the priority on this issue.

**Comment by inghylt** [comment]
@MalinAhlberg @nanjiangshu @e0 

Seems like no one can reproduce the error with sorting the frontend. https://github.com/MetabolicAtlas/MetabolicAtlas/issues/1197#issuecomment-1343967423  is not reproducible either, so it's likely that this problem can only be triggered if the server is heavily loaded.

`api/v2/gotenzymes/enzymes?filters[ec_number]=7.1.1.6&pagination[page]=1&pagination[pageSize]=50&pagination[column]=compound&pagination[isAscending]=true` does trigger a 504 in prod, not on localhost. I tried looking at `/api/src/gotEnzymes/enzyme.js` to see if I could speed things up but I can't come up with something.

Thus, I conclude that the way forward is either to increase the timeout limit (on localhost it takes ~43 s so likely somewhere in that ballpark), or to just let `api/v2/gotenzymes/enzymes?filters[ec_number]=7.1.1.6&pagination[page]=1&pagination[pageSize]=50&pagination[column]=compound&pagination[isAscending]=true` return 504. Temporary errors in the frontend should now be handled by #1241

Please have a look yourselves if you are able to speed something up and comment what you think is the best way moving forward

**Comment by e0** [comment]
I tested this more now and can trigger it more frequently for sorting by `compound` now. I suspect it's because we don't have enough RAM to fit all of the index so that it does a full table scan for some indexes. I think it's fine to increase the timeout for now.

<img width="475" alt="image" src="https://user-images.githubusercontent.com/423498/207049382-af8d2969-44b4-4774-820d-54570e65c717.png">

**Comment by inghylt** [comment]
@e0 Should we create a new issue to explore whether we need to allocate more RAM?

**Comment by e0** [comment]
Ok I got some unexpected and wild findings that I do not understand but seems to solve the problem. Inspired by: https://stackoverflow.com/a/66337537

So it turns out that this takes about `13s` on my machine:

```sql
select "gene","organism","domain","reaction_id","ec_number","compound","kcat_values" from enzymes
where true and array['2.5.1.19'] <@ string_to_array(ec_number, ';')
order by "compound" asc
limit 50 offset 0;
```

where as this takes about `40ms`:

```sql
select "gene","organism","domain","reaction_id","ec_number","compound","kcat_values" from enzymes
where true and array['2.5.1.19'] <@ string_to_array(ec_number, ';')
order by "compound" asc
limit 2000 offset 0;
```
The only difference here is increasing the limit from `50` to `2000`. 🤨

Anyways, this seems to work, including when combined with offset and filtering etc. So I will try to add a PR to address this.
