### ISSUE TITLE
Reactions table not useful on mobile devices

### ISSUE THREAD

**Issue by MalinAhlberg** [MetabolicAtlas/MetabolicAtlas#1199]
**Describe the bug**

Some reaction tables are hard to read / overview on a mobile phone, the user will just scroll through what looks like an empty table.

**Steps to reproduce**

- Visit eg `/explore/Human-GEM/interaction-partners/ENSG00000122687` from a mobile device / with a narrow window.

**Expected behavior**

- [ ] Tables look good on mobile devices

**Acceptance criteria**
- [ ] Check other tables as well in the Gem Browser.
 

**Screenshots**

![2022-11-01-154344_386x765_scrot.png](https://images.zenhubusercontent.com/5bd711b6c68d75301f4bd969/f22b874e-93a2-41b0-b7ff-db694e13236f)

**Additional context**

Created from #1154.
**Note**: the original example for this (ENSG00000145949) is not useful anymore as the data models have been updated since. It created a much, much longer section of nothingness on the screen that the now provided example.

**Comment by mihai-sysbio** [comment]
We might have to implement our own styling for tables on mobile devices, like Buefy is doing - which is a reason for having the research issue https://github.com/MetabolicAtlas/private-issues/issues/61 .

**Comment by e0** [comment]
As mentioned [here](https://github.com/MetabolicAtlas/private-issues/issues/61#issuecomment-1305514547), Buefy does not support Vue3.

It should be pretty simple to add similar styling as in Buefy's table. For example: https://codepen.io/AllThingsSmitty/pen/MyqmdM

**Comment by e0** [comment]
Another potential solution is to limit the number of initial items shown in mobile devices. Similar to how we do in the gem browser pages.

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/423498/202135249-284a9109-7633-44a7-bf10-a206c33e71a0.png">

**Comment by mihai-sysbio** [comment]
> Another potential solution is to limit the number of initial items shown in mobile devices. Similar to how we do in the gem browser pages.

The way I imagine this, expanding the rows would still eventually end up creating the same visual issue in the original screenshot. Perhaps you're thinking of changing the table headers - instead of horizontal as they are now in the Reaction table, the GEM Browser pages start with a vertical header in dark green.

**Comment by e0** [comment]
> > Another potential solution is to limit the number of initial items shown in mobile devices. Similar to how we do in the gem browser pages.
> 
> The way I imagine this, expanding the rows would still eventually end up creating the same visual issue in the original screenshot. Perhaps you're thinking of changing the table headers - instead of horizontal as they are now in the Reaction table, the GEM Browser pages start with a vertical header in dark green.

The hypothesis was that having less items per table cell would reduce the amount of whitespace. It is something that we would need to try out. Changing of table headers is not included here but it is included in the [comment before](https://github.com/MetabolicAtlas/MetabolicAtlas/issues/1199#issuecomment-1305519986).
