### ISSUE TITLE
Knowledge sharing to new team

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#1203]
**Please describe the feature**

As a new developer, I want to have have all the knowledge needed about how to run the software and access information so that I can work without hiccups.

**Acceptance Criteria**

- [x] Store link to onedrive for people outside of Chalmers (and inform what you can find and put there?)
- [x] Store link to the wiki
- [x] Information about how ZenHub
- [x] Invite all Aspeboda members to Bitwarden
- [x] Make sure that the new/correct production server is specified in the `Deployment via Docker` docs.
- [x] Add documentation regarding model update
- [x] Add documentation regarding 3d-viewer
- [x] Add documentation that when you make changes to overlay/network make sure to check map viewer and IP
- [x] Add documentation about language recommendations
- [x] Assign Aspeboda to MetAtlas calendar
- [x] ~Make sure Aspeboda have access to [Hotjar](https://insights.hotjar.com/sites/1356321/playbacks/list)~ done via Bitwarden
- [x] Add documentation with a brief introduction to each core tech (Vue, neo4j etc) and relevant source code files for each of the tech
- [x] Pin this issue in the knowledge transfer channel
- [x] Remove old branches from the repo
- [x] Assign this issue to Aspeboda team
- [x] Make sure everyone from Aspebodaklungan can deploy to the `dev` server (with the new changes in `proj.sh` #1295 )

#### Summary of todo for Mihail
- [x] Invite all Aspeboda members to Bitwarden (Jonas is the admin  of the org `Metbolic Atlas` now)
- [x] Enable that giving access to GitHub etc. is not solely dependent on him (Jonas is probably suitable candidate)
- [x] Add all relevant developers to GitHub Metabolic Atlas org
- [x] Invite all relevant developers to OneDrive
- [x] Show Miro
#### General todo
- [ ] ~Update MetAtlas About section and Contribute documentation to reflect the team changes~ moved to #1291 

**Additional context**

**Comment by inghylt** [comment]
https://docs.google.com/document/d/1gJ-sK6Cy3xHQolDxBIzxaPYFA1SDbJjG_DXr2FR3DMM/edit

Document for first meeting with Aspebodaklungan

**Comment by nanjiangshu** [comment]
Document for how to update models: https://github.com/MetabolicAtlas/data-files/blob/main/doc/HOW-TO-UPDATE-MODELS.md

**Comment by nanjiangshu** [comment]
Hi @mihai-sysbio , hope you are having a great vacation and sorry to disturb you,  we need you help to grant access of repos and other data to Aspeboda members. They are listed in the section `Summary of todo for Mihail` of the issue description. Except for the OneDrive, you can probably assign some of us as the admin and then we can do the rest of the work.

**Comment by mihai-sysbio** [comment]
@nanjiangshu thanks for the ping, see the follow-up on Slack

**Comment by mihai-sysbio** [comment]
Only two things left from the original list:
- [ ] Assign this issue to Aspeboda team
- [ ] Make sure everyone from Aspebodaklungan can deploy to the `dev` server (with the new changes in `proj.sh` #1295 )
