### ISSUE TITLE
IP map grows when adding more overlay cards

### ISSUE THREAD

**Issue by MalinAhlberg** [MetabolicAtlas/MetabolicAtlas#1207]
**Describe the bug**

When looking at a interaction partners map, and adding a second overlay card, the size of the map will grow, which looks confusing.

**Steps to reproduce**

- Visit eg https://metabolicatlas.org/explore/Human-GEM/interaction-partners/MAM01628c?expandedIds=&dataTypes=gene&dataSources=hpaRna.tsv&dataSets=B-cells
- Upload data for metabolomics
- Click `Add overlay`
- The map will expand vertically, giving the impression that the graph zooms in.

**Expected behavior**

**Acceptance criteria**
- [ ] Look good in Mobile mode

**Comment by nanjiangshu** [comment]
Suggestions:

1. set a maximum height 
2. use constant height

**Comment by nanjiangshu** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MetAtlas-Roadmap-60d96b68da0fb10019d26deb/issues/MetabolicAtlas/MetabolicAtlas/1207?planning-poker) with Zenhub @e0 @inghylt @MalinAhlberg
