### ISSUE TITLE
Improve memory configuration of neo4j to improve speed

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#1209]
**Please describe the feature**

As a user, I want to know if we should update the neo4j configuration so that I know if we are able to increase the speed with minor changes.

Related reaction query is one of the endpoints that could be improved:
https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02040r 

**Acceptance Criteria**

- [ ] Follow the recommended documentation for the configuration of neo4j even if it doesn't change the performance
- [ ] Explore whether we should set same value for `dbms.memory.heap.initial_size` and `dbms.memory.heap.max_size` as recommended [here](https://neo4j.com/docs/operations-manual/current/performance/memory-configuration/)
- [ ] Explore whether we should specify value for `dbms.memory.pagecache.size` as recommended [here](https://neo4j.com/docs/operations-manual/current/performance/memory-configuration/#memory-configuration-considerations)
- [ ] Document the results (before vs after performance)
- [ ] Implement if we see fit

**Additional context**

**Comment by mihai-sysbio** [comment]
I've re-opened this issue only to connect it to the PR, and will close it thereafter.
