### ISSUE TITLE
dev server containers could crash

### ISSUE THREAD

**Issue by e0** [MetabolicAtlas/MetabolicAtlas#1210]
**Describe the bug**

Recently, docker containers in the dev server seem to crash now and then.

**Steps to reproduce**

It's a bit unclear the exact scenario that causes this. A suspicion is that it was introduced in [this PR](https://github.com/MetabolicAtlas/MetabolicAtlas/pull/1182). Since this PR, the resource allocation for the dev server exceed what is available. Based on docker docs [here](https://docs.docker.com/compose/compose-file/compose-file-v3/#out-of-memory-exceptions-oome) and [here](https://docs.docker.com/config/containers/resource_constraints/#understand-the-risks-of-running-out-of-memory), it seems that a docker container that consumes more memory than allowed by the machine it could get killed.

**Expected behavior**

- [ ] The dev server should not crash due to over allocating system resources
- [ ] Tests verifying the fix are added

**Additional context**

**Comment by mihai-sysbio** [comment]
We do want to have equally powerful `dev` and `prod` instances in order to get a real feeling for how the changes we are doing will behave in the real world. So, my approach would be to have a new VM set up.

**Comment by e0** [comment]
> We do want to have equally powerful `dev` and `prod` instances in order to get a real feeling for how the changes we are doing will behave in the real world. So, my approach would be to have a new VM set up.

How soon can this be done?

As @nanjiangshu mentioned in Slack, this could be done using environment variables and shouldn't take more than a few minutes to fix.

**Comment by mihai-sysbio** [comment]
> dev server seem to crash now and then.

> How soon can this be done?

It generally takes a couple of days to have a new machine up and running after placing the order. At the same time I don't see a problem with containers shutting down randomly on the `dev` server for the coming months.

**Comment by nanjiangshu** [comment]
The problem is resolved after we have upgrade the VM for dev and prod server
