### ISSUE TITLE
Remove duplicate redirect rules

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#1214]
**Please describe the feature**

As a developer, I want to have a single source of configuration so that it is clear where a setting takes places.

**Acceptance Criteria**

- [ ] Remove duplicate redirect rules from Cloudflare

**Additional context**

See [this thread](https://nbisweden.slack.com/archives/C01D13EKUV7/p1667990396448049?thread_ts=1667917126.009349&cid=C01D13EKUV7) for more background information

We have redirect rules that serves that same purpose in both Cloudflare and [router.js](https://github.com/MetabolicAtlas/MetabolicAtlas/blob/397362507f2106b28416c919d45e41fcc32d864b/frontend/src/router.js#L98). Cloudflare has limited amount of rules we can configure, thus it makes more sense to handle it in the frontend

**Comment by inghylt** [comment]
![image.png](https://images.zenhubusercontent.com/5fc0f648ba2981921764866b/3e3e6e9c-348d-4ab5-a8b3-f7609cea23e7)

The duplicate redirect rules are disabled as seen in the screenshot. The disabling took place yesterday so it should have taken effect by now.

Please try out for example

- https://metabolicatlas.org/explore/gem-browser/human1/metabolite/MAM01345c
- https://metabolicatlas.org/explore/map-viewer/human1/alanine_aspartate_and_glutamate_metabolism

And other urls where redirect should take place

I will remove the rules once confirmed that everything works as intended

@MalinAhlberg @mihai-sysbio @nanjiangshu @e0

**Comment by nanjiangshu** [comment]
I think it makes sense to disable the Page rules in Cloudfare and keep the redirect rules in the router.js. I tested various pages for human1 and all worked well.

**Comment by e0** [comment]
Seems to work well!
