### ISSUE TITLE
Replace old dev server with new one where memory and cpu match prod

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#1216]
**Please describe the feature**

As a developer, I want dev and prod to be equal so that I can try out things at dev and trust that it behaves the same way it would in prod.

**Acceptance Criteria**

- [x] order new `dev` server matching `prod`
- [x] remove old `dev` and `prod`
- [x] update uptimerobot
- [x] configure new `dev`: install Docker, add user
- [x] update cloudfare config
- [x] update internal documentation at https://github.com/MetabolicAtlas/docs/wiki/VM-overview

**Comment by nanjiangshu** [comment]
The new dev server is setup.
