### ISSUE TITLE
Update citation information of GotEnzymes

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#1228]
**Please describe the feature**

**Acceptance Criteria**

- [ ] https://metabolicatlas.org/gotenzymes says "Manuscript under consideration", while at https://metabolicatlas.org/about/platform#citation we show how to cite the published article

**Additional context**

**Comment by mihai-sysbio** [comment]
Very good, please try to include this in the next deployment!
