### ISSUE TITLE
Obtain analytical data for the NBIS yearly report

### ISSUE THREAD

**Issue by nanjiangshu** [MetabolicAtlas/MetabolicAtlas#1229]
**Please describe the feature**

As a developer, I want to obtain analytical data for the usage of MetAtlas so that I can present at the NBIS yearly report.

**Acceptance Criteria**

- [ ] Number of users and comparison to the previous year
- [ ] Number of countries
- [ ] Number of total hours ?

**Additional context**

**Comment by mihai-sysbio** [comment]
Please also store a copy of this report on OneDrive.

**Comment by nanjiangshu** [comment]
The data is already stated in NBIS SIT 2022 document
