### ISSUE TITLE
Close and remove redundant branches

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#1264]
**Please describe the feature**

As a new developer, I don't want legacy branches do still be active so I am not confused by what to keep or not

**Acceptance Criteria**

- [ ] Close and remove redundant branches

**Additional context**

**Comment by inghylt** [comment]
Suggestion: We remove all branches that are not connected to a current issue/PR except https://github.com/MetabolicAtlas/MetabolicAtlas/tree/feat/gems-timeline-style.

**Comment by inghylt** [comment]
@e0 I guess we can close this now?

**Comment by e0** [comment]
I think so. Thanks for organizing this!
