### ISSUE TITLE
Windows users can't upload data overlay files

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#1286]
**Describe the bug**

A user reported via contact@metabolicatlas.org that she could not upload custom data overlay files. This seems to be a problem with Windows operating systems as it can not be reproduced on neither Mac or Linux.

**Steps to reproduce**

1. Use a computer with Windows operating system
2. Try upload valid custom data in the data overlay in the Map Viewer

**Expected behavior**

- [ ] Users can upload valid custom tsv files for the data overlay no matter which operating system.

**Screenshots**

<img width="600" alt="Atlas error message" src="https://user-images.githubusercontent.com/32480198/209304329-488e6660-d1b7-4ba1-9dbb-fe0cf2d79659.PNG">

**Additional context**

**Comment by mihai-sysbio** [comment]
@mihai-sysbio to look if there is more info for reproducibility.
Also, it's worth trying out this in Windows to see if the error can be produced.

**Comment by mihai-sysbio** [comment]
It seems this is not specific to a file - even a file that is known to function in Linux/Mac did not work when uploading from Windows.
