### ISSUE TITLE
Several observed bugs in `proj.sh` relating to code injection, code duplication, the use of unquoted variables, possible interfearence with external code via environment variables, readability, etc.

### ISSUE THREAD

**Issue by kusalananda** [MetabolicAtlas/MetabolicAtlas#1295]
**Describe the bug**

The `proj.sh` dot-script is supposed to be sourced (either via `source proj.sh` or `. ./proj.sh`) to install several convenient shell functions into the current shell session, along with numerous variables used by the project. These are shell functions that a developer is expected to use several times during an ordinary day of working with this project.  

I have collected several issues together with suggestions for solving most of these:

- The dot-script pollutes the current shell environment with unnecessary variables (some that contain passwords). It also modifies the `PATH` variable by adding `/usr/local/bin` to the end every time the script is sourced. This is an issue since developers may need to move between different projects and may inadvertently affect the running of unrelated code by the presence of certain variables or shell functions.  Depending on the shell's configuration, it may also expose passwords to any software started from the developer's shell. 
	- It would be better if sourcing the script only added the necessary functions to the environment without modifying existing environment variables or adding new ones.  
	- The environment could be made local by running the functions in sub-shells. Each function that needs it could initialise its local environment by calling a common `_setup-envinoment` function. This way, sourcing the `proj.sh` script *only* adds the shell functions defined within the script and does not pollute the environment with passwords etc.  
	- A `deactivate` function could be implemented that removes the installed shell functions from the environment. This function would not need to reset any shell or environment variables as none were changed.  
- Several variables are unquoted in the code. This makes it impossible to e.g. work with directories with spaces in their paths or passwords containing spaces, tabs, filename globbing characters, etc. This affects some uses of `$CHOSEN_ENV`, `$DATA_GENERATOR_PATH`, `$DATA_FILES_PATH`, `$NEO4J_USERNAME`, `$NEO4J_PASSWORD`, and a few uses of `$@`.  
	- Quoting these variables is possible.  
- There are two instances of code injection. Neither of these is (probably) a serious matter, but both could easily result in errors if a password happened to include quotes. Code injections should be fixed as a matter of principle, as assessing the real security impact is difficult.  
	- When `cypher-shell` is called within an in-line `bash -c` script, executed in the `neo4j` container, the two option-arguments `$NEO4J_USERNAME` and `$NEO4J_PASSWORD` are injected by the parent shell into the in-line script (their use is also unquoted which prompts the shell to split their values on whitespace and to apply filename globbing on the result).  
		- Either pass these two values as arguments to the `bash -c` script or, better yet, do not wrap the `cypher-shell` invocation in a `bash -c` script. In either case, the two arguments should be quoted.  
	- When `psql` is executed inside the `pq` container to change a password, `$POSTGRES_PASSWORD` is injected by the parent shell into the SQL statement that performs the change.  
		- We may parametrise the `ALTER USER` statement to use a variable set on the `psql` command line using `-v` or `--variable`. The `psql` utility would take care of sanitising the values of such variables. Note that the SQL statement has to be passed to `psql` via the command's standard input stream, as the statement given by `--command` or `-c` is not processed for parameter placeholders.  
- The command `docker compose` is being called with exactly the same arguments in a number of places.  
	- This may be extracted into a helper function, `_docker-compose`, that does the `docker compose` call with the static arguments, with the given variable arguments added to the end of the argument list. This not only gets rid of code duplication but also helps with readability, as it results in code with much shorter lines.  
- Regarding code reuse, all instances of `docker exec` and `docker compose exec` could look virtually the same.  
	- Reuse the `ma-exec` function for this.  
- The command `docker` may not have a `compose` sub-command on some systems where a `docker-compose-cli` package (or similar) is not available or has not been installed.  
	- Use `docker-compose` instead of `docker compose`, for the developer's convenience, and set the `DOCKER_BULDKIT` to `1` for the command to use [the improved BuildKit backend](https://docs.docker.com/build/buildkit/), just like `docker compose` would do by default.  
- There are some instances of the standard utility `cp` being called with an absolute path. This is inelegant.  
	- If there is an issue on some platform, for some developer, causing the wrong `cp` command is being used, then `/bin` should be added *first* in the `$PATH` variable and `command cp` should be used rather than just `cp`.  This ensures that the external command `cp` is called rather than a shell function or alias and that the shell would first search for this command in `/bin`.  
- There is a comment about a `-q` option in the `generate-data` function:  
  > enable flag "-q" to force overwritting existing data files  

    
  This comment is either out of place, unneeded, or should refer to the `--reset-db` option rather than `-q`.  
	- Correcting this comment would probably be the best approach.  
- There are some instances of using a mix of long and short options with `docker compose`, which reduces the code's readability and may cause confusion.  
	- To avoid confusion, spell `-d` as `--detach`, `-v` as `--volumes`, and `-f` as `--follow` in the relevant calls. Also, use long options with other non-standard commands where it serves to document the code.  
- Two `docker compose` calls (in `deploy-stack` and in `start-stack`) have no associated error handling, which means that if they fail, the rest of the code in the function would likely also fail. Likewise, the call to `generate-data` in `deploy-stack` and `import-db` may also fail.  
	- Selective use of `set -e` would allow us to bail out of functions at the first failing command. Note that all functions do not need this (typically only functions with multiple steps). Also, note that the effect of this shell option would be localised if each function executed within its own sub-shell as discussed at the start.  
- [Docker compose environment files](https://docs.docker.com/compose/environment-variables/env-file/) are not generally shell scripts. The shell code disregards this and sources the environment file.  
	- Using two separate environment files would not be practical, even though creating the Docker environment file from a shell script would be trivial.  
	- Since quoting works very differently in the two file formats, the passwords in the environment file will need to be picked carefully.
- Shell function names should not contain dashes.
  - We may have to assume that the developer uses a shell that allows this, to remain backward compatible.

**Comment by mihai-sysbio** [comment]
> * f there is an issue on some platform, for some developer, causing the wrong `cp` command is being used

This was exactly the problem - could you check the history so that the new solution resolves the original (and now inelegantly fixed) issue?

**Comment by mihai-sysbio** [comment]
Thank you for the comprehensive write-up @kusalananda. Conceptually, as a PO, I am tempted to split these in 2 bins (urgent/now and later), but it might be more efficient to do everything in one go. Please go ahead as you best see fit.

**Comment by e0** [comment]
Hi @kusalananda! (This is Shan btw.) This looks like an amazing audit and set of improvements for the `proj.sh` file. You brought up a lot of security issues that we overlooked before. The updated `proj.sh` file also looks so much cleaner and more professional.

I just wanted to mention one thing regarding the docker compose versions. It seems like [V1 won't be supported from the end of June](https://docs.docker.com/compose/compose-v2/). As a note, we also had some difficulties before finding the right version to work for different developers between Linux and macOS machines. I think I remember having certain issues with a V1 minor version on macOS when that worked for Linux users.

Overall, I can see that you seem to have a much better grasp of bash and docker than me so I'm confident in whatever decision you make here. Just wanted to mention the above in case you hadn't seen it.

Once again, it's really exciting and reassuring to see your attention to detail and I can see that the project is in good hands. Even though I'm not actively working on the project now, it's still an OS project that I care a lot about so please feel free to at me on any issues if you want to have another opinion.

**Comment by kusalananda** [comment]
> I just wanted to mention one thing regarding the docker compose versions. It seems like [V1 won't be supported from the end of June](https://docs.docker.com/compose/compose-v2/). As a note, we also had some difficulties before finding the right version to work for different developers between Linux and macOS machines. I think I remember having certain issues with a V1 minor version on macOS when that worked for Linux users.

Thanks for your input @e0 ! After some additional input from @mihai-sysbio, I will address a few other pending issues and comments from the project's past related to external dependencies like these.  I can make these functions pick up `docker compose` if `docker-compose` is not available, for example, as either command would be able to be used interchangeably in this project. This is fairly easy to do.

**Comment by kusalananda** [comment]
> > * f there is an issue on some platform, for some developer, causing the wrong `cp` command is being used
> 
> This was exactly the problem - could you check the history so that the new solution resolves the original (and now inelegantly fixed) issue?

Looking into the past I can see that the reason for using a full path is to avoid using an alias. I will propose a change that uses `rsync` instead of `cp`.  This would have the additional benefit of being ever so slightly faster.

**Comment by kusalananda** [comment]
> > Regarding code reuse, all instances of `docker exec` and `docker compose exec` could look virtually the same.
> > ```
> > * Reuse the `ma-exec` function for this.
> > ```
> 
> It should be checked that the command arguments work in the same way. Also, I think there is (was?) a `docker-compose` executable.

They (`docker exec` and `docker-compose exec`, or `docker compose exec`) don't work the same way, but it is easy to fix. I'm also continuously testing this to make sure that functions are still working as they have always been.
