### ISSUE TITLE
API is open to Cypher injection

### ISSUE THREAD

**Issue by perjo** [MetabolicAtlas/MetabolicAtlas#1317]
**Describe the bug**

The API is open to Cypher injection. 

**Steps to reproduce**

**Simple example**: Enter `HumanGem)-[]-(x`  as model in the [compartment API](http://localhost/api/v2/#/Compartments/compartmentInfo) (or visit http://localhost/api/v2/compartments/golgi_apparatus?model=HumanGem)-%5B%5D-(x&full=true
 directly. Now we've not only inserted data into the Cypher query, we have also changed the query that is executed. 

**More advanced example**: Enter `HumanGem)-[]-(r)-[]-(s)-[]-(ss)-[]-(cm)-[]-(g)-[]-(e)-[]-(csvg) // ` as model in the [compartment API](http://localhost/api/v2/#/Compartments/compartmentInfo)  (or visit http://localhost/api/v2/compartments/golgi_apparatus?model=HumanGem)-%5B%5D-(r)-%5B%5D-(s)-%5B%5D-(ss)-%5B%5D-(cm)-%5B%5D-(g)-%5B%5D-(e)-%5B%5D-(csvg)%20%2F%2F&full=true
 directly). In this example we inject code and comment out other parts of the query. This request times out in my environment but that is not really relevant. 

These examples could of course be tested with the production API as well. A simple sign of that is that if one requests https://metabolicatlas.org/api/v2/compartments/golgi_apparatus?model=%22 we get an error message directly from Neo4J not being able to parse the query. 

It is not only the compartments endpoint that is affected, it seems most of them except the GotEnzymes ones are. 

**Expected behavior**

The examples above should return error codes 400 or 404. 

**Disclaimer**: This issue is public after team and project management discussions since cypher injection issue is already disclosed in for example https://github.com/MetabolicAtlas/MetabolicAtlas/pull/557

**Comment by perjo** [comment]
Regarding how to fix this. I can think of two principal ways:

**Use parameterized queries**
This should be the preferred solution but it would require quite a bit of re-writing especially since the queries are wrapped in apoc calls.

**Sanitize parameters**
I guess we can restrict parameters contain just alphanumeric characters plus dot and underscore. This could be a quicker and simpler fix.

**Comment by mihai-sysbio** [comment]
Here's what Neo4j suggests: https://neo4j.com/developer/kb/protecting-against-cypher-injection/#_query_sanitization
