### ISSUE TITLE
Prevent opening anchor tag links in new window

### ISSUE THREAD

**Issue by KattisLej** [MetabolicAtlas/MetabolicAtlas#1322]
**Describe the bug**
As a user I don't want the application to open a new tab each time I click on a link.

When using anchor links the new page opens in a new window.

- [ ] use Shan’s way of dealing with `<a> tags and click.prevent=”e =>f(e)”` on the tags in the GEM Browser

Code example:
https://github.com/MetabolicAtlas/MetabolicAtlas/blob/cafee5f4189b09171d1ef4ecd343[…]43ac8/frontend/src/components/explorer/gemBrowser/GemSearch.vue

Problem example:
https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR09296 

**Expected behavior**
- [ ] A  link should not open a new window
- [ ] Tests verifying the fix are added

**Additional context**

**Comment by pdmnyberg** [comment]
As far as I understand anchor links that open new windows are specified with `target="_blank"` and the default behavior is to not open links in new windows. Thus I am not sure why `click.prevent=”e =>f(e)”` would be necessary in most cases.

I did however notice that there are some external links that do not use `target="_blank"` which makes them open in the current window.

Would it make sense to reformulate this task as to state that we want a consistent behavior from links:
- Local links should open in the same window
- External links should open in a new window

Or am I missing something?

**Comment by mihai-sysbio** [comment]
> Would it make sense to reformulate this task as to state that we want a consistent behavior from links:
>     * Local links should open in the same window
>     * External links should open in a new window

Great summary @pdmnyberg!
