### ISSUE TITLE
UptimeRobot downtime incident

### ISSUE THREAD

**Issue by KattisLej** [MetabolicAtlas/MetabolicAtlas#1361]
From UptimeRobot alert:

Monitor is DOWN: MetAtlas: prod API ( https://metabolicatlas.org/api/v2/repository/integrated_models ) - Reason: Connection Timeout

This is a placeholder issue for the time the team spent on researching the incident and deciding on how to handle it.

**Comment by mihai-sysbio** [comment]
This incident has been handled and new issues have been created to prevent this happening in the future.
