### ISSUE TITLE
implement bioschemas.org for existing content

### ISSUE THREAD

**Issue by e0** [MetabolicAtlas/MetabolicAtlas#579]
### Original issue description

Use bioschemas.org with the help of a library like [vue-headful](https://www.npmjs.com/package/vue-headful)/[vue-meta](https://www.npmjs.com/package/vue-meta)/[vue-head](https://www.npmjs.com/package/vue-head) for the following:

- [ ] everything in the GEM Browser
- [ ] papers under resources
- [ ] the metabolic atlas citation
- [ ] all other references on the about page

Focus on content that already exists on Met Atlas, and on bioschemas (don’t worry about schema.org). There are a bunch of ways to [test the implementation](ttps://bioschemas.org/tutorials/howto/howto_check_deploy).

### Updated issue description that reflects change in scope

As a developer, I would like to improve the schema definition of the HTML document for gem browser component pages, so that users and systems (search engine, link previewer, etc.) receive with more meaningful previews that reflect the contents of the pages.

- [x] update the `title` for gem browser component pages
- [x] add a `description` for gem browser component pages
- [x] add a bioschemas compatible schema for gene pages

**Comment by e0** [comment]
I have read a bit about Bioschemas and looked through [the profiles](https://bioschemas.org/profiles/). From the list, I see they have a [Gene profile](https://bioschemas.org/profiles/Gene/0.7-RELEASE/), which we could use as reference. Is there any other profile, and if so please let me know for which pages, that we could use?

**Comment by mihai-sysbio** [comment]
How about using the [Taxon](https://bioschemas.org/profiles/Taxon/0.6-RELEASE/) for the Explore page? It’s where we list all the integrated models. If easy enough, I could also see this in the GEM repository, but definitely not a must.
For checklist items 2-4, I believe we would need to use the [ScholarlyArticle](https://bioschemas.org/profiles/ScholarlyArticle/0.2-DRAFT-2020_12_03/). This is still a draft, and it looks like it has been for a while. Would it make sense to implement it now?

**Comment by mihai-sysbio** [comment]
There is an example provided for the `taxonRank`.

I guess the question is the same for both Taxon and ScholarlyArticle - how to handle pages with multiple entities. I haven't look this up yet but the answer should be in the docs.

**Comment by e0** [comment]
I looked at the example for Taxon but still don't quite understand. It would be nice if someone with more domain knowledge can help provide an example of how this should look like for us.

Also I didn't find any documentation that addresses pages with multiple entities, so I would appreciate if you can help point me to the right direction here as well.

**Comment by mihai-sysbio** [comment]
We should not forget that bioschemas is essentially a topic-specific schema.org implementation. When looking this up, I found many people wondering about the same thing. Here is a starting point: https://www.schemaapp.com/schema-markup/multiple-entities-on-one-page/

**Comment by e0** [comment]
> We should not forget that bioschemas is essentially a topic-specific schema.org implementation. When looking this up, I found many people wondering about the same thing. Here is a starting point: https://www.schemaapp.com/schema-markup/multiple-entities-on-one-page/

Thanks. I didn't look into schema.org at all according to the issue description. We agreed yesterday to open a new issue for multiple entities and focus on the gem browser pages for this issue. Should we still create a new issue or look into multiple entities in this one? Either way is fine, just want to get some clarity.

**Comment by mihai-sysbio** [comment]
To me, this ends up being a personal decision. Both single-page and multiple-page entries are required, and I envisioned the issue to contain both. How would you like to proceed @e0 ?

**Comment by e0** [comment]
It is still not clear to me what the best approach is for pages with multiple entities, so I will create a new issue for that.

**Comment by mihai-sysbio** [comment]
This issue has changed scope. @e0 could you please make sure the initial description matches the PR, and move the remaining stuff to other issues or to the parent epic?

**Comment by e0** [comment]
> This issue has changed scope. @e0 could you please make sure the initial description matches the PR, and move the remaining stuff to other issues or to the parent epic?

Good reminder. I have added a new section instead of overwriting the old description so that it's easier to spot the difference.
