### ISSUE TITLE
Improve UX for first time users of Interaction Partners

### ISSUE THREAD

**Issue by e0** [MetabolicAtlas/MetabolicAtlas#580]
When at https://metabolicatlas.org/ and pressing Interaction Partners the model and id are “hardcoded“ to be `Human-GEM` and `m02007p`. That leads to https://metabolicatlas.org/explore/Human-GEM/interaction-partners/m02007p, i.e. a page with no info on how to choose a different metabolite or information about the tool. For first time users, it would be beneficial with a “choose random metabolite” or short info regarding using the search bar + interaction icon and link to the documentation. 

Preferably, the “don’t make me think“ mentality should be kept in mind when designing this.

**Comment by e0** [comment]
<img width="563" alt="image" src="https://user-images.githubusercontent.com/423498/118652281-bb706b00-b7e6-11eb-9bb7-596fd8a7fc12.png">

**Comment by inghylt** [comment]
Fixed with pull request #587
