### ISSUE TITLE
GEM Browser shows broken image when ChEBI image does not exist

### ISSUE THREAD

**Issue by e0** [MetabolicAtlas/MetabolicAtlas#583]
When the ChEBI entry exists but ChEBI image does not, the GEM-Browser still shows the ChEBI frame but with broken image. Maybe we can display it in a better way. 

An example is for the metabolite `m02576c`, url: http://localhost/explore/Human-GEM/gem-browser/metabolite/m02576c.  

This will be solved by pretending there is no ChEBI id.
![image](https://user-images.githubusercontent.com/423498/118655769-27080780-b7ea-11eb-9c91-86ffb97f1b53.png)

**Comment by e0** [comment]
<img width="542" alt="image" src="https://user-images.githubusercontent.com/423498/118655919-4c951100-b7ea-11eb-9b0e-a2021bbdfc42.png">

**Comment by inghylt** [comment]
Fixed with pull request #589
