### ISSUE TITLE
Consistent usage disabling or removing content when RNA levels via proteinAtlas.org is unavailable

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#591]
In Map Viewer, if the model is not human we are currently removing the entire div with possibility to use gene expression data from proteinatlas . However, in Interaction Partners we are just disabling it and have the text "Unavailable for [model]".

[Map Viewer example](http://localhost/explore/Yeast-GEM/map-viewer/pentose_and_glucuronate_interconversions?dim=2d&panel=1&sel=&search=&coords=-617.54,-846.98,0.47,0,0,500&g1=None&g2=None), [Interaction Partners example](http://localhost/explore/Yeast-GEM/interaction-partners/s_3310)

As a user, I would like related content to behave in the same manner, so that I know what to expect when using the web page

**Comment by mihai-sysbio** [comment]
Might require closing.
