### ISSUE TITLE
Mismatch of reactions in model and SVG map

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#597]
As a developer, I would like all reaction IDs in the SVG map to be found in the model, so that the IDs are coherent.

Verified issue is for the new TSV format Golgi apparatus there were 41 reaction IDs in the SVG map not found in the  data-files/integrated-models/Human-GEM/Human-GEM.yml

Verification has not been performed for old TSV format

**Comment by nanjiangshu** [comment]
I can confirm the mismatch also for the old TSV format as in the branch `feat/more-models` for the repo `data-files`

**Comment by mihai-sysbio** [comment]
As the models are being revised, they not only gain reactions but also lose reactions. Without updating the SVG maps, the reactions would still appear to be part of the model even though they're not.

**Comment by mihai-sysbio** [comment]
I'm in favour of closing this issue, as the proper fix is to have a new way of obtaining the 2D maps.
