### ISSUE TITLE
Improve documentation of GitHub repo

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#601]
_CII Best Practice badge: The information on how to contribute SHOULD include the requirements for acceptable contributions (e.g., a reference to any required coding standard). (URL required)_

As a developer, I would like to know what problem MetabolicAtlas solves and how to contribute (including a reference to coding standard), so that it is straightforward for me to understand the project and contribute. 

Checklist
- [ ] describe in the readme what MetAtlas is about
- [ ] Link to the contribution guideline
- [ ] Update the CII badget 
- [ ] Update in the readme about how the users should report a bug or vulnerability

**Comment by mihai-sysbio** [comment]
I feel like with #712 and with issue/PR templates this issue wouldn't need more than updating the CII badge.
