### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#605]
CII Best Practice:
- _The project MUST use at least one automated test suite that is publicly released as FLOSS (this test suite may be maintained as a separate FLOSS project). The project MUST clearly show or document how to run the test suite(s) (e.g., via a continuous integration (CI) script or via documentation in files such as BUILD.md, README.md, or CONTRIBUTING.md)_
- _A test suite SHOULD be invocable in a standard way for that language_
- _It is SUGGESTED that the test suite cover most (or ideally all) the code branches, input fields, and functionality_
- _It is SUGGESTED that the project implement continuous integration (where new or changed code is frequently integrated into a central code repository and automated tests are run on the result)_
- _The project MUST have a general policy (formal or not) that as major new functionality is added to the software produced by the project, tests of that functionality should be added to an automated test suite._
- _The project MUST have evidence that the test_policy for adding tests has been adhered to in the most recent major changes to the software produced by the project._
- _It is SUGGESTED that this policy on adding tests (see test_policy) be documented in the instructions for change proposals._

As a developer, I would like to have test validating my code, so that I know that changes I make don't create bugs that are missed during PR reviews

As a user, I would like to have test validating the code, so that I know that the software I use is functional and that I use valid data

**Comment by mihai-sysbio** [comment]
The testing framework `cypress` is implemented - a first test in written at `frontend/cypress/testing`. To run the tests see the dev docs

Potentially use  https://chrome.google.com/webstore/detail/cypress-recorder/glcapdcacdfkokcmicllhcjigeodacab

**Comment by mihai-sysbio** [comment]
@e0 mentioned these frameworks in https://github.com/MetabolicAtlas/MetabolicAtlas/pull/673#issuecomment-908275439 :

* https://github.com/lukeed/uvu
* https://jestjs.io

**Comment by inghylt** [comment]
Issues
#849
#1082
#1083

are actionable issues that cover what we have left to fulfill, closing this epic
