### ISSUE TITLE
Create consistency regarding usage of external and identifier in the frontend

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#608]
As a user, I would like to have the same "group name" for identifiers belonging to external databases, so that I get a cohesive experience.

Currently, _external-db_ and _identifier_ are used to reference to the same type of identifier, i.e. identifiers referencing to BiGG, HepatoNet1 etc. 

It might be worth not using _identifier_ as the group name, as we technically have identifiers in all of the data types.

**Comment by inghylt** [comment]
I have looked into this, and I don't really see anything that needs to be fixed in the frontend.

We use external db/identifier or just identifier in:

- [Gem browser](https://dev-metatlas.csbi.chalmers.se/explore/Human-GEM/gem-browser/reaction/MAR07075), where we have the title "External databases"
- [/identifier/:dbName/:identifierId](https://dev-metatlas.csbi.chalmers.se/identifier/BiGG/15DMTitr)
- [root page](https://dev-metatlas.csbi.chalmers.se/)
    - "The integrated models can be compared on-the-fly via the external identifiers they share."
    - "Working with metabolic models requires a set of tools and external databases, which we have collected together for one-click access."
- [Global search](https://dev-metatlas.csbi.chalmers.se/search?term=dddddddddd)
    - "If this is an alias or external identifier, it means it is not present in any of the models. "
    - As one of the info bullets, e.g.
    Metabolites
        - ID
        - Name or aliases
        - Formula without charge
        - External identifiers
- [Documentation](https://dev-metatlas.csbi.chalmers.se/documentation) 
    - "If provided by the modellers, a list of identifiers from external databases and a list of references (PMIDs) are also shown in the References table below."
    - "additional identifiers from external databases will also be shown in the External databases table under the top table."
    - "In the first section of the page one can select 2 or 3 integrated GEMs to compare. The comparison is performed dynamically, by inspecting the external identifiers in the database. If a reaction or a metabolite share at least one such external identifier, they are considered to be shared between the compared models. Otherwise, they are considerend to be unique to the respective model."   

As I see it, there are external databases, such as BiGG, KEGG, PubChem etc. These external databases have identifiers, i.e. external identifiers. I think the main discussion that created this issue was that we added `/identifier/:dbName/:identifierId` and that we did not think that was in alignment with the title "External databases" in Gem browser. But the "External databases" section is a list of external databases, and the related identifiers in these database. I think that title makes sense and is better than for example "External Identifiers". And I think using the url `/identifier/:dbName/:identifierId` also makes sense, since the main functionality is to search for the occurrence of external identifier within the models. Perhaps one could name it to `/external-identifier/:dbName/:extIdentifierId`, but I don't think it is an improvement.

The only potential inconsistency I can think of is how we have named things in the code base. `frontend/src/components/ExternalDb.vue` and `frontend/src/store/modules/externalDb.js` is related to `/identifier/:dbName/:identifierId`, i.e. search for the occurrence of external identifier within the models. Maybe they should be renamed to something like `frontend/src/components/ExtIdInModels.vue` to reflect it's functionality

**Comment by inghylt** [comment]
@mihai-sysbio @e0 @MalinAhlberg @nanjiangshu Please read through the summary above. I you feel like feedback is too time consuming to write/you would like to discuss it live, I suggest we do it after a stand up

**Comment by e0** [comment]
Really good job compiling all the findings @inghylt!

It's a minor thing but the only change I want to propose is to change all usages of "external identifier" to "external database identifier". I think it would be clearer and more consistent, for example compared to "a list of identifiers from external databases".

> The only potential inconsistency I can think of is how we have named things in the code base. `frontend/src/components/ExternalDb.vue` and `frontend/src/store/modules/externalDb.js` is related to `/identifier/:dbName/:identifierId`, i.e. search for the occurrence of external identifier within the models.

I think having `/identifier` here feels more correct actually because we also serve our HMR components (for example: `/identifier/HMR%202.0/m00731c`) here and I don't think they should count as external resources.

**Comment by MalinAhlberg** [comment]
Yes, very good compilation! I agree with you both, and couldn't find anything else to comment on.

**Comment by e0** [comment]
> So maybe `~External databases~` should become `External identifiers` like @inghylt suggested.

Good point about the contradiction @mihai-sysbio . For me the main problem I see is that not everything is "external", so I don't see the benefit of going from `~External databases~` to `External identifiers`.

**Comment by mihai-sysbio** [comment]
Different suggestion, copied from a very well regarded database: [`cross-references`](https://www.uniprot.org/uniprot/O00418#cross_references)
