### ISSUE TITLE
Sort results alphabetically from API

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#609]
As a user I would like lists of results, from the API, to be sorted alphabetically, so that I do not have to think about the order of the items in the list. 

All api queries, except `gotEnzymes` routes, are to be sorted (there might be exceptions) Only endpoints which return list are relevant and only the top level list is to be sorted.

Related discussion: https://github.com/MetabolicAtlas/MetabolicAtlas/pull/574#pullrequestreview-672536208

**Acceptance criteria**
- [ ] if there is an front-end sorting, that should be removed
- [ ] sort by model if applicable
- [ ] sort only top-level structure
- [ ] some requests do not need sorting (such as the graph layout or when already sorting score)
- [ ] create separate issue(s) for the items where sorting would take longer to fix
- [ ] update tests if necessary

**Comment by pdmnyberg** [comment]
@mihai-sysbio Just to make things completely clear. When looking into this task I notice that the API used by http://localhost/identifier/BiGG/PPNCL3 actually returns an object. Previously I assumed that `top-level` structure meant `when the result is a list` but that is not the case as far as I understand now.

Would you like me to try to sort any `list` that is located in the root object or could you clarify what is meant by `top-level`.

**Comment by pdmnyberg** [comment]
Another thing to be noted is that the related discussion refers to http://localhost/explore which uses an entirely different endpoint which is not a `neo4j` which makes me think we might need some discussion in regards to what the actual goal of this issue.

I think it would be a good idea to separate the specific http://localhost/identifier/BiGG/PPNCL3 from the general neo4j or genereal endpoint changes.

**Comment by pdmnyberg** [comment]
I have looked into the endpoints and my understanding is as follows:
```yaml
'/compartments/:id': Is Object
'/compartments/:id/related-reactions': Already ordered
'/genes/:id': Is Objecy
'/genes/:id/related-reactions': Already ordered
'/hpa/gene/:id': Is Object
'/metabolites/:id': Is Object
'/metabolites/:id/related-reactions': Already ordered
'/reactions/:id': Is Object
'/reactions/:id/related-reactions': Already ordered
'/subsystems/:id': Is Object
'/subsystems/:id/related-reactions': Already ordered
'/interaction-partners/:id': Is Object
'/interaction-partners-expansion/:id': Is Object
'/maps/listing': Already ordered data.subsystem.name
'/maps/search': Should use relevance for order
'/search': Should use relevance for order
'/3d-network': Is Object
'/compare': Is Object
'/comparison-details': Is Object
'/external-db/:dbName/:externalId': Is Object
'/repository/integrated_models/:name': Is Object
'/data-overlay/:model': Is Object
'/data-overlay/:model/:dataType/:filename/data-sets':
'/data-overlay/:model/:dataType/:filename/data-sets/:dataSetName': Is Object

'/random-components': Assume random order is ok
'/hpa/genes': External enpoint with no need of sorting

'/svg-thumbnail/*': Ignored
'/gotenzymes/*': Ignored

'/metabolites/:id/related-metabolites': Possible need of sorting -> not sorted in frontend
'/repository/models': Possible need of sorting -> trivial
'/repository/integrated_models': Possible need of sorting -> trivial
```

**Comment by mihai-sysbio** [comment]
Nice summary @pdmnyberg, it makes sense to me.
I think the `data-sets` are returned based on the `index.tsv`, so perhaps we should document that alphabetical ordering should be used to avoid any ordering in the API. 
The related metabolites will only differ in the last letter of their identifier, but that should be sufficient for alphabetical ordering (since that letter is "distinct" - it's a unique abbreviation of a cellular compartment).

**Comment by pdmnyberg** [comment]
Regarding `data-sets` I personally prefer system support over documentation but I guess that is a solution. I am not familiar with the caching method yet but I would assume that this is an endpoint that is well suited for result-caching?

And to be completely clear. From the list I intend to adjust the following endpoints and their respective frontend sorting:
```
'/data-overlay/:model/:dataType/:filename/data-sets': Possible need of sorting
'/metabolites/:id/related-metabolites': Possible need of sorting -> not sorted in frontend
'/repository/models': Possible need of sorting -> trivial
'/repository/integrated_models': Possible need of sorting -> trivial
```
