### ISSUE TITLE
Remove Chondroitin sulfate degradation from Map viewer sidebar

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#612]
https://metabolicatlas.org/explore/Human-GEM/map-viewer/chondroitin_sulfate_degradation?dim=2d

There seem to be no map available for Chondroitin sulfate degradation, thus it's name should not be clickable in the sidebar

**Comment by mihai-sysbio** [comment]
Resolved through commit https://github.com/MetabolicAtlas/data-files/pull/4/commits/cd00124bd0fd22ef3fefcd8a430d9530c45ae151
