### ISSUE TITLE
Verify bioschemas in production environment

### ISSUE THREAD

**Issue by e0** [MetabolicAtlas/MetabolicAtlas#614]
As a developer, I would like to verify the bioschemas format in a production environment, so that I can ensure the markup is implemented properly.

This is related to https://github.com/MetabolicAtlas/MetabolicAtlas/issues/579. As a verification, it would be good to use a tool (for example: https://validator.schema.org) to make sure that the markup generated is as expected. Currently only the gene pages in gem browser have implementation according to a bioschemas compatible profile. The following page can be used as an example to test: https://metabolicatlas.org/explore/Human-GEM/gem-browser/gene/ENSG00000136010.

Edit: It would also be good to test the `title` and `description` changes in link previews (for example sending over Slack), as well as in search engines (for example Google and DuckDuckGo).

**Comment by mihai-sysbio** [comment]
If I understand correctly, this is issue is only about verifying in the production environment. My follow-up question would be why can't this be verified locally though, knowing it would be the same in the production environment?

**Comment by e0** [comment]
The markup in local development mode is not the same as in production. This issue is a reminder to double check that things are done correctly after deploy.

**Comment by mihai-sysbio** [comment]
> The markup (HTML document) in local development mode is not the same as in production

@e0 besides the host url changing, what other changes in the HTML should we be aware of?

**Comment by e0** [comment]
There is a lot of Vue specific stuff that's helpful during development but is stripped away for production. There is also other type of verifications (which I should have mentioned in the original issue description such as link previews when sending over Slack for example and verifying search engine titles and summaries) that makes more sense to test only on production.

**Comment by nanjiangshu** [comment]
Hi @mihai-sysbio and @e0, I've deployed the branch `feat/bioschemas_MA-675` on the dev server and verified the Genes page using Schema Markup Validator. The profile looks fine as shown by 
https://validator.schema.org/#url=https%3A%2F%2Fdev-metatlas.csbi.chalmers.se%2Fexplore%2FHuman-GEM%2Fgem-browser%2Fgene%2FENSG00000136010 

However, I could not find the entry `title` nor `description`, it seems they are not returned.

**Comment by e0** [comment]
@nanjiangshu Thanks for deploying and trying this out. I was wondering if it was maybe due to caching but I realized it is probably because these fields for title and description are populated after the webpage already loads and it makes another request to get the component data. To get around this issue, I think we would need to do some [SSR](https://ssr.vuejs.org). That would be a much larger issue though with changes to our infrastructure so we should probably have a talk before deciding if we want to make this change.

For now, I think the best things to do is to only focus on the bioschemas for genes and metabolites in this PR.
