### ISSUE TITLE
Add explanation for large number of missing reactions for cytosol maps

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#615]
As a user, I would like to know that there is a large number of missing reactions due to the compartment being split into several maps, so that I don't think the cytosol maps are inadequate 

To ask for feedback: Could be beneficial to have a function that summarize the reactions from each individual map so the user can view the actual number of missing reactions in the compartment.

**Comment by mihai-sysbio** [comment]
We need to compute the missing reactions in any of the 5 maps for Cytosol, and show that collectively. Hard-coding is acceptable.

**Comment by inghylt** [comment]
As I understand it, this issue now means:

- [ ] Create a function that summarize the reactions in the Cytosol maps and subtract this from the reactions available in the Cytosol model
- [ ] For every Cytosol map, have this resulting number displayed in the SidebarDataPanels instead of the default missingReactionList.length
- [ ] For every Cytosol map, the popup (modal) should have information that Cytosol is split into multiple maps due to its size and the number of missing reaction displayed is the missing reactions when all the reactions in the Cytosol maps are combined and not per individual map.
- [ ] For every Cytosol map, the popup (modal) should replace "Missing reactions on the map" and "Reactions shown on the map" with "Missing reactions on the combined Cytosol maps" and "Reactions shown on the combined Cytosol maps"

**Comment by mihai-sysbio** [comment]
Sounds great @inghylt !
