### ISSUE TITLE
Merge data overlay changes

### ISSUE THREAD

**Issue by e0** [MetabolicAtlas/MetabolicAtlas#616]
As a developer, I would like to merge in the changes from https://github.com/MetabolicAtlas/MetabolicAtlas/pull/571, so that no important work from the past is lost.

It's a good initiative to try to resolve legacy issues but the PR is not ready to be merged yet.

Related comment: https://github.com/MetabolicAtlas/MetabolicAtlas/pull/571#issuecomment-856034900

**Comment by mihai-sysbio** [comment]
Decided to not pursue this, in favor of continuing the refactoring of the data overlay as we have it now.
