### ISSUE TITLE
Improve deployment workflow regarding environment variables for different environments

### ISSUE THREAD

**Issue by e0** [MetabolicAtlas/MetabolicAtlas#618]
As a developer, I would like to improve the deployment workflow regarding environment variables, so that I can avoid editing the `.env` file before deploying to a different environment

This is to avoid potential problems with using wrong environment variables when deploying.

For example, different environment files could be used:

- `.env_local` -> localhost
- `.env_dev` -> dev server
- `.env_prod` -> prod server

**Comment by mihai-sysbio** [comment]
@e0 could you revise the description so as to limit it to the issue, without forcing a predetermined solution?
