### ISSUE TITLE
some reactions do not render

### ISSUE THREAD

**Issue by mihai-sysbio** [MetabolicAtlas/MetabolicAtlas#623]
As a user, I want to click on search items (either quicksearch or global search), so that I see the details of the component I'm interested in.

After clicking on some reactions in the quicksearch, they do not render and trigger errors instead, eg HMR_9577 and HMR_9579. The API response seems fine. This issue was reported by @JonathanRob.

https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/HMR_9491

**Comment by inghylt** [comment]
Reaction 2HIVc trigger errors as well
