### ISSUE TITLE
Maps available showing 2D maps that actually don't contain the component

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#626]
https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/13DMTtu
None of the cytosol maps have 13DMTtu (same on localhost new tsv files)

https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/HYOCHOLt2
Only part 1 have HYOCHOLt2 (same on localhost new tsv files)

**Comment by mihai-sysbio** [comment]
The implementation of MA-867 will handle these artefacts of maps being out of sync with the model.
