### ISSUE TITLE
Previousely selected component still shown after changing to a new 2D map. 

### ISSUE THREAD

**Issue by nanjiangshu** [MetabolicAtlas/MetabolicAtlas#630]
As a user, I would like the previously selected component show on the map listing sidebar be cleared after changing to a new 2D map. 

P.S. please ignore this issue if it is a desired feature.

**Comment by mihai-sysbio** [comment]
To reproduce this bug, open the Map Viewer and select a map. Then, click on a node on the map. This will bring up a card in the left sidebar with details on that component. At this stage, changing the map should "de-select" the reaction, ie the card with the component details should be removed.

**Comment by mihai-sysbio** [comment]
The card should be kept if the sidebar if the newly selected map contains the selected element.
