### ISSUE TITLE
incorporate feedback for the identifier page

### ISSUE THREAD

**Issue by mihai-sysbio** [MetabolicAtlas/MetabolicAtlas#637]
After getting feedback on #575, the following items should be implemented:

- [x] the component name at the beginning of each bullet list item should be removed
- [x] the components should be grouped by model (eg in sections)
- [ ] ~for the Metabolite ids, use the metabolite name~
- [x] link from the `External databases` section

**Comment by nanjiangshu** [comment]
I've implemented point 1&2 of the feedback in the branch `feat/feedback-identifier`. A screenshot for the example `/identifier/BiGG/carveol` is shown below. 
![Screenshot 2021-09-10 at 22.29.00.png](https://images.zenhubusercontent.com/58ca67a651aa2c305778a403/7702aa87-2751-499b-898a-59eb26c20021)

However, I'm not very clear about the point 3 and 4. 

For the point 3. What does it mean to use metabolite name for metabolite IDs? If it is to replace all metabolite IDs "MAM..." in the example shown to metablite name `carveol`, then it will be weird that all listed components will be shown as `carveol`. If it is for the header line `BiGG Metabolite carveol`, then it is already the metabolite name `carveol` that is used.

For the point 4, should this page `/identifier/BiGG/carveol` be linked from somewhere within the MetAtlas server or from https://identifiers.org/? If it is linked from within the MetAtlas server, does it mean when a user click the item `carveol` for BiGG in the external database section (as shown in the screenshot below), it will be linked to this page `/identifier/BiGG/carveol` for MetAtlas?

![Screenshot 2021-09-10 at 23.03.31.png](https://images.zenhubusercontent.com/58ca67a651aa2c305778a403/f097ad96-9639-49c2-8e2d-da13b57eecc1)

**Comment by mihai-sysbio** [comment]
> I've implemented point 1&2 of the feedback in the branch `feat/feedback-identifier`. A screenshot for the example `/identifier/BiGG/carveol` is shown below.

Looks nice. I have some suggestions, but I think the PR is a better place for these.

> For the point 3. What does it mean to use metabolite name for metabolite IDs? If it is to replace all metabolite IDs "MAM..." in the example shown to metablite name `carveol`, then it will be weird that all listed components will be shown as `carveol`. If it is for the header line `BiGG Metabolite carveol`, then it is already the metabolite name `carveol` that is used.

If one clicks on any of the links listed in `/identifier/BiGG/carveol`, the `Metabolite` page will show the metabolite name at thee top, as it is more meaningful. At the same time, you're highlighting an upcoming problem of not being able to differentiate between the compartmentalized metabolites. To handle both feedback items, I would suggest to go for a combination of id and name.

> For the point 4, should this page `/identifier/BiGG/carveol` be linked from somewhere within the MetAtlas server or from https://identifiers.org/? If it is linked from within the MetAtlas server, does it mean when a user click the item `carveol` for BiGG in the external database section (as shown in the screenshot below), it will be linked to this page `/identifier/BiGG/carveol` instead to https://identifiers.org/bigg.metabolite:carveol?

I see this was already implemented in the PR, by connecting this page from the `External databases section` 👍🏻
