### ISSUE TITLE
text selection in Map Viewer search bar

### ISSUE THREAD

**Issue by mihai-sysbio** [MetabolicAtlas/MetabolicAtlas#638]
As a user, I want to select the text in the search bar of the Map Viewer, so that I can edit it conveniently or copy-paste it. This was reported by @johan-gson.

**Comment by e0** [comment]
This issue might be tricky. After discussion, the aim is to research the problem and document the findings. If it seems that it's easily fixable then the a PR should be added directly to address this issue.

**Comment by e0** [comment]
@inghylt made an [interesting observation](https://github.com/MetabolicAtlas/MetabolicAtlas/issues/648#issuecomment-875692397) about a weird connection between a `z-index` problem and code that looks completely irrelevant. Just want to make a note of it here and maybe it could be helpful to look for similar things when working on this issue.
