### ISSUE TITLE
reaction 2HIVc not found

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#641]
Reaction with id 2HIVc is searchable in the search bar and can show up as an option for the random components in gembrowser, but https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/2HIVc returns that the reaction is not found

**Comment by mihai-sysbio** [comment]
@inghylt isn't this a duplicate of #623 ?

**Comment by inghylt** [comment]
Ah yes, nice that you saw that. I'll add the id to that issue instead
