### ISSUE TITLE
Warning message "2D map is not available" remains once it appears

### ISSUE THREAD

**Issue by nanjiangshu** [MetabolicAtlas/MetabolicAtlas#645]
As a user, I would like the warning message appears when a 2D map is not available but disappears after selecting an existing 2D map. 

How to reproduce the bug:

* Choose "Yeast Gem" in Map Viewer
* Select `Fatty acid biosynthesis`
* Switch to 3D viewer
* Select `sce00791 atrazine degradation`
* Switch to 2D viewer 
The warning message will appear 
* select `Fatty acid biosynthesis` again 
The warning message remains   

![Screenshot 2021-06-30 at 13.02.16.png](https://images.zenhubusercontent.com/58ca67a651aa2c305778a403/aff3f42c-517b-4f0a-9c86-9e69a7785e11)

**Comment by e0** [comment]
@inghylt made an [interesting observation](https://github.com/MetabolicAtlas/MetabolicAtlas/issues/648#issuecomment-875692397) about a weird connection between a `z-index` problem and code that looks completely irrelevant. Just want to make a note of it here and maybe it could be helpful to look for similar things when working on this issue.
