### ISSUE TITLE
Missing reaction popup modal not shown as expected

### ISSUE THREAD

**Issue by nanjiangshu** [MetabolicAtlas/MetabolicAtlas#648]
As a user, I would like the modal window popup to the front when clicking the `See comparison` in the left sidebar to 2D map viewer. However, as shown in the attached screenshots, the modal window is displayed behind some components of the map viewer. 

This issue might be a good application for `git bisect`

(for Chrome)
![Screenshot 2021-07-02 at 11.30.08.png](https://images.zenhubusercontent.com/58ca67a651aa2c305778a403/a1f7e0a6-f626-480e-a81b-674c0f62c682) 

(for Firefox and Safari)
![Screenshot 2021-07-02 at 19.50.56.png](https://images.zenhubusercontent.com/58ca67a651aa2c305778a403/2f858347-c1d9-40a7-9928-d8485d0cd712)

**Comment by inghylt** [comment]
Seems like commit [349a9bf0cb0cf0284313e0130966f58df1843997](https://github.com/MetabolicAtlas/MetabolicAtlas/commit/349a9bf0cb0cf0284313e0130966f58df1843997) introduced the bug

**Comment by e0** [comment]
> Seems like commit [349a9bf0cb0cf0284313e0130966f58df1843997](https://github.com/MetabolicAtlas/MetabolicAtlas/commit/349a9bf0cb0cf0284313e0130966f58df1843997) introduced the bug

Interesting. I can imagine if the associated PR to this commit causes the bug but it's pretty wild to me that this commit itself would cause it.

**Comment by inghylt** [comment]
Yeah it's weird. The commit before [76fbf2cceaaffca8dc12ba6e8f917a2ebf447e4b](https://github.com/MetabolicAtlas/MetabolicAtlas/commit/76fbf2cceaaffca8dc12ba6e8f917a2ebf447e4b) and all previous ones works fine though so it legit seems to be introduced by that

**Comment by e0** [comment]
> Yeah it's weird. The commit before [76fbf2cceaaffca8dc12ba6e8f917a2ebf447e4b](https://github.com/MetabolicAtlas/MetabolicAtlas/commit/76fbf2cceaaffca8dc12ba6e8f917a2ebf447e4b) and all previous ones works fine though so it legit seems to be introduced by that

That's some great detective work. I guess we could just revert this commit or maybe try [the variation](https://github.com/MetabolicAtlas/MetabolicAtlas/pull/628#discussion_r656197559) @mihai-sysbio suggested and see if it goes away.

**Comment by inghylt** [comment]
Some more investigation shows that it is actually commit [f08c43c2a68ed16d3dfb97c2cb95985931d58ca4](https://github.com/MetabolicAtlas/MetabolicAtlas/commit/f08c43c2a68ed16d3dfb97c2cb95985931d58ca4#diff-58c51e03582c094adf35b4e2a375d37ac5880e0ac09e2bee5d2c2ab3185704e0) that leads to the broken modal, I looked at commits to develop previously and not SidebarDataPanels.vue...

**Comment by e0** [comment]
Ok, that does make more sense!

**Comment by mihai-sysbio** [comment]
Hmm that's unexpected, bisect lead me to 8f43b0df6104b255bd9f9a60b9be8b46c683bb33

**Comment by mihai-sysbio** [comment]
After having a deeper look, it seems that the styling applied via `mapSidebar__header` is the culprit.

**Comment by inghylt** [comment]
Haha wow thanks. I started comparing manually bcs I wanted to rebuild and stuff to compare and then I just continued but lessons def learned that bisect is the way to go  :')

**Comment by e0** [comment]
> After having a deeper look, it seems that the styling applied via `mapSidebar__header` is the culprit.

That makes perfect sense!
