### ISSUE TITLE
dynamic model component counts

### ISSUE THREAD

**Issue by mihai-sysbio** [MetabolicAtlas/MetabolicAtlas#656]
As a user, I want to see the model component counts, so that I know how large a model is.

As a developer I want the reaction, metabolite and gene counts for each model to be automatically updated, so that I don't need to manually update these.

At the moment, the counts are statically stored in the `data-files` repository, in `integratedModels.json`.

**Comment by e0** [comment]
This does not involve modifying the `integratedModels.json` file during import.

**Comment by e0** [comment]
For verifying the results, the count should be compared with the yml files, for example number of occurrences for `MA...`.
