### ISSUE TITLE
unmount 3D viewer when not in use

### ISSUE THREAD

**Issue by e0** [MetabolicAtlas/MetabolicAtlas#664]
As a user, I want to the 3D viewer to be unmounted when it is not in use, so that it does not take up computing resources unnecessarily.

It seems that once the 3D viewer is loaded for a component, it does not unmount when changing to another page (unless the new page is reloaded). In the attached video, see the browser console, which keeps logging out 3D viewer related activity after the gem browser page is loaded.

https://user-images.githubusercontent.com/423498/126984248-4beba0b2-a1e4-4e4b-8f09-b9c60ef0f307.mov

**Comment by mihai-sysbio** [comment]
Nice job spotting this!

**Comment by e0** [comment]
This wasn't estimated prior to starting. I retrospect, I think it would be a 3 or 4.
