### ISSUE TITLE
add word break for MapsAvailable.vue

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#675]
When the maps have very long names, such as in https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR08387, the 3d button does not fit.

**Comment by mihai-sysbio** [comment]
It looks like `overflow-wrap: anywhere;` on the text cell would do the job.

**Comment by e0** [comment]
> It looks like `overflow-wrap: anywhere;` on the text cell would do the job.

Good suggestion but it doesn't work on Safari: https://caniuse.com/mdn-css_properties_overflow-wrap_anywhere

`word-break: break-word;` should be fine: https://caniuse.com/mdn-css_properties_word-break_break-word

**Comment by inghylt** [comment]
![image.png](https://images.zenhubusercontent.com/5fc0f648ba2981921764866b/be5d959d-b9e9-4a7a-9b68-00525f5b5ef5)

Print screen for demo
