### ISSUE TITLE
related reactions not refreshing

### ISSUE THREAD

**Issue by mihai-sysbio** [MetabolicAtlas/MetabolicAtlas#680]
Originally reported [here](https://github.com/MetabolicAtlas/MetabolicAtlas/issues/646#issuecomment-909426341) by @JonathanRob (tagging him to keep him in the loop).

As a user, I want to see the accurate content of the model reflected on the GEM browser pages.

When navigating through consecutive Reaction pages, the `Related reactions` row from the first table does not update (stays the same as in the first Reaction page displayed).

Note: Previously the entire page has not been refreshed and it has been solved. Now only the related reaction ID is not refreshed.

**Comment by nanjiangshu** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MetAtlas-Roadmap-60d96b68da0fb10019d26deb/issues/MetabolicAtlas/MetabolicAtlas/680?planning-poker) with ZenHub @inghylt @MalinAhlberg @mihai-sysbio

**Comment by inghylt** [comment]
Updating `CALL db.index.fulltext.createNodeIndex params` in `data-generation/cypher.js` to include `ExternalDb` and updating `MetabolicAtlas/api/src/neo4j/queries/search.js` seems to be a good step to enable neo4j to return matches for old Ids

Not sure though if all old Ids stem from External databases, that should be researched

**Comment by inghylt** [comment]
![image.png](https://images.zenhubusercontent.com/5fc0f648ba2981921764866b/12be83cc-3a59-4de5-ada8-afb3d2753190)

![image.png](https://images.zenhubusercontent.com/5fc0f648ba2981921764866b/78849a72-7544-47fc-a353-f34d71646095)

Print screens for demo

**Comment by mihai-sysbio** [comment]
> Not sure though if all old Ids stem from External databases with ids available in the neo4j db, that should be researched

I can confirm that at least the main old ids `HMR2` and `Recon3D` are listed under `External databases`, so it should be good.
