### ISSUE TITLE
Inclusion of metabolite compartments in reaction equations

### ISSUE THREAD

**Issue by mihai-sysbio** [MetabolicAtlas/MetabolicAtlas#681]
I noticed that one of the recent updates to Metabolic Atlas involved the removal of metabolite compartment abbreviations (e.g., `[c]`, `[m]`, etc.) from reaction equations shown in the GEM browser. What was the reason behind this change? It was pretty convenient to have these, in particular for reactions involving more than one compartment.

Taking a simple example, the reactions for glucose transport between different compartments all look the same ([MAR05027](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR05027), [MAR07675](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR07675), [MAR05029](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR05029), etc.)

_Originally posted by @JonathanRob in https://github.com/MetabolicAtlas/MetabolicAtlas/discussions/679_

**Comment by mihai-sysbio** [comment]
> Should `[somecomp] `be after every item in the equations, i.e. reactants and products?

Indeed @inghylt, `[somecomp]` should follow after each metabolite (all of them, reactants and products). Moreover, these comps have been summarized at the end of a reactions, e.g.: 

> MAR08885 : glucose[somecomp] ⇒ glucose[somecomp] : ([somecomp]⇒[somecomp]) 

Naturally, the compartment summary will contain exactly one of each compartment on each side of the equation. That is, if two metabolites belong to the same `[somecomp]` as reactants, the compartment will be should just once in the left side of the equation summary.

**Comment by MalinAhlberg** [comment]
I started on this, just want to verify that I'm on the right track..? ![reaction.png](https://images.zenhubusercontent.com/5bd711b6c68d75301f4bd969/d1092c7c-2e36-4bf6-a7b4-8014d73aa987).
I reused / adapted code I found, are the compartments supposed to have a grey background?

**Comment by JonathanRob** [comment]
I recall in an older version of Metabolic Atlas that the compartment abbreviations had some sort of background/highlighting, but I can't remember if it was grey or something else.

Regarding the compartment summary after each reaction - I'm not sure how necessary that is. It seems to overcrowd things.

**Comment by mihai-sysbio** [comment]
Functionally great @MalinAhlberg !

I don't remember anything beyond what Jon just said. Wasn't there another issue for creating better looking _Related reactions_? Maybe selecting the background (or other UI improvements) can be part of that?

Just a note, the screenshot still contains the empty `(⇒)` at the end of the reaction.

**Comment by MalinAhlberg** [comment]
Yes, issue [private issue 116](https://app.zenhub.com/workspace/o/metabolicatlas/private-issues/issues/116) is about the formatting. I have removed the grey background.
I kept the compartment summary for now, please see the draft PR connected to this issue. Let me know if they should be removed!
