### ISSUE TITLE
Investigate inconsistent naming

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#683]
Reaction MAR03598 is named RE3181C in the left panel when clicking it at https://metabolicatlas.org/explore/Human-GEM/map-viewer/cholesterol_metabolism?dim=2d&panel=0&sel=MAR03598&search=MAR03598&coords=-3403.51,-481.9,1,0,0,500&g1=None&g2=None. This name, which seems to be an external id, is not shown in the title of the gem browser https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR03598

This behavior is shared with many surrounding reactions. Some reaction however, such as https://metabolicatlas.org/explore/Human-GEM/map-viewer/cholesterol_metabolism?dim=2d&panel=1&sel=MAR01570&search=MAR03598&coords=-3183.75,-817.19,0.9,0,0,500&g1=None&g2=None, displays it's MA id in the left panel as well as the title of the gembrowser

This is not a major issue but there seem to be some inconsistency in when we choose to display id or name in the map viewer and gem browser

**Comment by mihai-sysbio** [comment]
Some reactions and metabolites have names. These are preferred over the identifiers, as they are more meaningful. Since this is fetched directly from the model `yml`, I think the issue should be resolved in Human-GEM.
@Hao-Chalmers any thoughts on this:

**Comment by mihai-sysbio** [comment]
I believe the easiest way to advance with this issue is to suggest a fix in Human-GEM.

**Comment by inghylt** [comment]
@mihai-sysbio Do you want to do that? Or should I more or less copy paste what it here and create an issue?

**Comment by mihai-sysbio** [comment]
I've created https://github.com/SysBioChalmers/Human-GEM/issues/333 for this, so I am closing this issue here.

In general, if we know we are true to the data in Human-GEM, then all data-related issues should be reported there directly.
