### ISSUE TITLE
run automatic lint check

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#688]
As a developer, I would like to have lint checks run when pushing to GitHub, so that lint warnings are discovered and fixed asap

**Comment by mihai-sysbio** [comment]
@inghylt could you merge this into #604?

**Comment by inghylt** [comment]
Ah, right. I think it makes sense having them as two separate issues though? One for lint integration for editors and one for updating the github actions

**Comment by mihai-sysbio** [comment]
I feel it's easier to keep issues grouped before they reach the backlog refinement, where we might decide to split them differently.
