### ISSUE TITLE
Templates for issues and PR:s

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#696]
As a developer, I would like to have default template for issues and PR:s, so that I follow standards we have agreed upon and don't forget to add items such as print screens, how to recreate a problem, how to test, relative links etc.

These should be applied to all repositories (4).

**Comment by mihai-sysbio** [comment]
> _Please edit this to-do list of things to include_

Issues:
- [ ] user story (rarely not applicable)
- [ ] in case of a bug, a description of how to reproduce it, with screenshots/video

PRs:
- [ ] relative url that can be reused both for production and local testing
- [ ] screenshot of the fix

**Comment by MalinAhlberg** [comment]
Here are some additional suggestions:

Issues:
- [ ] in case of a bug, expected behaviour
- [ ] proposed solution
- [ ] definition of done

PRs:
- [ ] what type of change the PR does (bug fix, feature, documentation...)
- [ ] related issues and PRs
- [ ] list of changes made

As I think there might be discussions about which of these that should be used, I did not edit your post above @mihai-sysbio , but feel free to put them there if you approve of any of them.

**Comment by mihai-sysbio** [comment]
Thanks @MalinAhlberg, I added in your suggestions.

The only thing I left out is the _definition of that_. According to scrum, this is something that should be equally applied to all issues, so it should be defined outside each individual issue. It would be really nice to have this DoD defined in the team.

**Comment by inghylt** [comment]
Below follows a suggestion for a PR template:

### Related issue(s) and PR(s)
This PR closes [issue number] and relates to [issue or PR number]

### Description of the changes proposed in the pull request
#### Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] [Other]
 
#### List of changes made
Specify what changes have been made and why

#### Screenshot of the fix
Attach screenshot if relevant

### How to test
Please delete options that are not relevant
- A certain branch in another repo is needed
- A rebuild is needed to due new dependencies
- Relative url that can be reused both for production and local testing
- Instructions on how to test


### Further comments
If relevant, specify questions or related information

### Checklist
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

**Comment by mihai-sysbio** [comment]
From what I can see, the templates were added to a single repository. The issue body says:

> These should be applied to all repositories (4).

I hope it's okay to reopen the issue to find answer to the question: How do we go from here?

**Comment by mihai-sysbio** [comment]
From what I can see, the templates were added to a single repository. The issue body says:

> These should be applied to all repositories (4).

I hope it's okay to reopen the issue to find answer to the question: How do we go from here?

**Comment by mihai-sysbio** [comment]
I'd like to add another point to this if you agree @inghylt.

**Comment by inghylt** [comment]
Go ahead
