### ISSUE TITLE
fix typo in identifier page

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#698]
`detailes` should be `details`

Perhaps also remove the surrounding brackets?

![image.png](https://images.zenhubusercontent.com/5fc0f648ba2981921764866b/b69baad4-450e-43d4-bb12-852b9ac70483)

**Comment by mihai-sysbio** [comment]
Perhaps the `Visit ...` line could be moved at the first position in the text.
