### ISSUE TITLE
separate Neo4j queries in API that power GemSearch and GlobalSearch

### ISSUE THREAD

**Issue by mihai-sysbio** [MetabolicAtlas/MetabolicAtlas#705]
As a developer, I want the code for the search functionality to be maintainable, so that I can work with it easily.

_Originally reported [here](https://github.com/MetabolicAtlas/MetabolicAtlas/pull/700#issuecomment-930864502)_

**Comment by mihai-sysbio** [comment]
Potential benefits of different queries:
- speed of uncached search results
- differentiation of search results (eg "reason for match")

**Comment by mihai-sysbio** [comment]
Expected:
- to remove the code that is not necessary for GemSearch

**Comment by inghylt** [comment]
Good issue to write tests
