### ISSUE TITLE
Research on how to improve scores returned by neo4j

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#707]
As a developer, I would like the score returned by `db.index.fulltext.queryNodes` in api/src/neo4j/queries/search.js to be dependable, so that I can use it to rank the results returned.

Currently, there are two sorting functions used related to sorting results returned from _search in api/src/neo4j/queries/search.js, `sortResultsScore(a, b)` and `sortResultsSearchTerm(a, b, this.searchedTerm)`. It would be optimal to just having to sort based on score. However, in some cases neo4j returns a higher score for nodes which should not be ranked as high. An example:

Gene with id `ENSG00000132664` is connected to GeneState with name `POLR3F`and Gene with id `ENSG00000181222` is connected to GeneState with name `POLR2A`

![image.png](https://images.zenhubusercontent.com/5fc0f648ba2981921764866b/85f0d64a-5d5d-482d-abfe-d351ab29d9a9)![image.png](https://images.zenhubusercontent.com/5fc0f648ba2981921764866b/087bbc12-40cb-400a-9cef-cd3cfb426079)

Thus, when searching on `POLR3F` it would be expected for `ENSG00000132664` to receive a higher score than `ENSG00000181222`, but this is not the case
![image.png](https://images.zenhubusercontent.com/5fc0f648ba2981921764866b/ec824ba7-0c01-4ed6-890a-bde85fd4fb24)

This has the consequence that `sortResultsSearchTerm(a, b, this.searchedTerm)` has to be used as well as `sortResultsScore(a, b)` within the codebase. Just sorting based on `sortResultsSearchTerm(a, b, this.searchedTerm)` is not working either as this does not work well when sorting for matches such as external Ids (noticeable when using global search).

**Comment by inghylt** [comment]
Potential useful information
- There seem to be configuration option to when creating an index, see https://neo4j.com/docs/cypher-manual/3.5/schema/index/#schema-index-fulltext-search and https://neo4j.com/docs/cypher-manual/3.5/schema/index/#schema-index-fulltext-search-create-and-configure.

- When excluding the ~, i.e. not performing fuzzy search, you get a result you expect, see images below

```
CALL db.index.fulltext.queryNodes("fulltext", "POLR3F")
YIELD node, score
WITH node, score, LABELS(node) as labelList
OPTIONAL MATCH (node)-[:V1_8_0]-(parentNode:HumanGem)
WHERE node:HumanGem OR parentNode:HumanGem
WITH DISTINCT(
CASE
WHEN EXISTS(node.id) AND NOT EXISTS(node.externalId) THEN { id: node.id, labels: labelList, score: score } 
ELSE { id: parentNode.id, labels: LABELS(parentNode), score: score } 
END 
) as r 
WHERE any(r IN r.labels WHERE r="HumanGem")
RETURN r
```
![image.png](https://images.zenhubusercontent.com/5fc0f648ba2981921764866b/f3e4f2c3-0f9a-490e-bf0e-75491c334e7e)

**Comment by mihai-sysbio** [comment]
Some (minor) implementation is expected as part of this issue.

**Comment by e0** [comment]
Started looking into this issue. It looks like the search performs differently and better now. Matching up really well with the expected result as mentioned in the issue description actually.

This is what it looks like when searching for `POLR3FF`. As you can see in the results, `ENSG00000132664` is now the highest ranked result and `ENSG00000181222` is not included at all actually.

It may just be that the search was fixed/improved with a newer version of neo4j. I will still try some other searches though to see how the results look like.

![image.png](https://images.zenhubusercontent.com/60992f121594d60ae1132a98/bb0d06d4-4510-40d0-9999-2d29f122ddeb)

![image.png](https://images.zenhubusercontent.com/60992f121594d60ae1132a98/339f0430-f80c-4401-8a50-24bf56e80549)

**Comment by e0** [comment]
I have been trying some more searches and here is a few more examples of fuzzy search results. For both of these cases, the scoring of the search results look really good. For example, we see that the gene `UPRT` gets the highest score when searching for `uptr`. Similarly, the compartment `cytosol` gets ranked higher than all reactions and metabolites when searching for `ctyosl` and is a close second to only the gene `CTSL`, which feels very appropriate.

My conclusion for now is that the search results are more than good enough to close this issue. If we solve https://github.com/MetabolicAtlas/private-issues/issues/151 the results should make even more sense for the users. If anyone else has any input or want me to test some other types of searches, please let me know.

### `uptr`

![image.png](https://images.zenhubusercontent.com/60992f121594d60ae1132a98/ba60e076-2987-4875-90e3-7f4871a41259)

![image.png](https://images.zenhubusercontent.com/60992f121594d60ae1132a98/ab3b4875-8b60-44d6-aa35-23c1b981743b)

### `ctyosl`

![image.png](https://images.zenhubusercontent.com/60992f121594d60ae1132a98/9bad32b9-aabd-4274-8023-719698f882f2)

![image.png](https://images.zenhubusercontent.com/60992f121594d60ae1132a98/1a859d06-f9c9-4887-9351-09b42d6f5289)

**Comment by MalinAhlberg** [comment]
This does indeed look a lot better :clap: ! As it solves the originally reported problem, I think it can be closed, unless anyone else has more examples to try out.

**Comment by e0** [comment]
Thank you for testing @nanjiangshu. Just want to double check, can you post your neo4j version that’s show in the neo4j browser? As you can see in my screenshot including the scores, the correct one is still ranked first and that’s directly from the neo4j browser.

**Comment by e0** [comment]
Following the previous comment, I tried configuring the search index with different analyzers based on the output of `CALL db.index.fulltext.listAvailableAnalyzers()`. When using something like `keyword` or `cypher` instead of the default one, it actually would rank `ENSG00000132664` first when searching for `POLR3F`. It does however perform worse for some other searches, for example when searching for `uptr`, the gene `UPRT` does not get returned at all. It was not a super exhaustive comparison but it feels like none of the other analyzers perform better than the default one.

Also just to highlight the previous message again, I do think the rankings of (`POLR2A` + `POLR2;POLRA;RPB1`) > (`POLR3F + C34;RPC39;RPC6`) makes sense considering all of the fields that are being indexed, so I don't think there is any actual problems with how the scores are calculated.

The one thing that I thought could make a difference is if we could assign different weights to different fields, for example we would want to prioritize matching the id over the matching of synonyms. This does not appear to be supported by `neo4j` at the moment though.

For these reason, I still think it's appropriate to close the issue.

**Comment by inghylt** [comment]
Really nice discussions and work so far. Some thoughts and discoveries:

- "`It does however perform worse for some other searches, for example when searching for uptr, the gene UPRT does not get returned at all`", do we know it is not something related case sensitivity causing this behavior?

- I remember from when we [demoed the sorting based on score](https://github.com/MetabolicAtlas/docs/wiki/Review-scripts#sprint-october-sep-27---oct-25-2021) in October searching part of an id was also not returned properly, e.g. `03309s` does not lead to `MAM03309s` being returned. Not sure if this is something we should care about in this issue or at all but wanted to bring it up since it was discovered during the demo.

- I'm doing some experimenting and searching for `ENSG00000149` does not give any results at all but it should given that genes such as `ENSG00000149599` do exist. Same case for `Asparaginyl-Cysteinyl` which should result in `Asparaginyl-Cysteinyl-Cysteine` but it does not. Not sure if this is something we should care about either.

- It feels silly and sub optimal using two sorting functions as written in the issue description. However, I'm wondering if we do see negative performance for the actual users as a result of this since for example `POLR3F` is returned quickly and at the top of the listed matching genes in the frontend. So if we can't find a fix, this should not be a critical issue to solve. Would make sense to have the advisors "stress test" the search functionality after this sprint to see if it behaves as researchers (and not bug/clean code seeking developers : D) expect.

**Comment by e0** [comment]
Thank you so much for this response @inghylt! It's really nice to get your input especially since you done some prior research on this before.

> * > It does however perform worse for some other searches, for example when searching for uptr, the gene UPRT does not get returned at all
>   
>   
>   do we know it is not something related to case sensitivity causing this behavior?

This is indeed the case (no pun intended)! I didn't think about this possibility at all but after using one of the non-default analyzers, I did notice a difference in the search results. For example, searching for `UPTR` does rank the gene `UPRT` firs where as `uptr` doesn't. It seems that [the standard analyzer applies a `LowerCaseFilter`](https://stackoverflow.com/a/5513068) by default but this is not the case for some of the other analyzers. I didn't find any way through cypher to configure the analyzers on this level, for example we want to try to enable `LowerCaseFilter` for the `keyword` analyzer. It does seem possible to [register custom analyzers](https://community.neo4j.com/t/how-to-add-custom-lucene-analyzer/3923/2) though but we would need to write some Java. I wouldn't mind giving this a try if we want to pursue this.

---

> * I remember from when we [demoed the sorting based on score](https://github.com/MetabolicAtlas/docs/wiki/Review-scripts#sprint-october-sep-27---oct-25-2021) in October searching part of an id was also not returned properly, e.g. `03309s` does not lead to `MAM03309s` being returned. Not sure if this is something we should care about in this issue or at all but wanted to bring it up since it was discovered during the demo.
> * I'm doing some experimenting and searching for `ENSG00000149` does not give any results at all but it should given that genes such as `ENSG00000149599` do exist. Same case for `Asparaginyl-Cysteinyl` and `glyoxylate/dicarboxylate` which should result in `Asparaginyl-Cysteinyl-Cysteine` and `Tricarboxylic acid cycle and glyoxylate/dicarboxylate` respectively but it does not. Not sure if this is something we should care about either.

These partial search words not leading to any results are a bit concerning. I'm happy to look more into this too if we want to spend the effort on improving this aspect.

---

> * It feels silly and sub optimal using two sorting functions as written in the issue description. However, I'm wondering if we do see negative performance for the actual users as a result of this since for example `POLR3F` is returned quickly and at the top of the listed matching genes in the frontend. So if we can't find a fix, this should not be a critical issue to solve. Would make sense to have the advisors "stress test" the search functionality after this sprint to see if it behaves as researchers (and not bug/clean code seeking developers : D) expect.

I really like the idea of letting researchers test this. It would also be interesting to look through some of the search words used in HotJar videos.

**Comment by nanjiangshu** [comment]
Very nice discussions! I agree with @e0 that the current searching result is probably good enough unless users complain. 

However, I do not quite understand why an exact search will result in worse hit than a fuzzy search. I would imagine an exact search finds either nothing or something relevant. 

For example, for the term `Asparaginyl-Cysteinyl` @inghylt mentioned, https://metabolicatlas.org/ returns no result 
![Screenshot 2022-02-18 at 12.11.42.png](https://images.zenhubusercontent.com/58ca67a651aa2c305778a403/37f6dfdc-75fe-403b-a011-2815456ce04d)

but the exact match returned relevant hits (tested with the branch `test/exact-search-term `)
![Screenshot 2022-02-18 at 12.05.16.png](https://images.zenhubusercontent.com/58ca67a651aa2c305778a403/538516e0-b98d-412f-903b-266b71b0ef1c)

Unless it's proven that exact search will in many cases results in worse hits, I still preserve the solution to combine `exact search` + `fuzzy search`.  Of course, we can ignore this suggestion if we all agree that the time spend on this implementation does not worth the marginal benefit of the user experience improvement that might gain.

**Comment by nanjiangshu** [comment]
The scores are equal for the exact search and fuzzy search for the same hit. There are a few hits, such as the one you mentioned and e.g. `dd`, but I mean if the exact search returned a hit equal or better (maybe in most cases just equal) than the fuzzy search, there is a benefit here. If an exact searched will return worse hit than the fuzzy search, then we should drop the idea.

**Comment by e0** [comment]
Thanks again for the meeting earlier @nanjiangshu! Was really nice to get your input on this issue. Just wanted to post this screenshot in addition to the associated PR. As you can see the scoring for the first result is now a combination between the exact match and the fuzzy match, where as the second result has the same score as if only fuzzy match was used.

<img width="728" alt="image" src="https://user-images.githubusercontent.com/423498/154969393-748911b1-38bf-47ae-a324-27fd99a14b94.png">
