### ISSUE TITLE
Improve no results found message in global search

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#710]
As a user, I would like to have a clear message if my global search returns no hits, so that I am not confused

The image below displays the current message, which is a bit unclear

![image.png](https://images.zenhubusercontent.com/5fc0f648ba2981921764866b/96d3c773-7a9c-4aec-a3de-65d5c560747c)

**Comment by mihai-sysbio** [comment]
- [ ] an introductory sentence
- [ ] examples (urls) for each
