### ISSUE TITLE
Long title of beta oxidation subsystem map is cut off

### ISSUE THREAD

**Issue by JonathanRob** [MetabolicAtlas/MetabolicAtlas#726]
**Describe the bug**
The title on the 2D subsystem map for `Beta oxidation of unsaturated fatty acids (n-9) (mitochondrial)` is partially cut off at the beginning and end.

**To reproduce**
View 2D map for [Beta oxidation of unsaturated fatty acids (n-9) (mitochondrial)](https://metabolicatlas.org/explore/Human-GEM/map-viewer/beta_oxidation_of_unsaturated_fatty_acids_n_9_mitochondrial?dim=2d)

**Expected behavior**
Should be able to see the entire title on the map

**Comment by inghylt** [comment]
Make sure to look through all maps with long names so that the bug is not occurring there as well

**Comment by mihai-sysbio** [comment]
Concerns:
- check all maps
- double-check with the mobile layout

**Comment by mihai-sysbio** [comment]
From what I could see, the map title for this specific map was _always_ cut on the sides. Weird, but at least it was the only Human-GEM map where this happened.

I am retrospectively downgrading the issue weight to a `1`.
