### ISSUE TITLE
Window does not switch to global search after clicking "Search all integrated GEMs" on safari 

### ISSUE THREAD

**Issue by nanjiangshu** [MetabolicAtlas/MetabolicAtlas#729]
When doing the gem searching, the webpage does not switch to global search after clicking "Search all integrated GEMs" 

**To reproduce**
    1. Open the webpage
    2. Click the GemSearch and input `ENSG00000002587` with model as Fruitfly-GEM
    3. At the popup window, click "Search all integrated GEMs"
    4. The popup window disappears but it does not switch to the global search page rather stay on the current page.

**Additional context**
This bug was found on Safari but neither Firefox nor Chrome.

Related issue: https://app.zenhub.com/workspaces/metatlas-sprint-607745622d49260019ce115a/issues/metabolicatlas/private-issues/143

**Comment by mihai-sysbio** [comment]
Bug confirmed.

**Comment by e0** [comment]
Adjusted to a 2 based on difficulty and workload.

Possible PR composition improvement for the future: include specific browser setting recommendations, in this case it would have been helpful to mention the cache issue with Safari before requesting reviews.
