### ISSUE TITLE
Add option to remove highlighting in Interaction Partners

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#730]
**Please describe the feature**
As a user, I want to be able to remove highlighting in Interaction Partners, so that I can have the graph in it's original form

**Describe the solution you'd like**
An option to remove highlighting. A suggested solution could be to add `None` to the drop down available under Highlight

**Additional context**
See attached image how it currently looks for https://metabolicatlas.org/explore/Human-GEM/interaction-partners/ENSG00000112303
![image.png](https://images.zenhubusercontent.com/5fc0f648ba2981921764866b/8b900271-10c9-405d-8c9f-1efb5dbb4efe)

**Comment by mihai-sysbio** [comment]
This is already implemented, albeit in an unclear way, by the eraser in the upper section of interaction graph. I'm very tempted to mark this as a `won't fix` and hope to have a better Interaction Partners in the future (when the current libraries will be swapped out in favor of our own viewer).

**Comment by inghylt** [comment]
@mihai-sysbio I have referenced this issue in the refactoring issue so that it will be considered in the future. Feel free to mark/close this as you wish

**Comment by mihai-sysbio** [comment]
Excellent @inghylt ! I'll close this but also label as `wontfix`.
