### ISSUE TITLE
Reactions table not being populated for genes from quick search

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#734]
**Describe the bug**
The Reactions table is sometimes empty when clicking on a matching gene in quick search. When doing a hard refresh for the url, the reaction table is populated

**To reproduce**
1. Search for `EEF2` in Human-GEM the quick search, choose matching gene
2. Press the matching result
3. Look at the Reactions table
4. Hard refresh

**Expected behavior**
The reaction table always being populated

**Screenshots**
When the match first clicked, the reaction table is not populated
![image.png](https://images.zenhubusercontent.com/5fc0f648ba2981921764866b/03b294f4-fb3c-4758-b4f7-28b5bd14e22c)

**Comment by mihai-sysbio** [comment]
This looks like a nasty bug that we should address with priority (I thought we had fixed this).

**Comment by inghylt** [comment]
Happened again when clicking on result for ENSG00000141279

**Comment by mihai-sysbio** [comment]
> Happened again on dev when clicking on result for ENSG00000141279

 I can confirm this happened in `localhost`. Restarting the stack and using a private browser window make this bug reproducible, now with 2 distinct cases.

Great detective work @inghylt 💪🏻

**Comment by nanjiangshu** [comment]
Hi @mihai-sysbio and @inghylt. While working on this issue, I find the problem with GemSearch is more than what described here. If you do the following steps 
1. load the homepage
2. click the GemSearch and select Human-Gem and search for `EEF2`
3. Click the GemSearch again and select Mouse-Gem and search for `EEF2`
4. click the first hit for Gene 
5. one got the error message `Gene Eef2 not found in Human-GEM` while the address bar has already been updated to `explore/Mouse-GEM/gem-browser/gene/Eef2`

A screenshot is shown below 
![Screenshot 2021-11-12 at 10.09.54.png](https://images.zenhubusercontent.com/58ca67a651aa2c305778a403/608aaa50-6330-4dab-a30c-e3ce9d130e71)

I'll try to address this problem also in this issue, but if it adds more complexity, I guess it is better to create a new issue for that.
