### ISSUE TITLE
Add information about id update when using url for old id

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#735]
**Please describe the feature**
As a user, I want to get information regarding the update from old to new ID:s when using an url with an old id specified, so that I understand that I should use the quick search to find the new one

**Describe the solution you'd like**
When a user uses an url such as `https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/HMR_4083
`, he should get information that HMR_4083 has been updated to a new ID, or possibly redirected to the new ID

**Comment by mihai-sysbio** [comment]
Hmm I'm a bit torn about this issue - it sounds like it can be quite some work in implementing this. I'd like to hear more details to get a better impression of what fixing this would entail.

**Comment by mihai-sysbio** [comment]
After some thinking, it makes more sense to just document the change via #821 and close this issue.
