### ISSUE TITLE
Map search being in front of quick search

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#736]
**Describe the bug**
Map search is being placed in front of quick search in Firefox

**To reproduce**
1. Open Firefox
2. Visit `/explore/Fruitfly-GEM/map-viewer/peroxisome?dim=3d&panel=0&sel=MAM03419p&search=MAM03419p&coords=0,0,1,0,0,500&datatype=None&datasource=None&dataSet=None`
3. Try searching for something in quick search 

**Expected behavior**
Quick search being in front of the map search and not the other way around in all browsers

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5fc0f648ba2981921764866b/1f311cda-4f8f-4ed8-a06a-61089d5067e5)

**Comment by MalinAhlberg** [comment]
I spent some of my frontend-training time trying to understand this. I put down my conclusions here, in case they might help anyone else:
The `z-index` for the `searchInput` and the `canvasoption` box (the two that end up in front of the search result list) are set to `network.nodes.length + 1`.
The `searchResults` (that end up behind the others) have a parent, `navbar`, with a `z-index` set to 30 (although I'm not sure where this happen). So if there are more than 29 nodes, the search result section will end up behind the `searchInput`.
Setting the `z-index` of `navbar` to something high, eg
```
#navbar {
  z-index: 3000;
```
solves this, but I suspect that's not a very good solution.
For some reason, changing the `z-index` of `#searchResults` does not help
```
 #searchResults {
    z-index: 3000;
```
