### ISSUE TITLE
Can't access 3D map and inconsistent error message in Map Viewer

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#737]
**Describe the bug**
When going from non existing 2D map information to the gem browser and then pressing backwards, you can't press 3D to access the 3D map and another type of error message than standard is shown

**To reproduce**
1. Visit /explore/Fruitfly-GEM/gem-browser/reaction/MAR06749
2. Press `Phenylalanine, tyrosine and tryptophan biosynthesis 3D`
3. Press 2D
4. Press gem browser link (subsystem or reaction does not matter)
5. Press backwards button
6. Note the different error message and try pressing 3D button

**Expected behavior**
That pressing backwards button leads to a normally functioning map viewer where you can click 3D and it is the same error message as in step 3.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5fc0f648ba2981921764866b/31990972-27fb-41b8-9d73-bb560596ae99)

**Comment by mihai-sysbio** [comment]
Very good you spotted this! The way I understand it, it's a pure UI bug. While it does highlight a potential improvement in the code, the user is most likely not severely affected by this. I'm thus very tempted to postpone this.

**Comment by e0** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MetAtlas-Roadmap-60d96b68da0fb10019d26deb/issues/MetabolicAtlas/MetabolicAtlas/737?planning-poker) with ZenHub @inghylt @MalinAhlberg @mihai-sysbio
