### ISSUE TITLE
Fix hard coded version of The Human Protein Atlas

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#738]
**Describe the bug**
Currently the version for The Human Protein Atlas is hard coded to be v18, which is actually not what we use

**To reproduce**
Visit https://metabolicatlas.org/documentation and search for v18

**Expected behavior**
Either that we don't specify the version at all or parse it from data-files repo

**Screenshots**
![image.png](https://images.zenhubusercontent.com/5fc0f648ba2981921764866b/7da43955-3a14-4900-9f0f-d9d2b56ba04e)

**Others**
Please try to fix other potentially affected places.

**Comment by mihai-sysbio** [comment]
Please don't over-engineer this.

My suggestion would be to rephrase to a more generic phrasing that covers also the case when there will be multiple data sources:

> gene expression levels for the genes from databases such as <a>The Human Protein Atlas</a> can be loaded

**Comment by nanjiangshu** [comment]
May be good to add a reference to the file [DATA_OVERLAY.md](https://github.com/MetabolicAtlas/data-files/blob/main/DATA_OVERLAY.md) in the Data overlay section.
Related discussion: https://github.com/MetabolicAtlas/data-files/pull/24#issuecomment-966333715
