### ISSUE TITLE
Improve accessibility of `Report an issue`

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#739]
**Please describe the feature**
As a user, I want the styling of the Report an issue section to have better styling so that it is easier to read

**Acceptance criteria**
- [ ] the words should not have so much spacing in between them, i.e. should be left-aligned
- [ ] include a link to create a new GH issue (to the model repository)
- [ ] double check that email is as pre-filled as possible (e.g. model + component type + identifier + link to the page)
- [ ] would be great (not a requirement) if there are any ideas to propagate this to other parts outside of GEM Browser (but still linked to a model, not generically to MetAtlas)

**Additional context**
![image.png](https://images.zenhubusercontent.com/5fc0f648ba2981921764866b/17f393f6-ec7f-4e1b-9fa2-c928d4938f92)

**Comment by e0** [comment]
It would be nice if this can be accessed from any page and perhaps also add a link to GitHub (relevant docs page or just the new issue with "Bug Report" template preselected) about creating an issue.
