### ISSUE TITLE
broken subsystem links in related reactions table

### ISSUE THREAD

**Issue by MalinAhlberg** [MetabolicAtlas/MetabolicAtlas#741]
**Describe the bug**
The pages for some subsystem are very empty, see below. Not even the name of the subsystem is shown.
![subsystem](https://user-images.githubusercontent.com/1029190/139660420-f7096f59-aba3-4ce3-9a4e-2889b175a0d8.png)
The link to 3D viewer does lead anywhere interesting either.

**To reproduce**
Go to  https://metabolicatlas.org/explore/Yeast-GEM/gem-browser/subsystem/sce01110_biosynthesis_of_secondary_metabolites_sce01130_biosynthesis_of_antibiotics_sce00900_terpenoid_backbone_biosynthesis
More such links can be found when clicking around from  https://metabolicatlas.org/explore/Yeast-GEM/gem-browser/gene/YJL167W.

**Expected behavior**
At least the subsystem name should be presented, as in this example 

![subsystem2](https://user-images.githubusercontent.com/1029190/139660376-11e70ac3-cf13-4110-97e1-bc47c1fea401.png)

**Comment by mihai-sysbio** [comment]
There seem to be 2 problems here:
a) instead of having distinct links for the subsystems there is only one; I think @inghylt resolved a similar problem for the compartments
b) the subsystem page should display an error message instead of an empty page, since there is no such subsystem in the database

**Comment by nanjiangshu** [comment]
This issue will only fix the broken link. The feature that shows an error message when the subsystem url does not exist will be solved in another issue.

**Comment by mihai-sysbio** [comment]
There is an incomplete issue for the error message problem #800.
