### ISSUE TITLE
Remove legacy info in global search

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#744]
**Please describe the feature**
As a user, I want information regarding the global search to be up to date, so that I know that I can for example search for external id:s

**Describe the solution you'd like**
The information returned if there are not matches `"If this is an alias or external identifier, it means it is not present in any of the models."` should probably be replaced by `"If this is an alias it means it is not present in any of the models"` or similar. We might want to add new information to the Documentation as well

**Additional context**
![image.png](https://images.zenhubusercontent.com/5fc0f648ba2981921764866b/e1dcbd65-bf67-470b-a363-0cda84735271)Add any other context or screenshots about the feature request here.

**Comment by mihai-sysbio** [comment]
Replace "external identifiers" with "cross-references".
