### ISSUE TITLE
Convey dynamic vs static numbers in Comparison

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#749]
**Please describe the feature**
As a user, I want to have more information regarding the dynamic and static numbers so that I understand why the numbers differ

**Describe the solution you'd like**
Perhaps the current version of Human-GEM in the GEM Comparison and some kind of informative title of the static comparisons. E.g. `Static comparisons of Human-GEM 1.0.2`.

**Additional context**
`/gems/comparison?models=FruitflyGem-1.1.0&models=HumanGem-1.8.0`
![image.png](https://images.zenhubusercontent.com/5fc0f648ba2981921764866b/d94b1fc8-14c4-42b3-8a45-b8154d67d54b)

**Comment by mihai-sysbio** [comment]
- [ ] the upper section should include version numbers
- [ ] the lower section should be clearly labeled as _historical_ and linked to the publication and add a short paragraph about the generation of Human-GEM (summarized from the paper)

**Comment by mihai-sysbio** [comment]
From the article https://europepmc.org/article/MED/32209698#free-full-text have a look at the last two paragraphs of the _Introduction_ and also at Fig S1.
