### ISSUE TITLE
only one compartment listed in reaction description

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#754]
**Describe the bug**
The meta information for reactions only contains one compartment even if the reaction belong to multiple. 

**To reproduce**
1. Visit for example `/explore/Human-GEM/gem-browser/reaction/MAR08363`
2. Inspect the page
3. Search for "description"
4. Note that Cytosol is not listed as a compartment in the content of `<meta data-vue-meta>`:
`<meta data-vue-meta="1" property="og:description" data-vmid="og:description" content="The reaction MAR08363 in Human-GEM (version 1.8.0) can be found in the Nucleus compartment and the Transport reactions subsystem.">`

**Expected behavior**
The description should be containing all compartments, e.g. "The reaction MAR08363 in Human-GEM (version 1.8.0) can be found in the Cytosol and Nucleus compartments and the Transport reactions subsystem."

- [ ] make sure this works well for both compartments and subsystems

**Additional context**
The same case for reaction at `/explore/Human-GEM/gem-browser/reaction/MAR12870`.

**Comment by e0** [comment]
It seems that we have similar problems for metabolites, genes, and subsystems as well. Hope it's ok that I work on all of these in a fix PR.

**Comment by mihai-sysbio** [comment]
> It seems that we have similar problems for metabolites, genes, and subsystems as well. Hope it's ok that I work on all of these in a fix PR.

Really nice that you spotted this! A reminder if you think the estimate should be bumped up.

**Comment by e0** [comment]
Thanks for the reminder @mihai-sysbio. J usually like to wait until reviews and possible revisions before readjusting the estimate. If not much significant work is needed I would probably lower this to a 1.

**Comment by inghylt** [comment]
@e0 Adding this to the current sprint
