### ISSUE TITLE
Description text in the API is out of date

### ISSUE THREAD

**Issue by nanjiangshu** [MetabolicAtlas/MetabolicAtlas#759]
**Describe the bug**
The description of the text in the API `/api/v2` is out of date in some places. 

**Screenshots**
For example, for Interaction Partners, it is valid not only for gene but also metabolite

![Screenshot 2021-11-10 at 09.25.39.png](https://images.zenhubusercontent.com/58ca67a651aa2c305778a403/3aecfd2c-f4fd-4270-816c-2f958b2a6178)

**Additional context**
There could be places to be fixed at other places on the API page.

**Acceptance Criteria**
- [ ] Update `for a given gene` to `for a given gene or metabolite`
- [ ] Look for other related inconsistencies in the api description

**Comment by inghylt** [comment]
When working on this, might be nice to add a section regarding the new svg-thumbnail functionality
