### ISSUE TITLE
Quick search throws error when using charachter :

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#764]
**Describe the bug**

Using quick search and typing in `:` leads to an error

**Steps to reproduce**

Type for example `gene:` in quick search, note the error being reported

**Expected behavior**

That no error is reported but that the quick search works as normally

**Screenshots**

![image.png](https://images.zenhubusercontent.com/5fc0f648ba2981921764866b/3a926811-96e2-41a3-a7ee-1519ce07b9ca)

**Comment by e0** [comment]
Looks like this could be relevant: https://neo4j.com/docs/cypher-manual/current/clauses/where/#escaping-in-regular-expressions

**Comment by nanjiangshu** [comment]
Please also look for other characters that might causing the similar problem.

**Comment by nanjiangshu** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/MetAtlas-Roadmap-60d96b68da0fb10019d26deb/issues/MetabolicAtlas/MetabolicAtlas/764?planning-poker) with ZenHub @e0 @inghylt @MalinAhlberg

**Comment by inghylt** [comment]
`Tricarboxylic acid cycle and glyoxylate/dicarboxylate` leads to immediate error as well so slash seems to be a problem as well

**Comment by inghylt** [comment]
We should aim to solve #686 and #884 with this issue as well
