### ISSUE TITLE
Research on how to reach users/make it easier for users to reach us

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#767]
**Please describe the feature**

As a developer/maintainer of metabolic atlas, I want functionality for users so that I know what is valued by users of the site

As a user, I want a minimal effort way to suggest ideas or feedback so that metabolic atlas can contribute in the best way possible to my research

**Describe the solution you would like**

Some kind of feedback form or button? At least mentioned somewhere on the page, e.g. at the root page

**Comment by mihai-sysbio** [comment]
@inghylt could you please merge this issue with https://github.com/MetabolicAtlas/private-issues/issues/49 and close one of them?
