### ISSUE TITLE
Interaction Partners throws error message for majority of the models

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#770]
**Describe the bug**

- Interaction Partners throws error message for all models except Human-GEM and Yeast-GEM. Happens for both gene and metabolites.
- This is also the case when loading Data Overlay in Map viewer for all models except Human-GEM and Yeast-GEM
- Yeast-GEM have the mock data files in prod, these should be removed as well
- Suggested to only support uploading custom data for maps that don't have relevant data to overlay on the server (i.e. all models except Human-GEM currently?)

**Steps to reproduce**

1. Visit `/explore`
2. Click Worm-GEM, Mouse-GEM, Rat-GEM or Fruitfly-GEM
3. Press Interaction Partners
4. Press a random gene or metabolite
5. Note that an error message is thrown (if the network is not too large)

**Expected behavior**

That step 1-5 does not lead to an error message for any model
The data overlay component should not show the default data section if there are no data sources. User uploaded data should still be allowed.

**Screenshots**

![image.png](https://images.zenhubusercontent.com/5fc0f648ba2981921764866b/08f22d1a-5279-43b8-92a1-845688a009d3)

**Comment by mihai-sysbio** [comment]
I'm wondering if this is maybe connected with the model selection bug for which @nanjiangshu already has a PR?

**Comment by inghylt** [comment]
I think it is connected to the new Data Overlay functionality

```
[Vue warn]: Error in created hook (Promise/async): "Error: Request failed with status code 404"

found in

---> <DataOverlay> at src/components/explorer/mapViewer/DataOverlay.vue
       <InteractionPartners> at src/components/explorer/InteractionPartners.vue
         <App> at src/App.vue
           <Root>
```

**Comment by mihai-sysbio** [comment]
Hmm interesting.. I think we have at least one data set only for Human-GEM and Yeast-GEM, and nothing for the rest.

**Comment by inghylt** [comment]
During backlog refinement it was discovered that the error message also shows up in Map Viewer, e.g. https://metabolicatlas.org/explore/Zebrafish-GEM/map-viewer/heme_synthesis?dim=3d&panel=1&sel=MAM02804c&search=MAM02804c&coords=0,0,1,0,0,500&datatype=None&datasource=None&dataSet=None

We should also remove the mock data files for Yeast-GEM, see e.g. https://metabolicatlas.org/explore/Yeast-GEM/interaction-partners/YDR148C

**Comment by e0** [comment]
> Hmm interesting.. I think we have at least one data set only for Human-GEM and Yeast-GEM, and nothing for the rest.
> 
> Edit: adding a link to @e0's comment that the transcriptomics for Yeast-GEM should also be removed [MetabolicAtlas/data-files#23 (comment)](https://github.com/MetabolicAtlas/data-files/pull/23#issuecomment-968871283) .

Do we have any data that's ready to be added for Yeast-GEM?
