### ISSUE TITLE
Improve formatting for metabolites

### ISSUE THREAD

**Issue by MalinAhlberg** [MetabolicAtlas/MetabolicAtlas#773]
**Please describe the feature**

As a user, I want the information on metabolites to be formatted nicely so that it is easy to read.

**Describe the solution you would like**
Use eg. [chemicalFormula](https://github.com/MetabolicAtlas/MetabolicAtlas/blob/develop/frontend/src/helpers/chemical-formatters.js#L1) for `Name` and `Related metabolites`.

**Additional context**
![metabolite-formatting.png](https://images.zenhubusercontent.com/5bd711b6c68d75301f4bd969/a01de753-5799-4a42-87d5-dcd39eae5985)
compared to ![superscript.png](https://images.zenhubusercontent.com/5bd711b6c68d75301f4bd969/777b6bfa-62c9-4b95-824a-9821742a1b55)

**Comment by inghylt** [comment]
Since it seems to be common practice in the field to keep names not formatted, we close this issue
