### ISSUE TITLE
verify API data

### ISSUE THREAD

**Issue by mihai-sysbio** [MetabolicAtlas/MetabolicAtlas#780]
As a developer, I would like to run a test to validate a list of endpoints, so that I am confident that nothing important is broken when making changes to the codebase.

It is a part of this issue to figure out the important endpoints.
For model specific endpoints, only focus on the Human-GEM for now.

**Comment by inghylt** [comment]
I'm thinking about adding the CII badge to this one as there is an entire section regarding testing so that can probably be updated once this is done. Agree?

**Comment by mihai-sysbio** [comment]
Absolutely, great idea @inghylt

**Comment by inghylt** [comment]
https://bestpractices.coreinfrastructure.org/en/projects/4276

Cool. Above is the link to the CII badge, @e0 would you like to update it (and perhaps create new issues if needed) once the PR is merged?

**Comment by e0** [comment]
> https://bestpractices.coreinfrastructure.org/en/projects/4276
> 
> Cool. Above is the link to the CII badge, @e0 would you like to update it (and perhaps create new issues if needed) once the PR is merged?

Sounds good to have the badge I think. Is there any reason why we don't want to make this update in the same PR? Idea is that if the PR is rejected the badge would not update.

**Comment by e0** [comment]
Got a few rounds of great feedback on the PR for this issue. Adjusted the story points from 4 to 5.
