### ISSUE TITLE
Improve Interaction Partners not generated network message

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#782]
**Please describe the feature**

As a user, I want to have a better message in Interaction Partners so that I understand why a network has not been generated

**Describe the solution you would like**

When a component has more nodes associated than the limit(s) in frontend/src/components/explorer/InteractionPartners.vue the current message is "The query has returned many nodes.The network has not been generated." It would be nice with an explanation why the network has not been generated. For example, is it because of UX reasons or that the network can't handle it.

**Additional context**

Maybe we should explore if the limit(s) value(s) are still relevant

**Comment by mihai-sysbio** [comment]
In light of the work done in #1144, this problem has been circumvented so this issue is no longer valid.
