### ISSUE TITLE
potentially wrong model component counts

### ISSUE THREAD

**Issue by mihai-sysbio** [MetabolicAtlas/MetabolicAtlas#790]
**Describe the bug**
The reaction count displayed for Mouse-GEM on the Explore page is likely wrong. It was weird that it would be exactly like Human-GEM. The yml file in data-files has 13095 (not 13078) matches for ids that begin with `MAR` .

**Steps to reproduce**
Have a look at the `/explore` page.

**Expected behavior**
Counts that are identical to the ones in the source `yml`.

**Screenshots**

**Additional context**

I don’t know the extent of the issue with respect to other models and other counts.

**Comment by nanjiangshu** [comment]
If the problem is with the data import, that is the neo4j database is incorrectly imported, a new issue should be created to tackle this problem.

**Comment by nanjiangshu** [comment]
It seems the number of counts are correct. Below I listed the number of components for the seven GEMs parsed from the Yaml file. 

```
$ node index.js ../data-files
../data-files/integrated-models/Fruitfly-GEM Num reactions =  12056
../data-files/integrated-models/Fruitfly-GEM Num metabolites =  8132
../data-files/integrated-models/Fruitfly-GEM Num genes =  2050
../data-files/integrated-models/Human-GEM Num reactions =  13078
../data-files/integrated-models/Human-GEM Num metabolites =  8370
../data-files/integrated-models/Human-GEM Num genes =  3625
../data-files/integrated-models/Mouse-GEM Num reactions =  13078
../data-files/integrated-models/Mouse-GEM Num metabolites =  8382
../data-files/integrated-models/Mouse-GEM Num genes =  3513
../data-files/integrated-models/Rat-GEM Num reactions =  13086
../data-files/integrated-models/Rat-GEM Num metabolites =  8386
../data-files/integrated-models/Rat-GEM Num genes =  3502
../data-files/integrated-models/Worm-GEM Num reactions =  12187
../data-files/integrated-models/Worm-GEM Num metabolites =  8150
../data-files/integrated-models/Worm-GEM Num genes =  1952
../data-files/integrated-models/Yeast-GEM Num reactions =  4058
../data-files/integrated-models/Yeast-GEM Num metabolites =  2742
../data-files/integrated-models/Yeast-GEM Num genes =  1150
../data-files/integrated-models/Zebrafish-GEM Num reactions =  12940
../data-files/integrated-models/Zebrafish-GEM Num metabolites =  8362
../data-files/integrated-models/Zebrafish-GEM Num genes =  3232
```
The numbers are identical to that are listed on https://metabolicatlas.org/explore

**Comment by mihai-sysbio** [comment]
> The yml file in data-files has 13095 (not 13078) matches for ids that begin with `MAR` .

Indeed, I cannot find where the number 13095 comes from.

**Comment by mihai-sysbio** [comment]
@nanjiangshu just pinging you in case you want to re-assess the estimate.

**Comment by mihai-sysbio** [comment]
You're right @nanjiangshu . Initially I reported finding 13095 reactions for Mouse-GEM, but without knowing exactly what file I looked at, every other file I look at now has 13078 reactions. Sorry for not doing better issue reporting, and thanks for patiently investigating this. I think it's file to declare the issue as resolved.

**Comment by nanjiangshu** [comment]
That's all right @mihai-sysbio and it is great that these numbers are verified now.
