### ISSUE TITLE
missing error messages for invalid compartments and subsystems

### ISSUE THREAD

**Issue by mihai-sysbio** [MetabolicAtlas/MetabolicAtlas#800]
**Describe the bug**
Navigating to subsystems or compartments with bogus IDs does not produce any error message.

**Steps to reproduce**
Here's a random compartment ID: `/explore/Yeast-GEM/gem-browser/compartment/zdfgdfsg`. The behaviour is the same for `/explore/Yeast-GEM/gem-browser/subsystem/scdfgdfgabolism`.

**Expected behavior**
The same error message as for the other GEM Browser pages (gene/metabolite/reaction)

**Screenshots**
![image](https://user-images.githubusercontent.com/23480589/152796285-8777fb3b-fc08-40b6-90eb-7f9d584f45dc.png)

versus the expected

![image](https://user-images.githubusercontent.com/23480589/152980035-c9ae715c-20d1-41c4-953f-b7893b7e41e6.png)

**Additional context**

**Comment by mihai-sysbio** [comment]
@e0 mention this might be related to _not_ return the expected 404.

**Comment by e0** [comment]
The fix for this was quite straightforward and no frontend changes were needed, so the points are adjusted from 2 to 1.
