### ISSUE TITLE
Data overlay custom data upload giving errors despite proper format

### ISSUE THREAD

**Issue by JonathanRob** [MetabolicAtlas/MetabolicAtlas#806]
**Describe the bug**
This may have already been fixed in the development version since I know you have been working on the data overlay component, so remove this if that's the case.

When trying to upload a custom expression TSV file for the data overlay on the map, I get a few unexpected errors despite following the instructions in the [Documentation](https://metabolicatlas.org/documentation#Data-overlay).

I tried uploading an example TSV file (similar to that shown in the Documentation):

geneID | heart | liver
--- | --- | ---
ENSG00000177666 | 42 | 8701
ENSG00000175535 | 572 | 1
ENSG00000187021 | 3498 | 1768

I received the following errors:

```
Error: invalid TSV format, file must contain an ID column. First column should not be geneID
Error: 42 is not a number between 0 and 1
Error: 8701 is not a number between 0 and 1
Error: 572 is not a number between 0 and 1
Error: 3498 is not a number between 0 and 1
Error: 1768 is not a number between 0 and 1
```

**Steps to reproduce**
Uploading a TSV identical to the example provided in the [Data overlay documentation](https://metabolicatlas.org/documentation#Data-overlay) will yield similar errors.

**Expected behavior**
~First column should be allowed (expected?) to be gene IDs, and the expression values should be allowed outside the 0-1 range~
The Documentation should correctly describe the allowed values, and any requirements regarding the name of the first "ID" column.

**Comment by mihai-sysbio** [comment]
Thanks for the reporting @JonathanRob. Would it be possible to attach a (part of) the TSV that generated errors for you? That would make the error more reliable to reproduce, and also easier to validate that it was fixed.

**Comment by JonathanRob** [comment]
GitHub doesn't support uploading .tsv files (in comments), so I changed it to a .txt. I just copied the example expression data from the Documentation section (and added a 1 just so there wasn't a missing value).

[test_expression.txt](https://github.com/MetabolicAtlas/MetabolicAtlas/files/7725457/test_expression.txt)

**Comment by JonathanRob** [comment]
Ok, after checking your tests, it seems that the header for the first column **must** be `id` (case-sensitive), which addresses one of the issues. This is not mentioned in the Documentation.

The other errors are because the numbers are not between 0 and 1 - again a requirement not stated in the Documentation, and also a bit strange that users are expected to pre-normalize to the 0-1 range prior to uploading the data.

**Comment by mihai-sysbio** [comment]
I'm wondering if it's not a computer/browser dependent issue in choosing the correct separator `.` vs `,`.

**Comment by JonathanRob** [comment]
What separator are you referring to? The only separator used in the file I provided above is a tab.

**Comment by mihai-sysbio** [comment]
Sorry I meant the decimal separator. In some countries/regions the pi may be written as `3.14` vs `3,14`.

**Comment by JonathanRob** [comment]
Ok, I wouldn't expect that to be the problem here, since I didn't use decimals in that test file - only integers.

**Comment by mihai-sysbio** [comment]
Sorry I'm just confused here actually.
The original bug report mentions
> Error: 1.32807419 is not a number between 0 and 1
Error: 3.194549598 is not a number between 0 and 1

This is _entirely accurate_ (no problem with the decimal separator). The column name having to be `id` is indeed something we should look into.

**Comment by JonathanRob** [comment]
Yes, sorry for the confusion. Since you recommended uploading part of the TSV that created the error, I decided to use a simpler case - the TSV example from the Documentation section.

Here are all the errors that I get if I try to use the test document that I provided:
```
Error: invalid TSV format, file must contain an ID column. First column should not be geneID
Error: 42 is not a number between 0 and 1
Error: 8701 is not a number between 0 and 1
Error: 572 is not a number between 0 and 1
Error: 3498 is not a number between 0 and 1
Error: 1768 is not a number between 0 and 1
```

> Also, most values in the test file are greater than 1, which is again a problem.
Exactly - I should be allowed to upload values greater than 1, right? If not, then the Documentation needs to be updated.

**Comment by nanjiangshu** [comment]
I think the problem is that the [Documentation](https://metabolicatlas.org/documentation#Data-overlay) is out of date. According to https://github.com/MetabolicAtlas/data-files/blob/main/DATA_OVERLAY.md#data-source-file-requirements, we have specified the new format of the custom file. Also, the reason why the user should prepare data in the range of 0-1 is that 1). the data should be in the range of 0-1 and otherwise the coloring scheme in the Data overlay is meaningless and 2). we would not know how to convert the user data to the range of 0-1 without further information. 

As to the  error ```Error: 1.32807419 is not a number between 0 and 1```, which does look weird, maybe it is because the first column name is not `id` and then it trying to parse also the first column as number? Need double check for that part.

**Comment by JonathanRob** [comment]
@nanjiangshu Ok that clears up the issue with the values out of range - the Documentation is just out of date.

`Error: 1.32807419 is not a number between 0 and 1` makes perfect sense, the value is not between 0 and 1, so of course it will give an error. My confusion was due to the Documentation being inconsistent with the value restrictions.

**Comment by nanjiangshu** [comment]
Hi @JonathanRob , I tried to upload with the file you provided `test_expression.txt` but I did not get the same error message as you got. 
This is what I got 
```
Error: invalid TSV format, file must contain an ID column. First column should not be geneID
Error: 42 is not a number between 0 and 1
Error: 8701 is not a number between 0 and 1
Error: 572 is not a number between 0 and 1
Error: 3498 is not a number between 0 and 1
Error: 1768 is not a number between 0 and 1
```

**Comment by JonathanRob** [comment]
That's the exact error message I got as well. I will update my original post to avoid further confusion.

**Comment by nanjiangshu** [comment]
Is that OK that I create another issue called e.g. "update the documentation for Data overlay" and refer to this bug report?

**Comment by mihai-sysbio** [comment]
Now that it's clear this was about the Documentation, I found an identical issue already being lined up to be solved soon https://github.com/MetabolicAtlas/private-issues/issues/129 . For now, I'm highlighting the "duplication".
