### ISSUE TITLE
Improve the release procedure

### ISSUE THREAD

**Issue by nanjiangshu** [MetabolicAtlas/MetabolicAtlas#813]
**Please describe the feature**

As a developer, I want the release procedure to be clear and yet simple enough so that it will not bring unnecessary overhead.

**Describe the solution you would like**

A release procedure that is clearly defined and easy to implement.

**Additional context**

We may book a short meeting to discuss about it.

**Comment by MalinAhlberg** [comment]
- check if api version should be updated

**Comment by MalinAhlberg** [comment]
I found the release documentation to be very good. I made some minor changes:
- Added the section *Before you start*, about the API version and server preparations.
- Expanded the section on the description of the release (point `5.v`).

If you approve of the changes, I think this issue can be closed.

**Comment by inghylt** [comment]
I approve of the changes, nice additions! Also pleasing that the documentation is in such good shape that only minor changes were needed :+1:

**Comment by nanjiangshu** [comment]
Nice addition! I also approve it.

**Comment by mihai-sysbio** [comment]
I also approve of the changes, very nice follow-through @MalinAhlberg!
