### ISSUE TITLE
Broken link for gembrowser compartments

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#819]
**Describe the bug**

When visiting a compartment in the gem browser and clicking the link for "complete list in JSON format" you get an error as result

**Steps to reproduce**

1. Visit https://metabolicatlas.org/explore/Human-GEM/gem-browser/compartment/golgi_apparatus
2. Press "complete list in JSON format" in the sentence "The complete list in JSON format of reactions / metabolites / genes is available using our API"
3. Notice that "Cannot GET /api/v2/1_10_0/compartments/golgi_apparatus" is returned

This happens for other compartments as well

**Expected behavior**

That the users get a list of reactions / metabolites / genes in JSON format

**Screenshots**

![image.png](https://images.zenhubusercontent.com/5fc0f648ba2981921764866b/a3d0b01f-8779-45ce-b7e0-e5b5bc5e7f2d)

**Comment by inghylt** [comment]
Seems to be related to missing model name in url

**Comment by mihai-sysbio** [comment]
A working url https://metabolicatlas.org/api/v2/compartments/inner_mitochondria?full=true&model=HumanGem

**Comment by nanjiangshu** [comment]
It returned the same result with or without version number in the url 
https://metabolicatlas.org/api/v2/compartments/inner_mitochondria?full=true&model=HumanGem
https://metabolicatlas.org/api/v2/compartments/mitochondria?full=true&model=HumanGem&version=1_10_0
