### ISSUE TITLE
Choosen 3 gems in gem comparison leads to broken site

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#823]
**Describe the bug**

When comparing 3 gems, the website responds with "something went wrong". Even if you remove one of the gems and only compare two, the website is still just loading

**Steps to reproduce**

1. Visit https://metabolicatlas.org/gems/comparison
2. Choose a third gem, e.g. Mouse-GEM
3. Note that nothing is displayed and that a "Something went wrong is returned"
4. Remove one of the three gems
5. Note that nothing is returned

**Expected behavior**

That you are able to compare 3 gems without breaking the gem comparison

**Screenshots**

![image.png](https://images.zenhubusercontent.com/5fc0f648ba2981921764866b/8fe7f06b-9190-416f-a4ed-a63141424314)

**Comment by mihai-sysbio** [comment]
An increased timeout on `dev` doesn't seem to make a difference.

**Comment by inghylt** [comment]
https://github.com/MetabolicAtlas/docs/wiki/neo4j-parallelisation might help

**Comment by mihai-sysbio** [comment]
> Still, the search took almost a minute so I guess this is due to different timeout settings.

That may well be the root cause of the issue, since in production the timeout is much less than that.

https://github.com/MetabolicAtlas/MetabolicAtlas/blob/acc9478a7f827ae268fc68fed0b2708798f1fee5/nginx/prod.nginx.conf#L6
