### ISSUE TITLE
Broken ToC link in Documentation

### ISSUE THREAD

**Issue by JonathanRob** [MetabolicAtlas/MetabolicAtlas#833]
**Describe the bug**
Extremely minor, but happened upon it when investigating something else. On the [Documentation](https://metabolicatlas.org/documentation) page, clicking on the "Metabolite page" item in the table of contents on the left side of the screen does not jump to that section, whereas it works for all other sections.

**Steps to reproduce**
In [Documentation](https://metabolicatlas.org/documentation), click on "Metabolite page" in the left table of contents menu.

**Expected behavior**
Selecting this section in the table of contents should move the page down to that section (as is the case with the other sections).

**Comment by e0** [comment]
Thanks for reporting this @JonathanRob!
