### ISSUE TITLE
Deployment to the dev server is broken 

### ISSUE THREAD

**Issue by nanjiangshu** [MetabolicAtlas/MetabolicAtlas#840]
**Describe the bug**

Deployment to the dev server is broken due to a problem with yarn
**Steps to reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

The problem is original posted in the comment https://github.com/MetabolicAtlas/MetabolicAtlas/pull/825#issuecomment-1011957873

**Comment by mihai-sysbio** [comment]
After updating Docker on the `dev` machine, deploying worked without issues.

**Comment by nanjiangshu** [comment]
I can also confirm that deployment to the `dev` server is working now.

**Comment by mihai-sysbio** [comment]
I propose to close the issue, and re-open if/when necessary.

**Comment by mihai-sysbio** [comment]
Not a problem anymore, confirmed by @nanjiangshu
