### ISSUE TITLE
gene name does not fit in SVG map

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#846]
**Describe the bug**

Long gene names do not fit in their "box" in the svg map

**Steps to reproduce**

1. Visit `/explore/Human-GEM/map-viewer/beta_oxidation_of_even_chain_fatty_acids_mitochondrial?dim=2d`
2. Zoom in and note that `HSD17B10` overflows it's container

**Expected behavior**

That the names of genes does not overflow

**Screenshots**

![image.png](https://images.zenhubusercontent.com/5fc0f648ba2981921764866b/e3a98471-032e-42d2-a3cd-3ef04f541313)
**Additional context**

**Comment by mihai-sysbio** [comment]
Oh that's interesting this wasn't noticed before. However, I'm leaning towards a `won't fix` label for this issue, since there isn't a robust workflow to update the maps.

**Comment by inghylt** [comment]
Sounds good! Just wanted to raise it since I noticed it, but obv. it's a teeny tiny bug. Feel free to close the issue completely
