### ISSUE TITLE
DOCKER_CONTEXT incorrectly set with proj.sh  

### ISSUE THREAD

**Issue by nanjiangshu** [MetabolicAtlas/MetabolicAtlas#852]
**Describe the bug**

DOCKER_CONTEXT is not set correctly after deploying to the `dev` server.
The command `docker compose --env-file env-local.env`  does not reset the value of `DOCKER_CONTEXT` which is defined (and exported) in the file `env-local.env`.

**Steps to reproduce**

1. Deploy to the `dev` server with `deploy-stack dev`. (Note that `DOCKER_CONTEXT` is `met-dev` after deployment, while `CHOSEN_ENV` is reset to `env-local.env`)
2. Trying to turn down the local stack with `stop-stack`. However, it killed the remote stack despite the ENV file is `env-local.env`

**Expected behavior**

After deploying to the `dev` server, both the `CHOSEN_ENV` and `DOCKER_CONTEXT` should be reset to the local. 

**Screenshots**

**Acceptance criteria**
- [ ] demonstrate the use of correctly setting the Docker context by automatically running a `cleanup` command before the deployment, thus also keeping our VMs clean (so they don't run out of disk space)

**Additional context**

The buggy behavior is found on Linux. Not tested on Mac.

**Comment by nanjiangshu** [comment]
A quick solution would be to export `DOCKER_CONTEXT` in the function e.g. `stop-stack`.

On my linux machine I used these definitions
```bash
mastart(){
    export DOCKER_CONTEXT=default
    exec_cmd "docker compose --env-file \$CHOSEN_ENV -f docker-compose.yml -f docker-compose-nj.yml up neo4j frontend api nginx -d  && sudo     chown \$USER -R neo4j &&  chmod 644 neo4j/import/.keep"
}

mastop(){
    export DOCKER_CONTEXT=default
    exec_cmd "docker compose --env-file \$CHOSEN_ENV -f docker-compose.yml -f docker-compose-nj.yml down && sudo chown \$USER -R neo4j &&       chmod 644 neo4j/import/.keep"
}
maps(){
    export DOCKER_CONTEXT=default
    exec_cmd "docker compose --env-file \$CHOSEN_ENV -f docker-compose.yml -f docker-compose-nj.yml ps"
}
mapriv(){
    exec_cmd "sudo chown \$USER -R neo4j &&  chmod 644 neo4j/import/.keep"
}
```

Another problem is the usage of `docker ... kill` in the function `stop-stack`. I think `docker down` is a better option since `docker kill` will cause the problem that port binding not released.

**Comment by MalinAhlberg** [comment]
Verify that this is still a problem

**Comment by MalinAhlberg** [comment]
It is still a problem (:

**Comment by mihai-sysbio** [comment]
Same for me
