### ISSUE TITLE
Create (repurpose) MVP content for the new About page

### ISSUE THREAD

**Issue by nanjiangshu** [MetabolicAtlas/MetabolicAtlas#859]
**Please describe the feature**

As a developer, I want the content of the new About page is written so that it can be implemented into the web-page.

**Describe the solution you would like**

**Additional context**

The Google Doc for the content of the about page
https://docs.google.com/document/d/1wbP8fCPPCs8kgTmaAJe0QUnJIQ8pAgQKPJKql9qVZ3g/edit

**Comment by MalinAhlberg** [comment]
I'll make a start on this, but contributions from everyone else would be welcome :) !

**Comment by MalinAhlberg** [comment]
Since the content contains a lot of html, I found it easier to update the vue files directly. The current state can be seen by using `feat/about-content`. I put some comments and todos in the google doc.

**Comment by mihai-sysbio** [comment]
Having seen the work that has gone into this issue, I'd say it's more than 3.

**Comment by e0** [comment]
> Having seen the work that has gone into this issue, I'd say it's more than 3.

Yes, changed to a 5.
