### ISSUE TITLE
do not index dev server

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#860]
**Please describe the feature**

As a PO, I want the dev server to not be indexed so that it does not get indexed and displayed online
As a developer, I want to be able to deploy without having to comment away lines in the env-dev.env file

**Describe the solution you would like**

Replacing the current solution with something more robust, e.g. a user/pass solution

**Additional notes**
There might be another robot filter on Cloudfare in addition to the possibility of having a `robots.txt`, so I am expecting some research into this as well.

**Comment by mihai-sysbio** [comment]
As a PO, I also want to be able to share the link to the `dev` server to anyone without having to know their IP beforehand.

**Comment by MalinAhlberg** [comment]
If there are other solutions for not being indexed, is it ok to remove the ip filtering @mihai-sysbio ?

**Comment by e0** [comment]
More about robot meta tags: https://moz.com/learn/seo/robots-meta-directives

**Comment by mihai-sysbio** [comment]
@e0's suggested approach of blocking crawlers is good enough for me.

**Comment by inghylt** [comment]
@MalinAhlberg @mihai-sysbio  @nanjiangshu @e0 

> More about robot meta tags: https://moz.com/learn/seo/robots-meta-directives

Short and nice article if you want to read more about this

Robots.txt does not seem to be recommended ([1](https://developers.google.com/search/docs/crawling-indexing/robots/intro#:~:text=Warning%3A%20Don't%20use%20a,URL%20without%20visiting%20the%20page.), [2](https://moz.com/learn/seo/robots-meta-directives)). Same goes for using Canonical URLs ([1](https://webmasters.stackexchange.com/questions/102575/using-canonical-links-to-keep-a-site-out-of-google-search-results), [2](https://community.cloudflare.com/t/pages-preview-protect-from-search-index-crawlers/384545/4))

Seems like the best options are either

1. `<meta>` tag (added inside `<head></head>`)
2. X-robots-tag (added to the response header)

Seems like they are more or less equal in terms of result ([1](https://moz.com/learn/seo/robots-meta-directives), [2](https://developers.google.com/search/docs/crawling-indexing/block-indexing)). We can apply X-robots-tag by configuring [Transform Rules](https://community.cloudflare.com/t/how-to-non-index-domain-its-pages/407579/2) easily and flexible in Cloudflare.  We can create 10 rules in total and use `hostname`, `URI`, `Country` [etc.](https://developers.cloudflare.com/rules/transform/response-header-modification/reference/fields-functions/), `equals`, `contains` etc. (not saying that we need all of the options, just a fyi :smile_cat: ).  Applying the `<meta>` tag only for dev and not prod seems like the messier option of the two for me, honestly not sure how to go about that.

**Comment by mihai-sysbio** [comment]
Very nice research results @inghylt 🌟 

> my suggestion is to apply X-robots-tag in Cloudflare since it seems like the most straightforward solution. If you agree, we could try it out (maybe by using a temp dev without current filtering applied?) and then verify by using sites such as https://seositecheckup.com/tools/noindex-tag-test

Sounds great! I guess this can be applied to an entire subdomain, in our case `dev.metabolicatlas.org`

**Comment by MalinAhlberg** [comment]
Great research and nice linked articles! I agree that x-robot-tags sounds like the best option!

**Comment by nanjiangshu** [comment]
Great research. Seems an easy and proper solution. I vote for that.

**Comment by e0** [comment]
I like the suggestion of handling this in Cloudflare @inghylt!

The only downside of course is that if we do move away from Cloudflare, or have to temporarily disable it for whatever reason, then the dev server would get indexed again. Personally I'm fine with that risk atm so I still support your suggestion.

> Applying the `<meta>` tag only for dev and not prod seems like the messier option of the two for me, honestly not sure how to go about it in a non hacky way.

I think this could be achieved by having a new env var to distinguish the dev server from the production server. Then we could add the `meta` tag conditionally using this.

**Comment by inghylt** [comment]
>The only downside of course is that if we do move away from Cloudflare, or have to temporarily disable it for whatever reason, then the dev server would get indexed again. Personally I'm fine with that risk atm so I still support your suggestion.

@mihai-sysbio I think it's up to you to decide whether this is an acceptable risk or not

**Comment by mihai-sysbio** [comment]
> @mihai-sysbio I think it's up to you to decide whether this is an acceptable risk or not

totally acceptable!
