### ISSUE TITLE
make the Table of Contents component sticky

### ISSUE THREAD

**Issue by e0** [MetabolicAtlas/MetabolicAtlas#864]
**Please describe the feature**

As a user, I want the Table of Contents to stick to the top so that it does not disappear as I scroll down the web page.

**Describe the solution you would like**

Make sure that the Table of Contents (currently for the Documentation and About pages) is always visible even if the user scrolls to the bottom of a long page that surpasses the height of Table of Contents.

**Additional context**

Two things to keep in mind for implementation:
- The mobile layout is different (ToC at top, content at bottom) and it should not be sticky depending on how things are laid out.
- If the ToC is longer than the visible window height, it should be possible to reach the bottom of the ToC as well.
- For the active link, nested visualization should be added similarly to example below.

![image](https://user-images.githubusercontent.com/423498/153219250-92b37a79-b309-4d22-b1a9-864e1f077231.png)

**Comment by mihai-sysbio** [comment]
This was demoed in the previous sprint, so I am moving it accordingly.
