### ISSUE TITLE
Research to make shift from vue-cli to create-vue

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#867]
**Please describe the feature**

As a developer, I want to see if we should make use of `create-vue` so that we use a modern package with nice features

**Describe the solution you would like**

A conclusion whether if it makes sense to shift from `vue-cli` to `create-vue`, e.g. if it is fairly straightforward and supports what we need. [By glance](https://github.com/vuejs/create-vue/blob/main/template/base/package.json) it seems like it. This library [is what is recommended](https://github.com/vuejs/vue-cli/issues/6064#issuecomment-1016473985) over `vue-cli`and has no vulnerabilities when you run `pnpm audit`. It also make use of `vite` instead of `webpack` which @e0 said was a good thing if I am not mistaken?

**Additional context**

Seems like the maintainers of `vue-cli` are involved in this project and it is part of the `vuejs` organization

**Comment by mihai-sysbio** [comment]
Perhaps this issue would be superseded by the switch to Vue 3?

**Comment by e0** [comment]
I set the estimate to a 5 but this attached PR is definitely a much bigger issue outside of our usual scale
