### ISSUE TITLE
Unwanted whitespace before comma 

### ISSUE THREAD

**Issue by nanjiangshu** [MetabolicAtlas/MetabolicAtlas#870]
**Describe the bug**

Unwanted white space has been added before comma or point at the end of sentences, as highlighted by the screenshot. 

**Expected behavior**

Comma or point should directly follow the character before.

**Screenshots**

![Screenshot 2022-02-07 at 16.53.00.png](https://images.zenhubusercontent.com/58ca67a651aa2c305778a403/017c03b1-1789-4440-9198-3c4a7083d928)
**Additional context**

The problem should be caused by non-properly configured `linter`.

**Comment by inghylt** [comment]
Note that this behavior is not only present for links but also for bold text section

**Comment by mihai-sysbio** [comment]
This requires some research.
