### ISSUE TITLE
add images/logos to About sections

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#876]
**Please describe the feature**

As a user, I want pretty visual things to support the text so that get a better visual experience.

**Describe the solution you would like**

Adding logos or images where possible. For example, `/about/introduction `might have the Metabolic Atlas logo

**Additional context**

**Comment by mihai-sysbio** [comment]
This would also bring the design of the `About` page closer to the `Documentation`, where we already make use of logos.
