### ISSUE TITLE
FTP server is down

### ISSUE THREAD

**Issue by nanjiangshu** [MetabolicAtlas/MetabolicAtlas#878]
**Describe the bug**

The FTP server of metabolicatlas.org is not accessible. It results in a time out error when trying to connect.

**Steps to reproduce**

**Expected behavior**

The FTP server ftp.metabolicatlas.org should work as normal

**Screenshots**

**Additional context**

Related issue https://app.zenhub.com/workspaces/metatlas-sprint-607745622d49260019ce115a/issues/metabolicatlas/private-issues/155

**Comment by mihai-sysbio** [comment]
@inghylt suggested setting up a monitoring service

**Comment by mihai-sysbio** [comment]
Here's how to enable more logging for the FTP server https://github.com/stilliard/docker-pure-ftpd#logs

**Comment by mihai-sysbio** [comment]
Apparently there was a Cloudfare misconfiguration, with the `ftp.metabolicatlas.org` being _proxied_. Removing that setting enabled me to connect immediately, but then I don't know if this fix is permanent.

**Comment by nanjiangshu** [comment]
I was previously guessing it was caused by the mis-configuration in Cloudfare https://nbisweden.slack.com/archives/C01D13EKUV7/p1648036868713759?thread_ts=1648035145.590119&cid=C01D13EKUV7

Great that the problem is solved, at least for now.

**Comment by nanjiangshu** [comment]
It seems we already have an account for `statusflare` and integrated with Slack. Is that owned by @mihai-sysbio?

**Comment by nanjiangshu** [comment]
Thanks for reminding @inghylt. I will set up a notification on UptimeRobot for the FTP server and then we can close the issue.

**Comment by nanjiangshu** [comment]
An UptimeRobot account has been created for MetAtlas and registered at https://bitwarden.dckube.scilifelab.se
The notification has also been set up in the `met-atlas` slack channel.
