### ISSUE TITLE
research UX for global search

### ISSUE THREAD

**Issue by e0** [MetabolicAtlas/MetabolicAtlas#890]
**Please describe the feature**

As a user, I want to have better UX for the global search functionality so that I can easier understand and filter the search results.

**Describe the solution you would like**

This issue should involve a thorough evaluation of what the global search page should look like and how it should work.

Following are some current pain points and potential improvements. **Please note that this is just a sample of the issues and this issue should include researching and identifying other points of improvement.**

- The global search page currently consists of a tab layout that groups the search results by component type. This is essentially 5 different tables, each with their own pagination rules. It is not straightforward to the user that pagination parameters, for example page size, may not be persistent when switching tabs.
- To get to the global search page, one would need to start from the gem search in the navbar. Do we want to offer alternatives ways for users to get to this page? If we do, please include design mockups of how they should work.
- Evaluate if we want to include or exclude and data.

**Additional context**

Related issue and discussion: https://github.com/MetabolicAtlas/private-issues/issues/101#issuecomment-1048769649

**Comment by mihai-sysbio** [comment]
Adding here a follow-up from https://github.com/MetabolicAtlas/private-issues/issues/101#issuecomment-1054145417:

The filtering should allow `and` conditions, and also inactivate (grey out) search options that would lead to 0 results.

**Comment by inghylt** [comment]
Some filtering we would like to keep:

- Model
- Components (not necessarily by tabs, this requires though on what information to present)
- Compartment
- Subsystems?

Multi select is a possible strategy
Bulma or Bulma extension might have functionality we can use

https://vue-multiselect.js.org 
A possible feature we can use

**Comment by MalinAhlberg** [comment]
Related to the implementation of this: https://github.com/MetabolicAtlas/MetabolicAtlas/pull/887#issuecomment-1056697509

**Comment by e0** [comment]
I have done some research and made some early mockups of the important components and ideas. After the mockups there is some additional notes. I'm happy to provide more detailed mockups but would appreciate some input before dedicating more time to a certain direction.

## Layout

<img width="961" alt="image" src="https://user-images.githubusercontent.com/423498/157436822-b206dd3c-a090-4efd-bf7b-bec67c342ff6.png">

The filter area is intended to be expandable and collapsable on mobile devices. When expanded, it should take up the entire screen except the navbar.

## Filter

<img width="955" alt="image" src="https://user-images.githubusercontent.com/423498/157436924-afd75e87-c92f-4d35-a311-8ce1d4d5c65c.png">


There are three kinds of filters included in this mockup. 

1. Checkbox group: Ideal for multi-select of filters that have few options.
2. Text input: Ideal for fields such as name and formula.
3. Multi-select with search: Ideal for multi-select of filters that have many options.

Ideas for other types of filters. Not sure if these are something we want to implement. Let me know if that's the case and I can add mockups for them.

- Range slider: Ideal for component counts, such as reactions count for a subsystem.
- Component that handles lists of values, such as alternate names and synonyms. Perhaps this can be included in the Text input?
- Custom component for formula: Would be neat to be able to filter formula by included elements.
- Custom component for gene rule: No concrete idea for this yet. The gene rules could be complex and nested. Happy to discuss this in more details if there is interest.

## Search results

Three alternatives are included here. Is there anyone you prefer? We could even have all three views and add a toggle (button group) for the user to pick.

1. Search engine style. Should be mobile friendly without requiring much adaptation. Can fit a lot of info.
<img width="958" alt="image" src="https://user-images.githubusercontent.com/423498/157438725-ea02c3a3-2d41-469a-93aa-618133563ef9.png">

2. Table view. Similar to what we currently have. Certain fields, such as id and name, could be merged into a single column if it makes sense.
<img width="953" alt="image" src="https://user-images.githubusercontent.com/423498/157438756-e3405621-90f3-4a5a-bdb4-7ab93c438bff.png">

3. Random components style. Nice way to visualize different types of components.
<img width="958" alt="image" src="https://user-images.githubusercontent.com/423498/157438894-f716bc2b-9a74-4d34-a8b9-630bb98a6121.png">

## Inspiration

- http://ensembl.org
- https://www.uniprot.org
- http://prisjakt.nu

**Comment by inghylt** [comment]
Really nice work :star: I enjoy having the filters as a side bar, makes them much more straightforward to use.

- Personally, I feel like nr 2 is most similar to how other things look at the web page, i.e. enables a feeling of consistency. But we can probably achieve a feeling of consistency with 1. as well if we style it more similar to for example the gem search. I actually like nr 1 the most, feels like we can convey most information but still keep it straightforward. Not a big fan of 3. as it suggests randomness to me and the search results are not random.
- Formula is not part of the mock ups but I guess it will be included?
- > To get to the global search page, one would need to start from the gem search in the navbar. Do we want to offer alternatives ways for users to get to this page? If we do, please include design mockups of how they should work.

    I feel like this is something we should try to fix as well when working with this issue. Maybe `Search all integrated GEMs` or something could be added to the Explore tab?
- I think it makes sense to include the advisors in an early stage to see if they have any suggestions or feedback. Maybe we should spend time on this during the review next week? Maybe ask them to look at the mock ups in advance?

**Comment by e0** [comment]
Thanks for the feedback!

> * Personally, I feel like nr 2 is most similar to how other things look at the web page, i.e. enables a feeling of consistency. But we can probably achieve a feeling of consistency with 1. as well if we style it more similar to for example the gem search. I actually like nr 1 the most, feels like we can convey most information but still keep it straightforward. Not a big fan of 3. as it suggests randomness to me and the search results are not random.

Makes sense! 3 would mostly be as a fun to have thing. Agree that it's not very useful.

___

> * Formula is not part of the mock ups but I guess it will be included?

Yes, I have left out many fields and just wanted to focus on the different types of filters here. The full list I have is as of following:

- Checkbox group
  - models
  - component types
- Text match search
  - formula
  - name
  - id
  - Custom
    - formula: filter by included elements?
    - lists of values:
      - alternate names
      - synonyms
      - gene rule
- Multi-select with search
  - compartment
  - subsystem
- Range
  - metabolites (count)
  - genes (count)
  - reactions (count)
  - subsystems (count)

___

> * > To get to the global search page, one would need to start from the gem search in the navbar. Do we want to offer alternatives ways for users to get to this page? If we do, please include design mockups of how they should work.
>   
>   
>   I feel like this is something we should try to fix as well when working with this issue. Maybe `Search all integrated GEMs` or something could be added to the Explore tab?

Ah yea I completely forgot about this. Will try to give it some though. Thanks for the reminder!

___

> * I think it makes sense to include the advisors in an early stage to see if they have any suggestions or feedback. Maybe we should spend time on this during the review next week? Maybe ask them to look at the mock ups in advance?

I think that would be great. Maybe after this round of feedback I can create some slightly better looking mockups before checking with them?

**Comment by nanjiangshu** [comment]
Thanks @e0 for the excellent research work on the global search. I like this modern design of search filtering. For the side bar filtering, I agree with @inghylt that a checkbox for `All` is good. Maybe not the elongated name `Search all integrated GEMs` but just `All` under the section `Models`. A similar checkbox can also be provided for `Component Types` as well.

For the search result area. I prefer the table view. It gives a better overview of the result and easier to sort the items by clicking the header items.

**Comment by e0** [comment]
> Thanks @e0 for the excellent research work on the global search. I like this modern design of search filtering. For the side bar filtering, I agree with @inghylt that a checkbox for `All` is good. Maybe not the elongated name `Search all integrated GEMs` but just `All` under the section `Models`. A similar checkbox can also be provided for `Component Types` as well.

I think this is a bit different from what @inghylt mentioned. It makes a lot of sense though and I think it should be included for the checkbox group filters. Great suggestion!

___

> For the search result area. I prefer the table view. It gives a better overview of the result and easier to sort the items by clicking the header items.

Thanks for your input!

**Comment by MalinAhlberg** [comment]
Really nice job :star: !
First, a clarification: do the checkboxes model `AND`? And the multi-select `OR`?

I also like the table view, since I think it gives the best overview. But I can imagine cases where the two others would be useful too. If there's enough time, I think it would be very nice to be able to toggle between them!

Another minor thing: if the top of the filter area would align with the top of the search result, maybe it would be clearer that you first need to search for something, in order to get results?

**Comment by e0** [comment]
> Really nice job ⭐ ! First, a clarification: do the checkboxes model `AND`? And the multi-select `OR`?

Ah good question. I think in terms of SQL this is like having `OR` (`SELECT * FROM components WHERE model = 'Human GEM' OR model = 'Mouse GEM'`) for both of them. So checking `Human GEM` and `Mouse GEM` means any components from these two models. Similarly if two compartments are selected in the multi-select, it would mean any components from those two compartments.

___

> I also like the table view, since I think it gives the best overview. But I can imagine cases where the two others would be useful too. If there's enough time, I think it would be very nice to be able to toggle between them!

I also think it would be nice to have both! For implementation it is something we could divided into different issues as well so we can ship the redesign with just one of them completed.

___

> Another minor thing: if the top of the filter area would align with the top of the search result, maybe it would be clearer that you first need to search for something, in order to get results?

That's a really good idea! We could also make the filter area auto-collapsed if there is no search term or search results. Thanks for the feedback!

**Comment by e0** [comment]
Thanks again for all the feedback!

Here is another round of mockups. There are certain details that I have left out, such as the pagination for mobile layouts. I hope that the mockups here are enough for us to use for implementation and that the leftover details are trivial enough to implement without the mockups. Please still let me know if you would like me to add more details on anything. The goal here is to make sure that anyone in the dev team is comfortable with the state of the mockups before wrapping up this issue.

I have also created a few related issues that improve the findability of global search: #918 and #919.

## Default view (no searches)

This should look near identical as before. The filter sidebar (even the toggle as shown below) should not be visible.

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/423498/158403459-21b74476-043c-4084-ae7b-c29b5ca33ad7.png">

<img width="309" alt="image" src="https://user-images.githubusercontent.com/423498/158403503-3437fc12-9e5d-4517-a5e9-69f4c033cf6c.png">

## Filter sidebar update

Compared to the first iteration, the "All" checkbox and sidebar toggle buttons are added.

<img width="1129" alt="image" src="https://user-images.githubusercontent.com/423498/158403703-8e2a360a-454f-4d2c-9ebe-6a05cd5d88c8.png">

<img width="306" alt="image" src="https://user-images.githubusercontent.com/423498/158405573-93dee4b2-9de0-44f7-be79-f768de1e88a2.png">


## Mobile table layout

It seems like the consensus is that the table view for search results is still most ideal. In the future we could explore the other options as well as having a toggle for switch between different result views. For now the aim is to focus on the table view and make sure it looks good in different device width. Following is a suggestion for how the table could work on mobile devices.

<img width="817" alt="image" src="https://user-images.githubusercontent.com/423498/158405690-19b29f30-9d5e-4bd4-b4fc-c137c362f918.png">

One of the alternatives is to present each table row in a vertical section as mentioned in [this article](https://css-tricks.com/responsive-data-tables/). I did not include a mockup of this because we have certain table cells that could contain a lot of text. A TLDR image is included below if you want to see what this looks like:

![image](https://i0.wp.com/css-tricks.com/wp-content/uploads/2011/04/responsive-table-on-iphone-1.png?w=400&ssl=1)

**Comment by inghylt** [comment]
Really nice work! I think everything is clear and actionable to me except the mobile view, not really sure about what "All columns" would do or how the filtering would work there. Think it makes sense to talk about this live

**Comment by e0** [comment]
Ah yea I see now that it's not obvious at all from the screenshots. When the "All columns" is OFF, it should show just two columns. When it is ON, it should show all columns and the table should be horizontally scrollable.

For filtering on mobile, one should click the little filter icon next to the search input to display the filters, which should take up the whole screen as shown in the screenshot under "Filter sidebar update".

Happy to discuss this live to help clarify these and any other questions.

**Comment by mihai-sysbio** [comment]
Great stuff! I really like how detailed the UX spec is, it really straightens up the implementation work.

I'd like to follow-up on this thread:

> > * Personally, I feel like nr 2 is most similar to how other things look at the web page, i.e. enables a feeling of consistency. But we can probably achieve a feeling of consistency with 1. as well if we style it more similar to for example the gem search. I actually like nr 1 the most, feels like we can convey most information but still keep it straightforward. Not a big fan of 3. as it suggests randomness to me and the search results are not random.
> 
> Makes sense! 3 would mostly be as a fun to have thing. Agree that it's not very useful.

- we should not feel constrained by the current use of `vue-good-table`; in fact, this library is earmarked for removal in https://github.com/MetabolicAtlas/MetabolicAtlas/issues/890#issuecomment-1062916264 because of its size, but also because there's no Vue3 version still (if there will ever be)
- any progress with the layout of this search will also propagate to the GEM Repository (the styling is similar now, and it make sense to maintain the styling similarity in the future)

On a side-note, we have an [open issue for looking into Buefy](https://github.com/MetabolicAtlas/private-issues/issues/61). There is a lot of inspiration to gain from their [table](http://buefy.org/documentation/table) implementation. What I liked in particular was how the table switches to a card layout if the page is too narrow. I think there is a lot of value in using cards (thus layout 1), since they adapt well almost regardless of page width.

**Comment by e0** [comment]
> * we should not feel constrained by the current use of `vue-good-table`; in fact, this library is earmarked for removal in [research UX for global search #890 (comment)](https://github.com/MetabolicAtlas/MetabolicAtlas/issues/890#issuecomment-1062916264) because of its size, but also because there's no Vue3 version still (if there will ever be)

Good point! I was approaching this as a UX designer and specifically did not want to go into any technical specifications. Maybe we don't want to have this type of limit in scope for future research work? I do remember us discussing this before though. Did you mean to link the comment to something else @mihai-sysbio? I followed the comment link and didn't find any relevant info about `vue-good-table` there.

___
 
> On a side-note, we have an [open issue for looking into Buefy](https://github.com/MetabolicAtlas/private-issues/issues/61). There is a lot of inspiration to gain from their [table](http://buefy.org/documentation/table) implementation. What I liked in particular was how the table switches to a card layout if the page is too narrow. I think there is a lot of value in using cards (thus layout 1), since they adapt well almost regardless of page width.

Good recommendation. This sounds like the technique mentioned at the bottom of [this comment](https://github.com/MetabolicAtlas/MetabolicAtlas/issues/890#issuecomment-1068092834).

**Comment by inghylt** [comment]
@e0 What is required to close this before sprint review on Monday?

**Comment by e0** [comment]
Thanks for the reminder @inghylt. I actually completely forgot that this issue was still in review. I'm really happy with the feedback and mockup revisions. If you and @mihai-sysbio are clear about the points mentioned in [this](https://github.com/MetabolicAtlas/MetabolicAtlas/issues/890#issuecomment-1070886865) and [this](https://github.com/MetabolicAtlas/MetabolicAtlas/issues/890#issuecomment-1073742295) comment respectively, then I think we can close this issue.

**Comment by mihai-sysbio** [comment]
I had thumbed-up your response @e0, and I am very happy with the state of this research issue and consider it fully resolved.

**Comment by inghylt** [comment]
I also think this can be closed! Good job :+1:

**Comment by e0** [comment]
Thank you for the confirmations!
