### ISSUE TITLE
Wrong link to the API

### ISSUE THREAD

**Issue by e0** [MetabolicAtlas/MetabolicAtlas#893]
**Describe the bug**

In the `About -> Related resources` page, the link for `Access Metabolic Atlas programatically` leads to the not found page.

**Steps to reproduce**

1. Visit `/about/resources`.
2. Scroll to the bottom and click the `Access Metabolic Atlas programatically` link.

**Expected behavior**

The link should be functional and lead to either the documentation page's section about API or to the API page (swagger) directly.

**Additional context**

There seems to be a typo as well, `programatically` should be `programmatically` (double m).

**Comment by mihai-sysbio** [comment]
Likely related, so posting this here: https://metabolicatlas.org/api/ broken on `prod`, works on `dev`.
