### ISSUE TITLE
Explore dbms.lock.acquisition.timeout

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#903]
**Please describe the feature**

As a developer, I want to see if we should add `dbms.lock.acquisition.timeout` to our neo4j configuration so that it is configured properly.

**Describe the solution you would like**

A conclusion whether we should add it or not, and if so a new PR with that configuration added.

**Additional context**

First mentioned [in this comment](https://github.com/MetabolicAtlas/MetabolicAtlas/pull/900#pullrequestreview-903163879). Documentation available [here](https://neo4j.com/developer/kb/understanding-transaction-and-lock-timeouts/)

**Comment by perjo** [comment]
Well, the documentation (linked above) clearly states that 

> It’s highly recommended that when you set the transaction timeout that you set the lock acquisition timeout as well.

so this should not be much to hesitate about. Will add a `dbms.lock.acquisition.timeout`.
