### ISSUE TITLE
Update `/documentation#resources`

### ISSUE THREAD

**Issue by MalinAhlberg** [MetabolicAtlas/MetabolicAtlas#904]
**Please describe the feature**

As a user, I want the resources section on the Documentation page to be up to date so that I can easily find what I'm looking for.

**Describe the solution you would like**

A link to `/about/resources`.

**Additional context**

See https://github.com/MetabolicAtlas/MetabolicAtlas/pull/902#pullrequestreview-904290862

The outdated documentation is confusing for users.

**Comment by inghylt** [comment]
We could maybe also add an intro text to https://metabolicatlas.org/about/resources. Title "Related resources" followed by "Tools" does not really introduce where the different tools come from (are they all SysBio?)
