### ISSUE TITLE
add citation information

### ISSUE THREAD

**Issue by mihai-sysbio** [MetabolicAtlas/MetabolicAtlas#907]
**Please describe the feature**

As an evaluator, I want understand the published landscape so that make a more informed decision about this resource.

**Describe the solution you would like**

For each publication, embed (suggestion: vertical-style) widgets  from:
- [ ] [PlumX](https://plu.mx/w/a/4I6gbLeUnBOvu1lhCA68LhMTi3vW4GZqDXWpvhJnKf4)
- [ ] [Altmetric](https://api.altmetric.com/embeds.html)
- [ ] [scite.ai](https://scite.ai/badge)
- [ ] [dimensions.ai](https://badge.dimensions.ai/)

**Additional context**

[OpenAlex](http://openalex.org) has an API for citation count so that could be an option. Another option is something similar to the EuropePMC's [Citation and Impact section](https://europepmc.org/article/MED/32209698#impact).

At least one of the articles has no info on OpenCitations, so I'm proposing to skip it.

The widgets/links should attract less attention than the citation itself.

Check this looks good on mobile.

**Comment by inghylt** [comment]
#933 and #934 has been created based on discussions. Will close this issue and keep PR #926 dangling until we know whether or not the widgets comply with the privacy policy
