### ISSUE TITLE
Incomplete ngnix redirecting for /api

### ISSUE THREAD

**Issue by nanjiangshu** [MetabolicAtlas/MetabolicAtlas#911]
**Describe the bug**

The URL https://metabolicatlas.org/api/ returns an error `Cannot GET /api/`
while the URL https://metabolicatlas.org/api/v2/ is redirected correctly to https://metabolicatlas.org/api/v2/

**Expected behavior**

Both https://metabolicatlas.org/api and https://metabolicatlas.org/api/ should be redirected correctly to https://metabolicatlas.org/api/v2/

**Additional context**

Note that the current set up works well on the localhost, i.e. both http://localhost/api and http://localhost/api/ will be redirected to http://localhost/api/v2/. So it must be tested at least on the `dev` server and ideally also on the `prod` server.

**Acceptance criteria**
- [ ] the fix should work on the `dev` server

**Comment by mihai-sysbio** [comment]
Might be related to the last `/`.

**Comment by inghylt** [comment]
@MalinAhlberg Added this to the current sprint
