### ISSUE TITLE
Unexpected behaviour of the param `full` for the api endpoints `/compartments` 

### ISSUE THREAD

**Issue by nanjiangshu** [MetabolicAtlas/MetabolicAtlas#914]
**Describe the bug**

The API endpoint `/api/v2/compartments/` does not work as expected.

For example: 
The parameter `full` must be specified for the `compartments` API in order to retrieve all the metabolites, genes, reactions and subsystems contained by the given compartment. Without this parameter, i.e. the endpoint `/api/v2/compartments/golgi_apparatus?model=HumanGem`
does not return information of genes, reactions and metabolites.

However, how this parameter `full` should be set is unexpected.  
The following two endpoints return 
`/api/v2/compartments/golgi_apparatus?model=HumanGem&full=false`
`/api/v2/compartments/golgi_apparatus?model=HumanGem&full=true`
return the same result containing information of all metabolites, genes, reactions and subsystems. 

While
`/api/v2/compartments/golgi_apparatus?model=HumanGem&full` and
`/api/v2/compartments/golgi_apparatus?model=HumanGem`
return the same result but without information of genes, reactions and metabolites. 

**Steps to reproduce**

**Expected behavior**

The returned result should be meaningful depending on the value of the parameter `full`. 

The following cases should be considered: 
1. `/api/v2/compartments/golgi_apparatus?model=HumanGem&full=true`  
2. `/api/v2/compartments/golgi_apparatus?model=HumanGem&full=false` 
3. When the parameter `full` is not set, i.e. `/api/v2/compartments/golgi_apparatus?model=HumanGem`, what should be the default value
4. When the parameter `full` is set to something else than `true` or `false`, i.e. `/api/v2/compartments/golgi_apparatus?model=HumanGem&full=somethingelse`  

**Screenshots**

**Additional context**

**Comment by mihai-sysbio** [comment]
- [ ] when `full` is present, it should default to a value of `true`
- [ ] when `full` is not present, it should default to a value of `false`
- [ ] check that the definition of full is included in the API in swagger
