### ISSUE TITLE
research `scoped` css

### ISSUE THREAD

**Issue by mihai-sysbio** [MetabolicAtlas/MetabolicAtlas#917]
**Please describe the feature**

As a user, I want the interface to feel fast, so I don't get demotivated by using the website.
As a developer, I want to know what is technically the best choice when setting up styling for the project

**Describe the solution you would like**

Research should confirm if we need to remove all `scoped` CSS.

**Additional context**

The performance aspects might differ between Vue 2 and Vue 3.

**Comment by e0** [comment]
According to [the official documentation](https://vuejs.org/api/sfc-css-features.html#scoped-css), there is no specific `scoped` styles performance penalties. The important takeaway is that `class` and `id` selectors are faster than standard HTML element selectors such as `div` or `p`. The `scoped` css does not add any `class` or `id` so we should keep in mind to always use these selectors. I found several instances of this (standard HTML element selectors in scoped style blocks) and have added a PR to address them.

**Comment by mihai-sysbio** [comment]
> The important takeaway is that `class` and `id` selectors are faster than standard HTML element selectors such as `div` or `p`

Indeed, here's a direct link where this is [documented](https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors):

> Scoped styles do not eliminate the need for classes. Due to the way browsers render various CSS selectors, `p { color: red }` will be many times slower when scoped (i.e. when combined with an attribute selector). If you use classes or ids instead, such as in `.example { color: red }`, then you virtually eliminate that performance hit.
