### ISSUE TITLE
Improve discoverability of global search from gem search

### ISSUE THREAD

**Issue by e0** [MetabolicAtlas/MetabolicAtlas#918]
**Please describe the feature**

As a user, I want to find global search more conveniently from gem search so that I can easier discover the global search page.

**Acceptance Criteria**

- [ ] The changes are tested on multiple models and browsers
- [ ] The changes do not affect the deployment
- [ ] The changes do not reduce the performance

**Additional context**

- [ ] The current hint ("Limited to 50 results per type. Click here to search all integrated GEMs") could be made more obvious. Similar to the button for when no matches are found.
- [ ] Clicking "Enter/Return" on the keyboard should perform a global search with the current search term.

**Comment by mihai-sysbio** [comment]
Here's an example of how others deal with the same problem (gsmarena.com in this case):
<img width="338" alt="image" src="https://user-images.githubusercontent.com/23480589/159248929-5c4411dc-486f-4bf4-b189-e9f9fbd22221.png">
<img width="339" alt="image" src="https://user-images.githubusercontent.com/23480589/159248979-a1de48b1-89fb-4f3a-b451-1ddbeaa45080.png">

Once one starts typing, 2 different buttons appear.
