### ISSUE TITLE
Remove uneccesary space bettween links and dots

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#930]
**Describe the bug**

When visiting https://metabolicatlas.org/about/introduction, all links and bold text have a unnecessary space between the text and dots/commas.

**Steps to reproduce**

Visit https://metabolicatlas.org/about/introduction

**Expected behavior**

That there is no unnecessary space

**Screenshots**

![image.png](https://images.zenhubusercontent.com/5fc0f648ba2981921764866b/125124e0-4ce0-4c22-a106-dafa97bea4a3)

**Additional context**

This is probably due to some setting in the formatter

**Comment by mihai-sysbio** [comment]
Is this a duplicate of #870 ?

**Comment by nanjiangshu** [comment]
I think so.

**Comment by inghylt** [comment]
Ah sorry my bad, closing this then
