### ISSUE TITLE
Add additional previous contributors to the Team page

### ISSUE THREAD

**Issue by e0** [MetabolicAtlas/MetabolicAtlas#931]
**Please describe the feature**

As a database evaluator, I want get a picture of the workload involved in setting up this resource, so that I don't have to request this information by email.

**Acceptance Criteria**

- [ ] The changes are tested on multiple browsers
- [ ] The changes do not affect the deployment
- [ ] The changes do not reduce the performance

**Additional context**

This is a continuation of #905 that should add the following people to the "Previous Contributors" section under the "About -> Teams" page: Pierre-Etienne Cholley, Jorrit Boekel, Lena Hansson, and Natapol Pornputtapong.

**Comment by MalinAhlberg** [comment]
Also add Pelle as current conttributor

**Comment by mihai-sysbio** [comment]
I have reached out to all 3. As part of this card, please add their names with a placeholder-style picture and the name as `Firstname L.` (where `L.` is the initial of the last name). If/when they reply I will either update you here or create a new issue.

For Pelle, it would be easiest to follow the same setup as for the other NBISers.

**Comment by mihai-sysbio** [comment]
For Natapol, use: the LinkedIn image and link to the LinkedIn profile;  Orcid 0000-0002-3833-0537; GH username `natapol`.

**Comment by mihai-sysbio** [comment]
Lena Hansson also confirmed. If she specifies any details I will create a new issue.
