### ISSUE TITLE
Can't search by metabolite id

### ISSUE THREAD

**Issue by PkiwiBird** [MetabolicAtlas/MetabolicAtlas#936]
- When searching for metabolite id MAM02040c in the search bar of metabolic atlas with "Human-GEM" selected at the left gives no results, but it works fine when using reaction ids or the name of the metabolite (h2o).
![Capture_a](https://user-images.githubusercontent.com/8766764/159881889-fecb9a3a-4079-458c-8560-7dea45998b7d.PNG)
![Capture_b](https://user-images.githubusercontent.com/8766764/159881915-5aaa7c2c-c82b-47d0-9705-f38b35a95c89.PNG)
![Capture_c](https://user-images.githubusercontent.com/8766764/159881939-37bf1da9-34f0-45c2-abeb-3031e23bddc2.PNG)
![Capture_d](https://user-images.githubusercontent.com/8766764/159882349-57fc0056-ddac-4790-b69c-be6baceb7d81.PNG)

- Also, the compartment 's' in the metabolic atlas seems to be different from the external compartment in models, which is 'e'

**Comment by mihai-sysbio** [comment]
Thank you @PkiwiBird for reporting this. It's really surprising how the search is indeed broken for [MAM02040c](https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM02040c).

> * Also, the compartment 's' in the metabolic atlas seems to be different from the external compartment in models, which is 'e'

I believe that change occurred in the latest release of Human-GEM `1.11`. On Metabolic Atlas we are still using the previous `1.10`.

**Comment by inghylt** [comment]
@PkiwiBird Thanks for reporting this! Seems like commit 3b3b01e5388e2fce301f841f824e350a2ddc32f9 introduced the bug. Will try to fix this asap

**Comment by mihai-sysbio** [comment]
@PkiwiBird the issue has been fixed by @inghylt and is now deployed. Let us know if you encounter further issues.

**Comment by inghylt** [comment]
@e0 should also be mentioned, we made the significant discoveries together!

**Comment by mihai-sysbio** [comment]
> @e0 should also be mentioned, we made the significant discoveries together!

Sorry about that @e0! It was the PR author that got stuck in my head. Thanks for working with @inghylt on this.

**Comment by PkiwiBird** [comment]
> @PkiwiBird the issue has been fixed by @inghylt and is now deployed. Let us know if you encounter further issues. edit: Human-GEM was kept at the same version, `1.10`.

Everything is fine now. Thank you.
