### ISSUE TITLE
Update search result limit from 5 to 10

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#945]
**Please describe the feature**

As a user, I want to see all compartmentalized metabolites so that find what I'm looking for.

**Acceptance Criteria**

- [ ] Update the limit from 5 to 10
- [ ] The documentation is updated accordingly
- [ ] The changes are tested on multiple models and browsers
- [ ] Tests verifying the changes are added

**Additional context**

**Comment by MalinAhlberg** [comment]
Related: #916 (created after discussions after our review session in March)

**Comment by inghylt** [comment]
Ah didn't find #916 when creating this issue! Closing this one then since it's a duplicate
