### ISSUE TITLE
Collect data for the new GEMs repository UX

### ISSUE THREAD

**Issue by nanjiangshu** [MetabolicAtlas/MetabolicAtlas#954]
**Please describe the feature**

As a developer, I want the data to be collected from the GEMs repository releases so that the new GEMs repository UX can be developed and implemented.

Note that this is the first step of data collection which includes the data for 
* release data (version, date, link to github)
* references to the publication
* externalParentId

This can be scripted or manual (no requirements on this). However, there is a requirement to  _in the future_ merge these data with manually curated data.

**Acceptance Criteria**

- [x] the Dev documentation (wiki or readme) is updated accordingly
- [x] new data files added to the appropriate place

**Additional context**

This issue is related to #950 but not blocked by that issue.
Consider if testing is relevant.

**Comment by inghylt** [comment]
This issue stems from #929

**Comment by mihai-sysbio** [comment]
Inspiration https://github.com/MetabolicAtlas/standard-GEM-validation/blob/develop/runner.py

**Comment by nanjiangshu** [comment]
I find [PyGithub](https://github.com/PyGithub/PyGithub) is quite useful to retrieve Github data through the API.

**Comment by nanjiangshu** [comment]
I created [a python script](https://github.com/MetabolicAtlas/data-files/blob/feat/collect-release-data/utils/fetch_release_data.py) to fetch release data from the Github repos 
The preliminary result generate with by the script with the command 
```
./fetch_release_data.py > t1.json
```
can be found at http://pcons2.scilifelab.se/misc/download/t1.json

Here I define the ID as `{gem_name}-{version}`. The content of the output can be modified easily when the data format is finalized. 

I'm not quite sure how the reference should be placed. I was thinking the references should be bound to the release, not the model but I could not find it in the release information. I guess this should be set manually.

**Comment by nanjiangshu** [comment]
A requirement for adding `externalParentId` is added for this issue based on the discussion at https://nbisweden.slack.com/archives/C01D13EKUV7/p1651480217985409

**Comment by nanjiangshu** [comment]
yes. I will close it.
