### ISSUE TITLE
Support Apple M1 

### ISSUE THREAD

**Issue by perjo** [MetabolicAtlas/MetabolicAtlas#962]
**Please describe the feature**

As a user with a Mac M1 device, I want to be able to bootstrap the project so that I can get started.

**Acceptance Criteria**

- [x] Mac M1 users should be able to get started following the README file
- [x] The web page documentation is updated accordingly
- [x] The changes are tested on multiple models and browsers

**Additional context**
On a Mac M1 when running the `build-stack` command I get 

> => ERROR [metabolicatlas_neo4j internal] load metadata for docker.io/library/neo4j:4.2.11   

> failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:216c7dcd870a6d4a6e20b839fa802c30fdeb951a79d2b4d75e618f95e1c4ed0b: not found

After adding  `platform: linux/amd64` to the neo4j section of the  docker-compose.yml I can get past this but then the import.sh script hangs: 

>  => [metabolicatlas_neo4j 5/5] RUN ./import.sh                                                                                                                                                                4429.8s
 => => # Waiting for neo4j to start                                                                                                                                                                                  
 => => # Waiting for neo4j to start                                                                                                                                                                                  
 => => # Waiting for neo4j to start                                                                                                                                                                                  
 => => # Waiting for neo4j to start                                                                                                                                                                                  
 => => # Waiting for neo4j to start                                                                                                                                                                                  
 => => # Waiting for neo4j to start

**Comment by mihai-sysbio** [comment]
It looks like this could be solved with a Neo4j version bump https://github.com/neo4j/neo4j/issues/12692#issuecomment-995631957 . In the past we've had issues with `latest`, but it might make sense to reconsider this now that we have some tests.

**Comment by perjo** [comment]
Seems not to work after setting 

`FROM neo4j:4.4.6`

either. Getting 

 > [metabolicatlas_neo4j 5/5] RUN ./import.sh --verbose:
#0 11.09 Selecting JVM - Version:11.0.15+10, Name:OpenJDK 64-Bit Server VM, Vendor:Oracle Corporation
#0 19.42 Changed password for user 'neo4j'.
#0 25.90 Directories in use:
#0 25.91 home:         /var/lib/neo4j
#0 25.91 config:       /var/lib/neo4j/conf
#0 25.91 logs:         /var/lib/neo4j/logs
#0 25.91 plugins:      /var/lib/neo4j/plugins
#0 25.92 import:       /var/lib/neo4j/import
#0 25.92 data:         /var/lib/neo4j/data
#0 25.92 certificates: /var/lib/neo4j/certificates
#0 25.92 licenses:     /var/lib/neo4j/licenses
#0 25.92 run:          /var/lib/neo4j/run
#0 25.92 Starting Neo4j.
#0 26.09 Unable to start. See user log for details.
#0 26.09 Failure to create the user log file /var/lib/neo4j/logs/neo4j.log due to /var/lib/neo4j/logs
#0 26.09 Run with '--verbose' for a more detailed error message.

**Comment by mihai-sysbio** [comment]
Right, so Neo4j does (attempt to) start but then exists. Have you had a chance to look at the the detailed Neo4j log?

**Comment by inghylt** [comment]
@perjo Assigning this to the current sprint

**Comment by mihai-sysbio** [comment]
Suggested time-box of 4h.

**Comment by e0** [comment]
I looked a bit into this now. Indeed I get the same problem as @perjo reported with version `4.4.9`. I didn't find any solutions after searching a bit.

Then I tried to comment out the lines starting from `neo4j start` in the `import.sh` file. Just to see if the rest of the build can complete. This went well actually! `start-stack` ran fine as well so after everything started I could run the following to manually add the `neo4j` data.

```bash
docker exec -it CONTAINER_ID-shell -u NEO4J_USERNAME -p NEO4J_PASSWORD --format plain --file import/import.cypher
```

After that it seems like everything works fine locally. So as long as you don't need to deploy, this should be a good enough solution to work with on your Mac. This issue should still be left open though until we can figure out the import step too. @perjo please give this a try and let me know if you run into any problems.

**Comment by mihai-sysbio** [comment]
It seems that now Docker has official images for `arm64`, could anyone try one of those images (that are now official) https://hub.docker.com/r/arm64v8/neo4j/ ?

**Comment by e0** [comment]
@mihai-sysbio I think `arm64` is supported by default now since `4.4`. I didn't have to specify anything after `4.4.9` when I got things to work now. The only thing that doesn't work is the `import.sh` stuff during `build-stack` but I think that might be some permission related stuff rather than problems with their images.

**Comment by e0** [comment]
I think the build issue is solved now! The [key line](https://github.com/MetabolicAtlas/MetabolicAtlas/pull/1099/files#diff-6d164ff713c29e2e2f1c534a44b68acde992cbc46ca58e0ca1db7bcda3dd0486R9) is to simply create the log file if it doesn't exist.

**Comment by e0** [comment]
Since multiple people have spent time on this issue I'm marking it as a `3`. If I was to only count the time I spent on it yesterday I would probably mark it as a `1` instead.
