### ISSUE TITLE
Implement new branching workflow

### ISSUE THREAD

**Issue by inghylt** [MetabolicAtlas/MetabolicAtlas#963]
**Please describe the feature**

As a developer, I want to remove the dev branch and only have a main one so that the workflow is simplified.

**Acceptance Criteria**

- [x] Update CONTRIBUTING.md on how we do branching
- [x] Update wiki documentation on how we do releasing
- [x] Remove dev branch

**Additional context**

This issue implements the suggestion from #915

**Comment by inghylt** [comment]
https://github.com/MetabolicAtlas/docs/wiki/Release-guidelines

@MalinAhlberg @mihai-sysbio @nanjiangshu @perjo @shan please have a look at the new instructions on how to do releasing. I have kept the old ones under title `Old version` for comparison, will remove when we reach a conclusion for the new version

**Comment by mihai-sysbio** [comment]
Brilliant improvements 🌟 my personal preference would be to move all the text-related guidelines like British-English to another place, but I'm fine with doing that later.

**Comment by MalinAhlberg** [comment]
Very good job, the instructions are much clearer now!

But what about "mention the sprint theme name"? Was that deleted on purpose?
Also, for the sake of completeness: 
> 4. Merge when approved **and delete the branch**

**Comment by inghylt** [comment]
> But what about "mention the sprint theme name"? Was that deleted on purpose?

Deleted on purpose as we said that we will not necessarily make a release after each sprint but when we feel the need to make a new release, i.e. there will not always be a sprint theme to mention.

> Merge when approved and delete the branch
Nice, updated with your suggestion

**Comment by e0** [comment]
Just read the Release guidelines now. Excellent job @inghylt! It looks well formatted and clear. I really like the change of creating a single branch as opposed to one for the new version and one for the news.

I have a minor comment that only became relevant this week. The `2` should be changed (to perhaps a `3`?) here.

> On ZenHub, assign the sprint and set the estimate to `2`.

**Comment by inghylt** [comment]
Nice that you caught that @shan-chalmers! I've updated the documentation with a `3` instead of `2`.

Closing this issue now since the wiki seems to have enough approvals and the other parts of the Acceptance Criteria are completed as well
