### ISSUE TITLE
Find and remove unwanted version-"v"s

### ISSUE THREAD

**Issue by MalinAhlberg** [MetabolicAtlas/MetabolicAtlas#966]
**Please describe the feature**

As a user, I want the version names for the GEMs to be eg "1.0.1" rather than "v1.0.1", on all pages and in all documentation (visible to the user), so that  things are consistent.

**Acceptance Criteria**

- [ ] No instances of versions-"v" for GEMs are shown on the webpage

**Additional context**

See https://github.com/MetabolicAtlas/MetabolicAtlas/pull/964#discussion_r859358460.

It might be the case that "-" are also presented in some unwanted locations.

**Comment by e0** [comment]
Instance of when `-` is used. ![image.png](https://images.zenhubusercontent.com/60992f121594d60ae1132a98/23d6df92-77dd-4d0c-83a2-70349105f24a)
