### ISSUE TITLE
inconsistent behaviour when moving between 2d and 3d

### ISSUE THREAD

**Issue by MalinAhlberg** [MetabolicAtlas/MetabolicAtlas#971]
**Describe the bug**
Switching between 2D and 3D is not working as expected. The behavior depends on which state you're in when you enter the page / reload the page. 

**Steps to reproduce**

Example:
- Go to the MapViewer and select Cystol, part 1
- Change to 3D
- Reload the page
- Change back to 2D
You will  see an empty map.

**Expected behavior**

- [ ] Repeating steps above will result in that the correct map is shown
- [ ] Tests verifying the fix are added

**Screenshots**

![emptymap.png](https://images.zenhubusercontent.com/5bd711b6c68d75301f4bd969/b333f122-ca14-455a-bc6c-36872b4df4db)

**Additional context**

This is related to #837.
The problem seems to be that [`this.$route.query.dim`](https://github.com/MetabolicAtlas/MetabolicAtlas/blob/develop/frontend/src/components/explorer/MapViewer.vue#L281) is not updated when switching to another dimension, it will always keep the value from when the page is first loaded (or reloaded).

**Comment by nanjiangshu** [comment]
I think this problem is not just caused by switching between 2D/3D, but switching generated a non functioning URL. I guess it may related to bad coordinates or zooming. The following URL 

https://metabolicatlas.org/explore/Human-GEM/map-viewer/cytosol_2?dim=2d&panel=0&sel=&search=&coords=-20278.48,-102710.34,0.04,0,0,500&datatype=None&datasource=None&dataSet=None

results in a constant empty 2D map viewer.

**Comment by e0** [comment]
Didn't get too far with this. Deprioritizing it for now to focus on enzyme issues.

**Comment by mihai-sysbio** [comment]
Confirmed: still a bug after the upgrade to Vue 3 (which makes sense).

**Comment by MalinAhlberg** [comment]
This happens to me locally and on the dev server (not on the prod server). It might be related, but seems to have more to do with the coordinates getting messed up:
- Go to the map viewer and select *Acyl-CoA Hydrolysis*
- Change to 3D
- Reload the page
- Change to map *Alkaloids biosynthesis*
- Change to 2D
- The map is shown really quick and then disappears again
