### ISSUE TITLE
indicator when data overlay is applied

### ISSUE THREAD

**Issue by MalinAhlberg** [MetabolicAtlas/MetabolicAtlas#975]
**Please describe the feature**

As a user, I want an indication when data overlay is applied so that I understand what is shown on the map.

**Acceptance Criteria**

- [ ] there are bonus points if the implementation is applied to the Interaction Partners (not a hard requirement)
- [ ] An indicator is shown when overlay is applied:
  - one idea is the button group in the map viewer area (same for 2D/3D)
- [ ] The changes are in alignment with the privacy policy
- [ ] The changes are tested on multiple models and browsers
- [ ] The changes do not affect the deployment
- [ ] The changes do not reduce the performance

**Additional context**

 [Example](https://github.com/CreativeBulma/bulma-badge/). See also #935

**Comment by pdmnyberg** [comment]
@mihai-sysbio I think it might be helpful if you pointed out what is missing or deviating from the acceptance criteria.
