### ISSUE TITLE
improve search results

### ISSUE THREAD

**Issue by MalinAhlberg** [MetabolicAtlas/MetabolicAtlas#978]
**Please describe the feature**

As a user, I want relevant search results so that I find what I'm looking for.

This is a left-over from #896:

- When searching for fatty the top result should not be the gene FASTK as top result

**Acceptance Criteria**

- [ ] When searching for fatty the top result should not be the gene FASTK as top result
- [ ] The changes are tested on multiple models and browsers
- [ ] Tests verifying the changes are added
- [ ] The changes do not affect the deployment
- [ ] The changes do not reduce the performance

**Additional context**

As this turned out to be unrelated to the other part of issue #896 (PR #965), it was moved here.

**Comment by mihai-sysbio** [comment]
To me, this issue may be closed - any thoughts?

**Comment by nanjiangshu** [comment]
I think the result of the current quick search looks good. However, people might be a bit confused that why there is no exact match of common key words such as `fatty` or `transporter` in the result list. It might be good to show the `Alternate name` in the result table, see the following chart as an example. 
<img width="1091" alt="Screenshot 2022-08-22 at 09 31 07" src="https://user-images.githubusercontent.com/5833722/185866609-a7ebdf53-59ad-46e5-b982-0c1ab4bc302d.png">

**Comment by mihai-sysbio** [comment]
I'm on the same page with @nanjiangshu, and I know that improvements are to be implemented in #895.

**Comment by nanjiangshu** [comment]
> I'm on the same page with @nanjiangshu, and I know that improvements are to be implemented in #895.

Great! Then I think this issue can be closed.

**Comment by inghylt** [comment]
@nanjiangshu Should we estimate this with 1? Because I guess you spent some time on it?
