### ISSUE TITLE
Refactor code for fetching and handling GEMs

### ISSUE THREAD

**Issue by e0** [MetabolicAtlas/MetabolicAtlas#991]
**Please describe the feature**

As a developer, I want to refactor the code for fetching and handling GEMs so that the code is more consistent with how Vuex modules and API fetching works for other instances.

**Acceptance Criteria**

- [ ] In `frontend/src/api/gems.js`, the `fetchGems` function includes some mapping logic. An argument could be made that the code for mapping should be included in the corresponding `frontend/src/store/modules/gem.js` instead. Consider if this should be done and if so update the files.
- [ ] The changes are in alignment with the privacy policy
- [ ] The changes are tested on multiple models and browsers
- [ ] The API response is the same as before
- [ ] The changes do not affect the deployment
- [ ] The changes do not reduce the performance

**Additional context**

**Comment by inghylt** [comment]
Seems like `frontend/src/components/explorer/InteractionPartners.vue` in commit 890235ed82cd32fc6d83a8f39de69164598badd8 had a `TODO` about Vuex as well, should it be included in this issue?

**Comment by inghylt** [comment]
Ah sorry I got it mixed up yesterday, thank for pointing out the obvious @e0
