### ISSUE TITLE
Rename the API endpoint  "/external-db/:dbName/:externalId"

### ISSUE THREAD

**Issue by nanjiangshu** [MetabolicAtlas/MetabolicAtlas#995]
**Please describe the feature**

As a developer, I want the API endpoint `/external-db/:dbName/:externalId` to be renamed so that it reflects its actual meaning. 

This API is currently used to retrieve both the cross references such as `/api/v2/external-db/BiGG/PPNCL3` and the MetIDs such as `/api/v2/external-db/MetabolicAtlas/MAM10036c`

**Acceptance Criteria**

- [x] The old endpoint is replaced by a more meaningful one (suggested that `external-db` is replaced by `identifier` but the rest of the URL is kept)
- [x] Update backend and db to be consistent with the naming
- [x] Update swagger if needed
- [x] Update tests if needed

**Additional context**

Related Issue #747
Related comment https://github.com/MetabolicAtlas/MetabolicAtlas/pull/989#issuecomment-1125400249
Currently in frontend we make use of `identifier`, see https://metabolicatlas.org/identifier/MetabolicAtlas/MAM02877e and https://metabolicatlas.org/identifier/HMR%202.0/HMR_5934

**Comment by e0** [comment]
Should the database related stuff for `ExternalDb` be updated as well? If so, then the data generation logic should also be updated.

**Comment by mihai-sysbio** [comment]
>  If HPA make use of these url:s or if it is easy to implement, ensure backwards compatibility as well (for example in nginx)

All endpoints used by [HPA](https://proteinatlas.org) are grouped under `/hpa`, so here is nothing to here.
